/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface _ACAccountTypeIdentifierTwitter (_10906268_)
- (BOOL)__enumerateAssetsAtIndexes:(id)fp8 options:(unsigned int)fp12 usingBlock:(id)fp(null);
@end

