/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface _ACAccountTypeIdentifierTwitter (MRMarimbaViewPlayback)
- (void)gotoSlide:(id)fp8;
- (void)gotoPreviousSlide;
- (void)gotoNextSlide;
- (id)currentSlide;
- (id)currentSlides;
- (void)watcherThread:(id)fp8;
- (int)_mainLayerIndex;
- (id)_effectContainerForTime:(double)fp8;
- (id)_firstEffectContainer;
- (id)_currentEffectContainer;
- (void)moveToSubtitleForSlide:(id)fp8;
- (void)moveToTitleSlide;
- (void)moveToPreviousEffectContainer;
- (void)moveToNextEffectContainer;
- (void)moveToEffectContainer:(id)fp8 withStartOffset:(double)fp12 toStopOffset:(double)fp20 blocking:(BOOL)fp28;
- (id)displayedEffectContainers;
- (double)relativeTimeForLayer:(id)fp8;
- (double)relativeTimeForBackgroundAudio;
- (double)relativeTime;
@end

