/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface _ACAccountTypeIdentifierTwitter (RCAdditions)
+ (id)stringFromOSErr:(short)fp8;
+ (id)stringWithTripleDecimalFloat:(float)fp8;
+ (id)stringWithSingleDecimalFloat:(float)fp8;
+ (id)stringWithNumerator:(int)fp8 denominator:(int)fp12;
+ (id)stringWithInt:(int)fp8;
+ (id)formattedDiskSpace:(double)fp8;
+ (id)pathComponent:(id)fp8 componentIndex:(unsigned int)fp12;
+ (id)pathComponents:(id)fp8 firstComponentIndex:(unsigned int)fp12 lastComponentIndex:(unsigned int)fp16;
- (id)stringByTrimmingWhiteSpace;
- (int)widthOnActionSheet;
- (BOOL)containsString:(id)fp8;
- (id)filterErrorDescription;
- (id)setterName;
- (id)string;
- (int)caseInsensitiveLocalizedNumericCompare:(id)fp8;
- (id)singleLineString;
- (id)lastTwoPathComponents;
- (id)appendToPathname:(id)fp8;
- (int)comparePathModificationDates:(id)fp8;
- (id)pathRelativeToComponent:(id)fp8;
@end

