/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface _ACAccountTypeIdentifierTwitter (SizeToFitBox)
- (void)parametersToFitInSize:(struct CGSize)fp8 font:(id)fp16 minPointSize:(float)fp20 maxPointSize:(float)fp24 multiLine:(BOOL)fp28 actualFont:(id *)fp32 actualSize:(struct CGSize *)fp36;
@end

