/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSLock, NSString;

@interface _BLReachabilityRequest : _ACAccountTypeIdentifierTwitter
{
    NSLock *_lock;
    NSString *_hostname;
    struct __SCNetworkReachability *_reachability;
    unsigned int _flags;
    struct __CFDictionary *_observers;
    BOOL _isReachable;
    BOOL _receivedAtLeastOneCallback;
}

- (void)setHostname:(id)fp8;
- (id)hostname;
- (BOOL)hasObservers;
- (void)removeObserver:(id)fp8;
- (void)addObserver:(id)fp8 selector:(SEL)fp12;
- (void)reachabilityChangedWithFlags:(unsigned int)fp8;
- (id)description;
- (void)dealloc;
- (id)initWithHostname:(id)fp8;

@end

