/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "NSCopying-Protocol.h"

@class NSArray;

@interface AutoEncodeDecodeObject : _ACAccountTypeIdentifierTwitter <NSCopying>
{
    NSArray *m_keysToEncode;
}

- (void)setKeysToEncode:(id)fp8;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (BOOL)isEqualToObject:(id)fp8;
- (id)description;
- (id)keysToEncode;
- (id)getKeysToEncode;

@end

