/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface BLActionSheet : _ACAccountTypeIdentifierTwitter
{
    int m_width;
    struct CGSize m_fixedSize;
}

- (void)setFixedSize:(struct CGSize)fp8;
- (struct CGSize)fixedSize;
- (id)initWithTitle:(id)fp8 delegate:(id)fp12 cancelButtonTitle:(id)fp16 destructiveButtonTitle:(id)fp20 otherButtonTitles:(id)fp24;
- (void)setFont:(id)fp8 forButtonWithTitle:(id)fp12;
- (void)setButtonFont:(id)fp8;
- (void)setButtonFont:(id)fp8 inView:(id)fp12;
- (void)setEnable:(BOOL)fp8 forButtonWithTitle:(id)fp12;
- (id)buttonWithTitle:(id)fp8 inView:(id)fp12;
- (int)addButtonWithTitle:(id)fp8;
- (void)setFrame:(struct CGRect)fp8;

@end

