/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLMainTabItemView.h"

@interface BLAlbumListItem : BLMainTabItemView
{
}

- (id)key;
- (void)setObject:(id)fp8;
- (void)albumContentsChanged:(id)fp8;
- (id)imageCache;
- (id)posterMedia;
- (BOOL)wantHighResThumbnails;
- (int)thumbSize;
- (id)initWithFrame:(struct CGRect)fp8 index:(int)fp24;
- (void)showEditor;
- (void)setName:(id)fp8 album:(id)fp12;
- (id)imageNameForIndex:(int)fp8;

@end

