/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLMainTabController.h"

#import "UIScrollViewDelegate-Protocol.h"

@class NSArray;

@interface BLAlbumListViewController : BLMainTabController <UIScrollViewDelegate>
{
    NSArray *m_arrangedAlbums;
}

+ (id)viewController;
- (void)setArrangedAlbums:(id)fp8;
- (id)arrangedAlbums;
- (void)dealloc;
- (id)initWithController:(id)fp8;
- (id)emptyImageKey;
- (id)emptyLabel;
- (id)helpTag;
- (void)setupObjects;
- (void)viewDidUnload;
- (id)objectsToDisplay;
- (Class)itemViewClass;
- (Class)cellClass;
- (id)tabNibName;

@end

