/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIImageView;

@interface BLAnimatedHighlightImageView : _ACAccountTypeIdentifierTwitter
{
    UIImageView *m_highlightView;
}

- (void)setHighlightView:(id)fp8;
- (id)highlightView;
- (void)setHighlightedImage:(id)fp8;
- (void)dealloc;
- (void)setHighlighted:(BOOL)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithImage:(id)fp8 highlightedImage:(id)fp12;
- (void)_createHighlightImageView:(id)fp8;

@end

