/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UILabel;

@interface BLAndNMoreView : _ACAccountTypeIdentifierTwitter
{
    int m_count;
    UILabel *m_label;
}

- (int)count;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)setCount:(int)fp8;

@end

