/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface BLAttributedLabel : _ACAccountTypeIdentifierTwitter
{
}

+ (id)labelForKey:(id)fp8 size:(float)fp12 color:(id)fp16;
+ (Class)layerClass;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (id)attributedString;
- (void)setAttributedString:(id)fp8;

@end

