/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSString;

@interface BLBlurredLabel : _ACAccountTypeIdentifierTwitter
{
    NSString *m_label;
}

- (id)label;
- (void)dealloc;
- (id)initWithLabel:(id)fp8;
- (void)setLabel:(id)fp8;
- (void)sizeToFit;
- (struct CGSize)sizeForString:(id)fp8;
- (void)drawRect:(struct CGRect)fp8;
- (void)drawInRect:(struct CGRect)fp8 withXOffset:(float)fp24 yOffset:(float)fp28;
- (id)font;

@end

