/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIImageView;

@interface BLButtonWithImage : _ACAccountTypeIdentifierTwitter
{
    UIImageView *m_buttonImageView;
}

- (void)setButtonImageView:(id)fp8;
- (id)buttonImageView;
- (void)setHighlighted:(BOOL)fp8;

@end

