/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLImage.h"

@interface BLCGImage : BLImage
{
}

- (id)CIImage;
- (id)UIImage;
- (id)initWithFileAtURL:(id)fp8;
- (id)initWithCGImage:(struct CGImage *)fp8;

@end

