/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIView;

@interface BLColorControlsWrapper : _ACAccountTypeIdentifierTwitter
{
    UIView *m_saturation;
    UIView *m_sky;
    UIView *m_plants;
    UIView *m_skin;
    UIView *m_div1;
    UIView *m_div2;
    UIView *m_div3;
}

- (void)setM_div3:(id)fp8;
- (id)m_div3;
- (void)setM_div2:(id)fp8;
- (id)m_div2;
- (void)setM_div1:(id)fp8;
- (id)m_div1;
- (void)setM_skin:(id)fp8;
- (id)m_skin;
- (void)setM_plants:(id)fp8;
- (id)m_plants;
- (void)setM_sky:(id)fp8;
- (id)m_sky;
- (void)setM_saturation:(id)fp8;
- (id)m_saturation;
- (void)dealloc;
- (void)setFrame:(struct CGRect)fp8;

@end

