/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLExposureView.h"

@interface BLColorView : BLExposureView
{
}

- (void)type:(int)fp8 getMin:(float *)fp12 max:(float *)fp16 scale:(float *)fp20;
- (id)keyForType:(int)fp8;
- (void)adjustmentTypesForLocation:(struct CGPoint)fp8 horizontal:(int *)fp16 vertical:(int *)fp20;

@end

