/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIView;

@interface BLColorSettingsViewController : _ACAccountTypeIdentifierTwitter
{
    UIView *landscapeView;
    UIView *portraitView;
}

- (void)setPortraitView:(id)fp8;
- (id)portraitView;
- (void)setLandscapeView:(id)fp8;
- (id)landscapeView;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

