/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLEffectView.h"

@class UIImageView, UIView;

@interface BLColorSlider : BLEffectView
{
    UIImageView *m_lineView;
    UIView *m_indicatorView;
    UIView *m_coverView;
    float m_minValue;
    float m_maxValue;
    BOOL m_dragging;
    BOOL m_disableAnimations;
    struct CGPoint m_lineCenter;
}

- (void)setMaxValue:(float)fp8;
- (void)setMinValue:(float)fp8;
- (float)minValue;
- (struct CGPoint)lineCenter;
- (void)setM_coverView:(id)fp8;
- (id)m_coverView;
- (void)setM_indicatorView:(id)fp8;
- (id)m_indicatorView;
- (void)setM_lineView:(id)fp8;
- (id)m_lineView;
- (void)dealloc;
- (void)awakeFromNib;
- (void)willMoveToWindow:(id)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)setValue:(float)fp8;
- (void)updateIndicator;
- (void)updateThumb;
- (void)setLineCenter:(struct CGPoint)fp8;
- (void)userPanned:(id)fp8;
- (void)effectDidChange:(id)fp8;
- (void)effectWillChange:(id)fp8;
- (int)lineInset;
- (float)maxValue;

@end

