/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface BLColorMatrix : _ACAccountTypeIdentifierTwitter
{
}

+ (CDAnonymousStruct9)artisticMatrix:(int)fp8;
+ (CDAnonymousStruct9)cartoonMatrix:(int)fp8;
+ (CDAnonymousStruct9)vintageMatrix:(float)fp8;
+ (CDAnonymousStruct9)warmCoolMatrix:(float)fp8;
+ (CDAnonymousStruct9)blackAndWhiteMatrix:(float)fp8;
+ (CDAnonymousStruct9)matrix:(float)fp8 numBlocks:(int)fp12 matrices:(CDAnonymousStruct9 *)fp16;
+ (CDAnonymousStruct9)mix:(float)fp8 matrix1:(CDAnonymousStruct9)fp12 matrix2:(CDAnonymousStruct9)fp60;
+ (CDAnonymousStruct5)mix:(float)fp8 channelMix1:(CDAnonymousStruct5)fp12 channelMix2:(CDAnonymousStruct5)fp28;
+ (struct CGContext *)newContext:(struct CGContext *)fp8 withWithColorMatrix:(CDAnonymousStruct9 *)fp12;

@end

