/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIImageView, UIView;

@interface BLCropGuideOverlayView : _ACAccountTypeIdentifierTwitter
{
    BOOL m_manualCropMode;
    float m_aspectRatio;
    struct CGRect m_cropRect;
    UIView *m_topOpaqueView;
    UIView *m_bottomOpaqueView;
    UIView *m_rightOpaqueView;
    UIView *m_leftOpaqueView;
    UIView *m_topLinenView;
    UIView *m_topLinenPatternView;
    UIView *m_bottomLinenView;
    UIView *m_bottomLinenPatternView;
    UIView *m_rightLinenView;
    UIView *m_rightLinenPatternView;
    UIView *m_leftLinenView;
    UIView *m_leftLinenPatternView;
    UIImageView *m_topEdgeView;
    UIImageView *m_bottomEdgeView;
    UIImageView *m_rightEdgeView;
    UIImageView *m_leftEdgeView;
    UIImageView *m_topEdgeAlternateView;
    UIImageView *m_bottomEdgeAlternateView;
    UIImageView *m_rightEdgeAlternateView;
    UIImageView *m_leftEdgeAlternateView;
    UIImageView *m_topLeftCornerView;
    UIImageView *m_topRightCornerView;
    UIImageView *m_bottomRightCornerView;
    UIImageView *m_bottomLeftCornerView;
    UIImageView *m_topLeftCornerAlternateView;
    UIImageView *m_topRightCornerAlternateView;
    UIImageView *m_bottomRightCornerAlternateView;
    UIImageView *m_bottomLeftCornerAlternateView;
    UIImageView *m_topThirdView;
    UIImageView *m_bottomThirdView;
    UIImageView *m_rightThirdView;
    UIImageView *m_leftThirdView;
    UIImageView *m_straightenHorizontalViews[6];
    UIImageView *m_straightenVerticalViews[6];
    BOOL m_cornersVisible;
    BOOL m_thirdsVisible;
    BOOL m_straightenVisible;
}

- (void)setAspectRatio:(float)fp8;
- (float)aspectRatio;
- (void)setManualCropMode:(BOOL)fp8;
- (BOOL)manualCropMode;
- (int)stretchForPoint:(struct CGPoint)fp8;
- (int)cropActionForPoint:(struct CGPoint)fp8;
- (void)flashStraightenGrid;
- (void)showStraightenGrid:(BOOL)fp8;
- (void)showThirdsGrid:(BOOL)fp8;
- (void)layoutSubviews;
- (void)setCropRect:(struct CGRect)fp8;
- (struct CGRect)cropRect;
- (void)dealloc;
- (void)setupSubviews;
- (id)initWithCoder:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

