/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLEffectSettingsViewController.h"

@class UIView;

@interface BLCropSelectorViewController : BLEffectSettingsViewController
{
    id <BLCropSelectorTarget> m_target;
    UIView *m_landscapeView;
    UIView *m_portraitView;
}

- (void)setLandscapeView:(id)fp8;
- (id)landscapeView;
- (void)setPortraitView:(id)fp8;
- (id)portraitView;
- (void)setTarget:(id)fp8;
- (id)target;
- (void)a_reset:(id)fp8;
- (void)a_done:(id)fp8;
- (void)a_constraint:(id)fp8;
- (void)setImage:(id)fp8 forConstraint:(int)fp12 animated:(BOOL)fp16;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

