/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface BLCurveSpline : _ACAccountTypeIdentifierTwitter
{
}

+ (void)splineCurveTable:(float *)fp8 tableSize:(int)fp12 gamma:(float)fp16 from:(const struct CGPoint *)fp20;

@end

