/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLSharingServiceViewController.h"

@class NSDate, UIDatePicker;

@interface BLDatePickerViewController : BLSharingServiceViewController
{
    NSDate *m_date;
    UIDatePicker *m_datePicker;
    id <BLDatePickerViewDelegate> m_delegate;
}

- (id)selectedDate;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)loadView;
- (void)dateChanged:(id)fp8;
- (struct CGSize)requiredPopoverSize;
- (void)setPopoverDelegate:(id)fp8;
- (void)dealloc;
- (id)initWithDate:(id)fp8 delegate:(id)fp12;

@end

