/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLDBManager.h"

@interface BLDBManager (Public)
- (id)coalesceNotificationsWithSync:(BOOL)fp8 resultBlock:(id)fp(null);
- (id)deleteMediaWithList:(id)fp8 keepFlagged:(BOOL)fp12 beamed:(BOOL)fp16 ubiquitous:(BOOL)fp20 sync:(BOOL)fp24 resultBlock:(id)fp(null);
- (id)deleteMediaWithUuid:(id)fp8 keepFlagged:(BOOL)fp12 beamed:(BOOL)fp16 ubiquitous:(BOOL)fp20 sync:(BOOL)fp24 resultBlock:(id)fp(null);
- (id)createOrUpdateMediaWithData:(id)fp8 beamed:(BOOL)fp12 ubiquitous:(BOOL)fp16 sync:(BOOL)fp20 resultBlock:(id)fp(null);
- (id)deleteMediaAttachmentFilesWithMediaUuid:(id)fp8 typeMask:(int)fp12 beamed:(BOOL)fp16 ubiquitous:(BOOL)fp20 sync:(BOOL)fp24 resultBlock:(id)fp(null);
- (id)createOrUpdateMediaAttachmentFilesWithMediaUuid:(id)fp8 type:(int)fp12 pathExtension:(id)fp16 data:(id)fp20 beamed:(BOOL)fp24 ubiquitous:(BOOL)fp28 sync:(BOOL)fp32 resultBlock:(id)fp(null);
- (id)deleteAttachmentFilesWithJournal:(id)fp8 typeMask:(int)fp12 beamed:(BOOL)fp16 ubiquitous:(BOOL)fp20 sync:(BOOL)fp24 resultBlock:(id)fp(null);
- (id)deleteAttachmentFilesWithMedia:(id)fp8 typeMask:(int)fp12 beamed:(BOOL)fp16 ubiquitous:(BOOL)fp20 sync:(BOOL)fp24 resultBlock:(id)fp(null);
- (id)writeAttachmentFileWithJournal:(id)fp8 type:(int)fp12 content:(id)fp16 ifExists:(BOOL)fp20 beamed:(BOOL)fp24 ubiquitous:(BOOL)fp28 sync:(BOOL)fp32 resultBlock:(id)fp(null);
- (id)writeAttachmentFileWithMedia:(id)fp8 type:(int)fp12 pathExtension:(id)fp16 content:(id)fp20 ifExists:(BOOL)fp24 beamed:(BOOL)fp28 ubiquitous:(BOOL)fp32 sync:(BOOL)fp36 resultBlock:(id)fp(null);
- (void)readAttachmentFileWithJournal:(id)fp8 type:(int)fp12 sync:(BOOL)fp16 persistent:(BOOL)fp20 resultBlock:(id)fp(null);
- (void)readAttachmentFilesWithMedia:(id)fp8 typeMask:(int)fp12 useAlternate:(BOOL)fp16 sync:(BOOL)fp20 persistent:(BOOL)fp24 resultBlock:(id)fp(null);
- (void)readAttachmentFileWithMedia:(id)fp8 type:(int)fp12 useAlternate:(BOOL)fp16 sync:(BOOL)fp20 persistent:(BOOL)fp24 resultBlock:(id)fp(null);
- (id)mergeAttachmentFileWithMedia:(id)fp8 type:(int)fp12 hint:(id)fp16 sync:(BOOL)fp20 mergeAttachmentFileSyncBlock:(id)fp(null) resultBlock:(void)fp24;
- (id)executeAdjustmentsWithMedia:(id)fp8 combinedAdjustments:(id)fp12 orClockwise90DegreeTurns:(int)fp16 originalFullResolutionImage:(id)fp20 useOriginalFullResolutionImage:(BOOL)fp24 context:(id)fp28 sync:(BOOL)fp32 beginExecuteAdjustmentsBlock:(id)fp(null) prepareGenerateImageSyncBlock:(void)fp36 executeGenerateImageSyncBlock:(id)fp(null) endExecuteAdjustmentsBlock:(void)fp40;
- (id)deleteAssetsLibraryAlbumUuid:(id)fp8 withSync:(BOOL)fp12 resultBlock:(id)fp(null);
- (id)disassociateMediaList:(id)fp8 fromAssetsLibraryAlbumUuid:(id)fp12 withSync:(BOOL)fp16 resultBlock:(id)fp(null);
- (id)associateMediaList:(id)fp8 toAssetsLibraryAlbumUuid:(id)fp12 withSync:(BOOL)fp16 resultBlock:(id)fp(null);
- (id)createAssetsLibraryAlbumWithName:(id)fp8 sync:(BOOL)fp12 resultBlock:(id)fp(null);
- (id)writeImageToAssetsLibrarySavedPhotosAlbumWithImage:(struct CGImage *)fp8 usingMetadataFromMedia:(id)fp12 orDictionary:(id)fp16 sync:(BOOL)fp20 resultBlock:(id)fp(null);
- (id)writeImageDataToAssetsLibrarySavedPhotosAlbumWithData:(id)fp8 usingMetadataFromMedia:(id)fp12 orDictionary:(id)fp16 sync:(BOOL)fp20 resultBlock:(id)fp(null);
- (id)endWriteToAssetsLibraryAlbumWithCount:(unsigned int)fp8 sync:(BOOL)fp12 resultBlock:(id)fp(null);
- (id)beginWriteToAssetsLibraryAlbumWithSync:(BOOL)fp8 resultBlock:(id)fp(null);
- (id)deleteAlbum:(id)fp8 withSync:(BOOL)fp12 resultBlock:(id)fp(null);
- (id)disassociateMediaList:(id)fp8 fromSmartAlbumType:(int)fp12 withBeamed:(BOOL)fp16 ubiquitous:(BOOL)fp20 sync:(BOOL)fp24 resultBlock:(id)fp(null);
- (id)associateMediaList:(id)fp8 toSmartAlbumType:(int)fp12 withBeamed:(BOOL)fp16 ubiquitous:(BOOL)fp20 sync:(BOOL)fp24 resultBlock:(id)fp(null);
- (id)disassociateMediaList:(id)fp8 fromAlbum:(id)fp12 withSync:(BOOL)fp16 progressBlock:(id)fp(null) resultBlock:(void)fp20;
- (id)associateMediaList:(id)fp8 toAlbum:(id)fp12 withSync:(BOOL)fp16 progressBlock:(id)fp(null) resultBlock:(void)fp20;
- (id)createAlbumWithName:(id)fp8 journal:(id)fp12 sync:(BOOL)fp16 resultBlock:(id)fp(null);
- (id)createAlbumWithName:(id)fp8 type:(int)fp12 sync:(BOOL)fp16 resultBlock:(id)fp(null);
- (id)updateAlbumPosterMediasWithRejectedMediaList:(id)fp8 rejected:(BOOL)fp12 sync:(BOOL)fp16 resultBlock:(id)fp(null);
- (id)testIfMediaList:(id)fp8 isBoundToAlbum:(id)fp12 withSync:(BOOL)fp16 resultBlock:(id)fp(null);
- (void)mediaWithUuid:(id)fp8 sync:(BOOL)fp12 persistent:(BOOL)fp16 resultBlock:(id)fp(null);
- (void)mediaWithKey:(unsigned int)fp8 sync:(BOOL)fp12 persistent:(BOOL)fp16 resultBlock:(id)fp(null);
- (void)mediaListWithAlbum:(id)fp8 predicate:(id)fp12 sync:(BOOL)fp16 persistent:(BOOL)fp20 resultBlock:(id)fp(null);
- (void)albumWithJournalUuid:(id)fp8 sync:(BOOL)fp12 persistent:(BOOL)fp16 resultBlock:(id)fp(null);
- (void)albumWithKey:(unsigned int)fp8 sync:(BOOL)fp12 persistent:(BOOL)fp16 resultBlock:(id)fp(null);
- (void)albumListWithALType:(unsigned int)fp8 sync:(BOOL)fp12 persistent:(BOOL)fp16 resultBlock:(id)fp(null);
- (void)mediaListWithPredicate:(id)fp8 sync:(BOOL)fp12 persistent:(BOOL)fp16 resultBlock:(id)fp(null);
- (void)mediaListWithPredicate:(id)fp8 sync:(BOOL)fp12 persistent:(BOOL)fp16 ignoreCache:(BOOL)fp20 resultBlock:(id)fp(null);
- (void)assignUserPosterMedia:(id)fp8 toAlbum:(id)fp12 completionBlock:(id)fp(null);
- (void)videoPlaybackURLWithMedia:(id)fp8 sync:(BOOL)fp12 completionBlock:(id)fp(null);
- (void)assetWithMedia:(id)fp8 wantsThumbnail:(BOOL)fp12 completionBlock:(id)fp(null);
- (void)assetWithMediaUuid:(id)fp8 wantsThumbnail:(BOOL)fp12 completionBlock:(id)fp(null);
- (void)assetWithURL:(id)fp8 wantsThumbnail:(BOOL)fp12 completionBlock:(id)fp(null);
- (void)applicationDidBecomeActive;
- (void)applicationDidEnterBackground;
- (void)terminate;
- (void)cancelRequest:(id)fp8;
- (void)postRequest:(id)fp8;
- (void)restoreFileFromBackupWithPath:(id)fp8;
- (id)backupFileWithPath:(id)fp8;
- (id)backupPathWithPath:(id)fp8;
- (void)batchUpdateModelList:(id)fp8 withPredicate:(id)fp12 propertyKey:(id)fp16 value:(id)fp20 validatorBlock:(id)fp(null) completionBlock:(void)fp24;
- (void)didUpdateWithModel:(id)fp8 propertyKey:(id)fp12 oldValue:(id)fp16 beamed:(BOOL)fp20 ubiquitous:(BOOL)fp24 needsResort:(char *)fp28;
- (void)didUpdateWithModel:(id)fp8 propertyKeyList:(id)fp12 oldValueList:(id)fp16 beamed:(BOOL)fp20 ubiquitous:(BOOL)fp24 needsResort:(char *)fp28;
- (id)deleteDatabaseModelListWithClass:(Class)fp8 attribute:(id)fp12 value:(id)fp16;
- (id)deleteDatabaseModel:(id)fp8;
- (id)updateDatabaseModelList:(id)fp8 withModelClassMask:(int)fp12;
- (id)updateDatabaseModelList:(id)fp8 withAttributes:(id)fp12;
- (id)updateDatabaseModel:(id)fp8 withAttributes:(id)fp12;
- (id)insertDatabaseModelList:(id)fp8 abortBlock:(id)fp(null);
- (id)insertDatabaseModel:(id)fp8;
- (id)writeDatabaseModelGraphWithWritingMask:(int)fp8 abortBlock:(id)fp(null);
- (id)readDatabaseModelGraphWithReadingMask:(int)fp8 abortBlock:(id)fp(null);
- (id)sandboxAttachmentFilePathWithType:(int)fp8 uuid:(id)fp12 parentDirPath:(id *)fp16;
- (id)assetsLibrary;
- (void)removeDatabaseFiles;
- (BOOL)databaseExists;
- (id)databasePathNames;
- (id)initWithDirPath:(id)fp8 schema:(int)fp12;
@end

