/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLDBGenericModel.h"

@interface BLDBKeywordMediaJoin : BLDBGenericModel
{
    unsigned int m_keywordKey;
    unsigned int m_mediaKey;
    unsigned int m_index;
}

+ (id)sortModelListByAscendingKeywordKeys:(id)fp8;
+ (id)keywordKeyIndexSetWithMediaKey:(unsigned int)fp8 inModelList:(id)fp12 abortBlock:(id)fp(null);
+ (id)indexSetWithMediaKey:(unsigned int)fp8 inModelList:(id)fp12 abortBlock:(id)fp(null);
+ (id)keywordKeysWithMediaKey:(unsigned int)fp8 inModelList:(id)fp12 abortBlock:(id)fp(null);
+ (id)mediaKeysWithKeywordKey:(unsigned int)fp8 inModelList:(id)fp12 atIndexes:(id *)fp16 abortBlock:(id)fp(null);
+ (id)modelWithKeywordKey:(unsigned int)fp8 mediaKey:(unsigned int)fp12 inModelList:(id)fp16 abortBlock:(id)fp(null);
+ (id)keywordKeysInModelList:(id)fp8 abortBlock:(id)fp(null);
+ (int)endDeleteTableRowsWithDB:(struct sqlite3 *)fp8 schema:(int)fp12 stmt:(struct sqlite3_stmt *)fp16 accessLock:(id)fp20;
+ (int)deleteModel:(id)fp8 withSchema:(int)fp12 stepData:(struct sqlite3_stmt *)fp16;
+ (int)beginDeleteTableRowsWithDB:(struct sqlite3 *)fp8 schema:(int)fp12 stmt:(struct sqlite3_stmt **)fp16 accessLock:(id)fp20;
+ (int)endUpdateTableRowsWithDB:(struct sqlite3 *)fp8 attributes:(id)fp12 schema:(int)fp16 stmt:(struct sqlite3_stmt *)fp20 accessLock:(id)fp24;
+ (int)updateModel:(id)fp8 withAttributes:(id)fp12 schema:(int)fp16 stepData:(struct sqlite3_stmt *)fp20;
+ (int)beginUpdateTableRowsWithDB:(struct sqlite3 *)fp8 attributes:(id)fp12 schema:(int)fp16 stmt:(struct sqlite3_stmt **)fp20 accessLock:(id)fp24;
+ (id)tableAttributesWithSchema:(int)fp8;
+ (id)tableNameWithSchema:(int)fp8;
- (void)setIndex:(unsigned int)fp8;
- (unsigned int)index;
- (void)setMediaKey:(unsigned int)fp8;
- (unsigned int)mediaKey;
- (void)setKeywordKey:(unsigned int)fp8;
- (unsigned int)keywordKey;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (BOOL)isEqual:(id)fp8;
- (id)description;
- (void)dealloc;

@end

