/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLDBGenericModel.h"

@class NSString;

@interface BLDBKeyword : BLDBGenericModel
{
    NSString *m_title;
    unsigned int m_sortIndex;
}

+ (id)sortModelListByAscendingSortIndexes:(id)fp8;
+ (id)titlesInModelsList:(id)fp8 abortBlock:(id)fp(null);
+ (id)modelsWithTitleInList:(id)fp8 inModelList:(id)fp12 abortBlock:(id)fp(null);
+ (id)modelWithTitle:(id)fp8 inModelList:(id)fp12 abortBlock:(id)fp(null);
+ (BOOL)isModelKeyUsedForSort:(id)fp8;
+ (id)tableAttributesWithSchema:(int)fp8;
+ (id)tableNameWithSchema:(int)fp8;
- (void)setSortIndex:(unsigned int)fp8;
- (void)setTitle:(id)fp8;
- (unsigned int)sortIndex;
- (id)title;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)description;
- (void)dealloc;

@end

