/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "BLDBFilePresenterModel-Protocol.h"
#import "NSCopying-Protocol.h"

@class BLDBManager, NSString;

@interface BLDBGenericModel : _ACAccountTypeIdentifierTwitter <NSCopying, BLDBFilePresenterModel>
{
    unsigned int m_primaryKey;
    NSString *m_uuid;
    BLDBManager *m_databaseManager;
    BOOL m_transient;
    int _ignoreDidUpdateCounter;
}

+ (id)stateDebugStringWithTypeMask:(int)fp8;
+ (BOOL)isModelKeyListEditable:(id)fp8;
+ (BOOL)isModelKeyListSerializable:(id)fp8;
+ (BOOL)isModelKeyUsedForSort:(id)fp8;
+ (id)displayableUuidWithUUid:(id)fp8;
+ (BOOL)removeModelWithUuid:(id)fp8 fromModelList:(id)fp12 abortBlock:(id)fp(null);
+ (unsigned int)addModelListIfNotPresent:(id)fp8 toModelList:(id)fp12 abortBlock:(id)fp(null);
+ (BOOL)addModelIfNotPresent:(id)fp8 toModelList:(id)fp12 abortBlock:(id)fp(null);
+ (id)sortModelListByAscendingUuids:(id)fp8;
+ (id)sortModelListByAscendingPrimaryKeys:(id)fp8;
+ (id)primaryKeyIndexSetInModelList:(id)fp8 abortBlock:(id)fp(null);
+ (id)primaryKeysInModelList:(id)fp8 abortBlock:(id)fp(null);
+ (id)modelsWithPrimaryKeyInIndexSet:(id)fp8 inModelList:(id)fp12 usingIndexModelList:(id)fp16 abortBlock:(id)fp(null);
+ (id)modelsWithPrimaryKeyInList:(id)fp8 inModelList:(id)fp12 usingIndexModelList:(id)fp16 abortBlock:(id)fp(null);
+ (id)modelsWithPrimaryKeyInList:(id)fp8 inModelList:(id)fp12 abortBlock:(id)fp(null);
+ (id)modelWithUuid:(id)fp8 inModelList:(id)fp12 usingIndexModelList:(id)fp16 atIndex:(unsigned int *)fp20 abortBlock:(id)fp(null);
+ (id)modelWithUuid:(id)fp8 inModelList:(id)fp12 usingIndexModelList:(id)fp16 abortBlock:(id)fp(null);
+ (id)modelWithUuid:(id)fp8 inModelList:(id)fp12 atIndex:(unsigned int *)fp16 abortBlock:(id)fp(null);
+ (id)modelWithUuid:(id)fp8 inModelList:(id)fp12 abortBlock:(id)fp(null);
+ (id)modelWithPrimaryKey:(unsigned int)fp8 inModelList:(id)fp12 usingIndexModelList:(id)fp16 atIndex:(unsigned int *)fp20 abortBlock:(id)fp(null);
+ (id)modelWithPrimaryKey:(unsigned int)fp8 inModelList:(id)fp12 usingIndexModelList:(id)fp16 abortBlock:(id)fp(null);
+ (id)modelWithPrimaryKey:(unsigned int)fp8 inModelList:(id)fp12 abortBlock:(id)fp(null);
+ (id)modelWithModel:(id)fp8;
+ (int)endDeleteTableRowsWithDB:(struct sqlite3 *)fp8 schema:(int)fp12 stmt:(struct sqlite3_stmt *)fp16 accessLock:(id)fp20;
+ (int)deleteModelsWithSchema:(int)fp8 attribute:(id)fp12 value:(id)fp16 stepData:(struct sqlite3_stmt *)fp20;
+ (int)beginDeleteTableRowsWithDB:(struct sqlite3 *)fp8 schema:(int)fp12 attribute:(id)fp16 stmt:(struct sqlite3_stmt **)fp20 accessLock:(id)fp24;
+ (int)endUpdateTableRowsWithDB:(struct sqlite3 *)fp8 attributes:(id)fp12 schema:(int)fp16 stmt:(struct sqlite3_stmt *)fp20 accessLock:(id)fp24;
+ (int)updateModel:(id)fp8 withAttributes:(id)fp12 schema:(int)fp16 stepData:(struct sqlite3_stmt *)fp20;
+ (int)beginUpdateTableRowsWithDB:(struct sqlite3 *)fp8 attributes:(id)fp12 schema:(int)fp16 stmt:(struct sqlite3_stmt **)fp20 accessLock:(id)fp24;
+ (int)endWriteTableRowsWithDB:(struct sqlite3 *)fp8 schema:(int)fp12 stmt:(struct sqlite3_stmt *)fp16 accessLock:(id)fp20;
+ (int)writeModel:(id)fp8 withSchema:(int)fp12 attributes:(id)fp16 stepData:(struct sqlite3_stmt *)fp20;
+ (int)beginWriteTableRowsWithDB:(struct sqlite3 *)fp8 schema:(int)fp12 assignPrimaryKey:(unsigned int)fp16 attributes:(id *)fp20 stmt:(struct sqlite3_stmt **)fp24 accessLock:(id)fp28;
+ (int)endReadTableRowsWithDB:(struct sqlite3 *)fp8 schema:(int)fp12 stmt:(struct sqlite3_stmt *)fp16 accessLock:(id)fp20;
+ (int)readModelWithStepData:(struct sqlite3_stmt *)fp8 schema:(int)fp12 attributes:(id)fp16 model:(id *)fp20;
+ (int)beginReadTableRowsWithDB:(struct sqlite3 *)fp8 schema:(int)fp12 attributes:(id *)fp16 stmt:(struct sqlite3_stmt **)fp20 accessLock:(id)fp24;
+ (int)numberOfRowsInTableWithDB:(struct sqlite3 *)fp8 schema:(int)fp12 accessLock:(id)fp16 count:(unsigned int *)fp20;
+ (int)destroyTableWithDB:(struct sqlite3 *)fp8 schema:(int)fp12 accessLock:(id)fp16;
+ (int)createTableWithDB:(struct sqlite3 *)fp8 schema:(int)fp12 accessLock:(id)fp16;
+ (id)tablePrimaryKeyAttributeWithSchema:(int)fp8;
+ (id)tableAttributesWithSchema:(int)fp8 inModelKeySet:(id)fp12;
+ (id)tableAttributesWithSchema:(int)fp8;
+ (id)tableNameWithSchema:(int)fp8;
+ (id)_makeDeleteTableRowStatementWithName:(id)fp8 attributes:(id)fp12;
+ (id)_makeUpdateTableRowStatementWithName:(id)fp8 attributes:(id)fp12;
+ (id)_makeInsertTableRowStatementWithName:(id)fp8 attributes:(id)fp12;
+ (id)_makeReadTableRowStatementWithName:(id)fp8 attributes:(id)fp12;
+ (id)_makeCreateTableStatementWithName:(id)fp8 attributes:(id)fp12;
- (void)setTransient:(BOOL)fp8;
- (BOOL)transient;
- (void)setDatabaseManager:(id)fp8;
- (id)databaseManager;
- (void)setUuid:(id)fp8;
- (id)uuid;
- (void)setPrimaryKey:(unsigned int)fp8;
- (unsigned int)primaryKey;
- (BOOL)setValue:(id)fp8 forPropertyKey:(id)fp12 beamed:(BOOL)fp16 ubiquitous:(BOOL)fp20;
- (int)popIgnoreDidUpdate;
- (int)pushIgnoreDidUpdate;
- (void)mergeWithAssetsLibraryDerivedModel:(id)fp8;
- (void)prepareForReuse;
- (id)displayableUuid;
- (BOOL)areEditablePropertiesSetToInitialValues;
- (void)setEditablePropertiesToInitialValues;
- (id)dictionary;
- (id)shortDictionary;
- (id)reinitWithDictionary:(id)fp8 changedPropertyKeyList:(id)fp12 oldValueList:(id)fp16;
- (id)initWithDictionary:(id)fp8;
- (id)initWithDatabaseManager:(id)fp8;
- (id)cloneWithModel:(id)fp8 changedPropertyKeyList:(id)fp12 oldValueList:(id)fp16;
- (id)reallyCopyWithZone:(struct _NSZone *)fp8;
- (BOOL)ignoreDidUpdate;
- (BOOL)updateStateWithAddedMask:(unsigned int)fp8 removedMask:(unsigned int)fp12 beamed:(BOOL)fp16 ubiquitous:(BOOL)fp20;
- (unsigned int)state;
- (id)archivableContent;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (BOOL)isEqual:(id)fp8;
- (id)description;
- (id)valueForUndefinedKey:(id)fp8;
- (void)dealloc;
- (id)init;

@end

