/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLViewController.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@class BLAlbum, BLMainViewController, NSUndoManager, UIButton;

@interface BLEditor : BLViewController <UIPopoverControllerDelegate, UIActionSheetDelegate>
{
    BLMainViewController *m_mainViewController;
    UIButton *m_undoButton;
    NSUndoManager *m_undoManager;
    BLAlbum *m_album;
}

- (void)setAlbum:(id)fp8;
- (id)album;
- (void)dealloc;
- (void)viewDidUnload;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (BOOL)shouldBecomeFirstResponder;
- (BOOL)canBecomeFirstResponder;
- (void)setUndoManager:(id)fp8;
- (void)viewDidLoad;
- (void)keyboardWillHide:(id)fp8;
- (void)keyboardWillShow:(id)fp8;
- (void)undoCheckpoint;
- (void)setupUndoSheetForButton:(id)fp8;
- (void)a_redo:(id)fp8;
- (void)a_undo:(id)fp8;
- (void)undoLongPress:(id)fp8;
- (void)showUndoActionSheetFromView:(id)fp8;
- (void)willPresentActionSheet:(id)fp8;
- (id)redoButtonTitle;
- (id)undoButtonTitle;
- (void)actionSheet:(id)fp8 willDismissWithButtonIndex:(int)fp12;
- (void)actionSheet:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)performRedo;
- (void)performUndo;
- (id)undoManager;
- (void)a_done:(id)fp8;

@end

