/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol BLEditableCommentCellDelegate <NSObject>
- (void)commentingEnded:(id)fp8 result:(int)fp12;
- (void)commentingBegan:(id)fp8;
@end

