/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "UITextViewDelegate-Protocol.h"

@class NSString, UITextView;

@interface BLEditableCommentCell : _ACAccountTypeIdentifierTwitter <UITextViewDelegate>
{
    UITextView *m_textView;
    id <BLEditableCommentCellDelegate> m_delegate;
    NSString *m_placeholder;
    BOOL m_usingPlaceholder;
    BOOL m_commentingEndedCalled;
}

- (id)placeholderText;
- (void)textViewDidChange:(id)fp8;
- (void)textViewDidBeginEditing:(id)fp8;
- (void)textViewDidEndEditing:(id)fp8;
- (void)setCommentCellDelegate:(id)fp8;
- (void)setPlaceholderText:(id)fp8;
- (id)commentText;
- (void)setCommentText:(id)fp8;
- (void)cancel:(id)fp8;
- (void)post:(id)fp8;
- (void)removePlaceholderIfNeeded;
- (void)applyPlaceholderIfNeeded;
- (void)dealloc;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;

@end

