/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface BLEffectManager : _ACAccountTypeIdentifierTwitter
{
}

+ (id)effectManager;
+ (void)invertContext:(struct CGContext *)fp8;
+ (void)fillContext:(struct CGContext *)fp8 withColor:(id)fp12;
+ (struct CGContext *)newContextFromContext:(struct CGContext *)fp8;
+ (struct CGContext *)newContext:(struct CGContext *)fp8 withBlur:(float)fp12;
+ (struct CGContext *)newContext:(struct CGContext *)fp8 withExposure:(float)fp12;
+ (struct CGContext *)newContext:(struct CGContext *)fp8 withSaturation:(float)fp12;
+ (struct CGContext *)newContext:(struct CGContext *)fp8 lineOperation:(id)fp(null);
+ (struct CGContext *)newContext:(struct CGContext *)fp8 pixelOperation:(id)fp(null);
+ (void)performLineBlock:(id)fp(null) onContext:(void)fp8;
+ (void)performBlock:(id)fp(null) onContext:(void)fp8;
+ (void)performLineBlock:(id)fp(null) fromContext:(void)fp8 toContext:(struct CGContext *)fp12;
+ (void)performBlock:(id)fp(null) fromContext:(void)fp8 toContext:(struct CGContext *)fp12;
+ (void)hBlurFrom:(struct CGContext *)fp8 to:(struct CGContext *)fp12 withRadius:(int)fp16;
+ (void)vBlurFrom:(struct CGContext *)fp8 to:(struct CGContext *)fp12 withRadius:(int)fp16;
+ (struct CGImage *)newBrushImageRefWithSize:(float)fp8 softness:(float)fp12 brightness:(float)fp16;
+ (struct CGContext *)newGrayscaleContextWithSize:(struct CGSize)fp8 clear:(BOOL)fp16;
+ (struct CGContext *)newContextWithSize:(struct CGSize)fp8 clear:(BOOL)fp16;

@end

