/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface BLEffectOverlayView : _ACAccountTypeIdentifierTwitter
{
    id <BLEffectOverlayViewDelegate> m_delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setFrame:(struct CGRect)fp8;
- (void)setBounds:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

