/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSString, UILabel;

@interface BLEffectSegmentedControl : _ACAccountTypeIdentifierTwitter
{
    UILabel *m_keyString;
    NSString *m_key;
    id m_objectToObserve;
    BOOL m_takingValue;
}

- (void)setObjectToObserve:(id)fp8;
- (void)setKey:(id)fp8;
- (void)setM_keyString:(id)fp8;
- (id)m_keyString;
- (void)dealloc;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)updateValue;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)willMoveToWindow:(id)fp8;
- (void)takeValue;
- (void)sendAction:(SEL)fp8 to:(id)fp12 forEvent:(id)fp16;
- (id)objectToObserve;
- (id)key;

@end

