/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLAlbumListViewController.h"

#import "UIScrollViewDelegate-Protocol.h"

@interface BLEventListViewController : BLAlbumListViewController <UIScrollViewDelegate>
{
}

+ (id)viewController;
- (void)dealloc;
- (id)initWithController:(id)fp8;
- (id)emptyImageKey;
- (id)emptyLabel;
- (id)helpTag;
- (void)setupObjects;
- (id)objectsToDisplay;
- (Class)itemViewClass;
- (Class)cellClass;
- (id)tabNibName;

@end

