/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLLevelEffectController.h"

#import "UIPopoverControllerDelegate-Protocol.h"

@class BLExposureView, UIBarButtonItem, UIButton;

@interface BLExposureController : BLLevelEffectController <UIPopoverControllerDelegate>
{
    BLExposureView *m_exposureView;
    UIButton *m_pasteButton;
    UIButton *m_resetButton;
    UIBarButtonItem *m_resetBarButton;
    BOOL m_hasSourceImageLoadedObserver;
    BOOL m_hasFullResolutionSourceImageLoadedObserver;
    BOOL m_loadingFullResolutionSource;
    BOOL m_inFullResReloadLoop;
}

+ (id)adjustmentKeys;
- (void)setResetBarButton:(id)fp8;
- (id)resetBarButton;
- (void)setResetButton:(id)fp8;
- (id)resetButton;
- (void)setPasteButton:(id)fp8;
- (id)pasteButton;
- (void)setExposureView:(id)fp8;
- (id)exposureView;
- (id)undoActionForTool;
- (void)updateMainView;
- (void)dealloc;
- (void)finish;
- (void)setup;
- (void)viewerFrameChanged;
- (void)fullResolutionSourceImageLoaded;
- (void)sourceImageLoaded;
- (void)generateHistogram;
- (void)a_reset:(id)fp8;
- (id)histogram;
- (void)setHistogram:(id)fp8;
- (int)toolType;
- (void)showSettingsPopover:(id)fp8;
- (void)a_done:(id)fp8;
- (void)adjustPopovers;
- (void)popoverControllerDidDismissPopover:(id)fp8;
- (void)setSettingsController:(id)fp8;
- (id)settingsController;
- (id)pasteUndoName;
- (id)pasteboardKey;

@end

