/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "FBRequestDelegate-Protocol.h"

@class FBRequest;

@interface BLFacebookAccessProxyObject : _ACAccountTypeIdentifierTwitter <FBRequestDelegate>
{
    id m_progressBlock;
    id m_completionBlock;
    id m_cancelBlock;
    FBRequest *m_request;
}

+ (id)proxyWithProgressBlock:(id)fp(null) completionBlock:(void)fp8;
+ (id)proxyWithProgressBlock:(id)fp(null) completionBlock:(void)fp8 andCancelBlock:(id)fp(null);
- (void)setRequest:(id)fp8;
- (id)request;
- (void)requestWasCancelled:(id)fp8;
- (void)request:(id)fp8 didFailWithError:(id)fp12;
- (void)request:(id)fp8 didLoad:(id)fp12;
- (void)request:(id)fp8 wroteBytes:(id)fp12 totalBytesWritten:(id)fp16 totalBytesExpectedToWrite:(id)fp20;
- (void)requestLoading:(id)fp8;
- (id)cancelBlock;
- (void)setCancelBlock:(id)fp(null);
- (id)progressBlock;
- (void)setProgressBlock:(id)fp(null);
- (id)completionBlock;
- (void)setCompletionBlock:(id)fp(null);
- (void)dealloc;

@end

