/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLSharingServiceViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSArray, NSDictionary, NSIndexPath, NSString, UILabel, UITableView;

@interface BLFlickrSharingViewController : BLSharingServiceViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate>
{
    NSArray *m_photosToShare;
    UITableView *m_shareSettingsTableView;
    UILabel *m_usernameLabel;
    int m_privacyLevel;
    NSDictionary *m_uploadLocation;
    BOOL m_wantsNewSet;
    BOOL m_searchable;
    BOOL m_addTags;
    BOOL m_uploadCancelled;
    NSString *m_loggedInUsername;
    NSIndexPath *m_scrollToIndexPath;
}

- (id)loggedInUsername;
- (void)setUploadCancelled:(BOOL)fp8;
- (BOOL)uploadCancelled;
- (BOOL)wantsNewSet;
- (BOOL)textField:(id)fp8 shouldChangeCharactersInRange:(struct _NSRange)fp12 replacementString:(id)fp20;
- (void)textFieldDidEndEditing:(id)fp8;
- (void)textFieldDidBeginEditing:(id)fp8;
- (void)keyboardWillHide:(id)fp8;
- (void)keyboardDidShow:(id)fp8;
- (void)updateScrollViewOffsetsForKeyboard:(struct CGSize)fp8;
- (float)tableView:(id)fp8 heightForFooterInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 titleForFooterInSection:(int)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didDeselectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 willSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)switchChanged:(id)fp8;
- (void)a_share:(id)fp8;
- (void)sharePhotos:(BOOL)fp8 setName:(id)fp12 tags:(id)fp16;
- (void)setWantsNewSet:(BOOL)fp8;
- (int)privacyLevel;
- (void)setPrivacyLevel:(int)fp8;
- (id)sharingLocation;
- (void)setSharingLocation:(id)fp8;
- (void)setPhotosToShare:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)setLoggedInUsername:(id)fp8;
- (void)viewDidUnload;
- (void)logout:(id)fp8;
- (void)loginInfoChanged:(id)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)loadView;
- (struct CGSize)requiredPopoverSize;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

