/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class BLURLConnection, NSDictionary, NSMutableArray, NSMutableDictionary;

@interface BLFlickrAccess : _ACAccountTypeIdentifierTwitter
{
    BOOL m_hasCachedLoginState;
    int m_cachedLoginState;
    BOOL m_hasCachedUploadStatus;
    NSDictionary *m_cachedUploadStatus;
    NSMutableDictionary *m_cachedComments;
    NSMutableDictionary *m_cachedUserInfo;
    NSMutableArray *m_pendingUploads;
    BOOL m_uploadInProgress;
    BOOL m_cancelNextUpload;
    BOOL m_uploadAlmostComplete;
    BLURLConnection *m_uploadConnection;
}

+ (id)sharedInstance;
- (void)setUploadAlmostComplete:(BOOL)fp8;
- (BOOL)uploadAlmostComplete;
- (void)setCancelNextUpload:(BOOL)fp8;
- (BOOL)cancelNextUpload;
- (void)setUploadConnection:(id)fp8;
- (id)uploadConnection;
- (void)setUploadInProgress:(BOOL)fp8;
- (BOOL)uploadInProgress;
- (void)setCachedUploadStatus:(id)fp8;
- (id)cachedUploadStatus;
- (void)setHasCachedUploadStatus:(BOOL)fp8;
- (BOOL)hasCachedUploadStatus;
- (void)setCachedLoginState:(int)fp8;
- (int)cachedLoginState;
- (void)setHasCachedLoginState:(BOOL)fp8;
- (BOOL)hasCachedLoginState;
- (void)testGetPhotos;
- (void)cancelQueue;
- (void)signalQueue;
- (void)processFlickrError:(id)fp8 forPhoto:(id)fp12;
- (id)dateFromFlickrTime:(double)fp8;
- (id)JSONFromFlickrData:(id)fp8;
- (id)signedParameterStringWithParameters:(id)fp8;
- (id)signatureStringWithParameters:(id)fp8;
- (id)parameterStringWithParameters:(id)fp8 forSigning:(BOOL)fp12;
- (void)reachabilityChanged:(id)fp8;
- (id)callPOSTMethod:(id)fp8 withParameters:(id)fp12 response:(id *)fp16 andError:(id *)fp20;
- (id)callGETMethod:(id)fp8 withParameters:(id)fp12 response:(id *)fp16 andError:(id *)fp20;
- (void)callPOSTMethod:(id)fp8 withParameters:(id)fp12 andCompletionBlock:(id)fp(null);
- (void)callGETMethod:(id)fp8 withParameters:(id)fp12 andCompletionBlock:(id)fp(null);
- (void)uploadPhoto:(id)fp8 parameters:(id)fp12 progressBlock:(id)fp(null) completionBlock:(void)fp16;
- (double)currentFlickrTime;
- (id)flickrURLForPhotos:(id)fp8;
- (void)cancelUploads;
- (void)enqueuePhotoUpload:(id)fp8 parameters:(id)fp12 progressBlock:(id)fp(null) completionBlock:(void)fp16;
- (void)addMetadataForPhoto:(id)fp8 title:(id)fp12 description:(id)fp16 withCompletionBlock:(id)fp(null);
- (void)setHidden:(BOOL)fp8 forPhoto:(id)fp12 withCompletionBlock:(id)fp(null);
- (void)setPermissionsForPhoto:(id)fp8 permissions:(id)fp12 withCompletionBlock:(id)fp(null);
- (void)setTags:(id)fp8 toPhoto:(id)fp12 withCompletionBlock:(id)fp(null);
- (void)addSetWithTitle:(id)fp8 withPrimaryPhoto:(id)fp12 andCompletionBlock:(id)fp(null);
- (void)addPhoto:(id)fp8 toSetWithSetId:(id)fp12 withCompletionBlock:(id)fp(null);
- (void)requestPhotoSetsWithCompletionBlock:(id)fp(null);
- (void)refreshCommentsForPhoto:(id)fp8 withCompletionBlock:(id)fp(null);
- (void)addComment:(id)fp8 toPhoto:(id)fp12 withCompletionBlock:(id)fp(null);
- (void)commentsForPhoto:(id)fp8 completionBlock:(id)fp(null);
- (void)recentCommentCountForPhoto:(id)fp8 completionBlock:(id)fp(null);
- (void)photoInfoForPhoto:(id)fp8 completionBlock:(id)fp(null);
- (void)userInfoForCurrentUserWithCompletionBlock:(id)fp(null);
- (void)fetchUploadLimitsWithCompletionBlock:(id)fp(null);
- (void)checkLoggedInWithCompletionBlock:(id)fp(null);
- (void)logout;
- (void)authenticateWithViewController:(id)fp8 andCompletionBlock:(id)fp(null);
- (BOOL)hasStoredLoginInformation;
- (id)currentUserId;
- (id)consumerKey;
- (id)accessToken;
- (id)signedURLWithEndpoint:(id)fp8 andParameters:(id)fp12;
- (void)flushCachedData;
- (void)checkServiceReachableWithCompletionBlock:(id)fp(null);
- (void)dealloc;
- (id)init;

@end

