/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLSharingServiceViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class BLFlickrSharingViewController, NSArray, UITableView;

@interface BLFlickrSharingSetSelectionViewController : BLSharingServiceViewController <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *m_setTableView;
    BLFlickrSharingViewController *m_sharingController;
    NSArray *m_setList;
    BOOL m_loadingSets;
}

- (void)setLoadingSets:(BOOL)fp8;
- (BOOL)loadingSets;
- (void)setSharingController:(id)fp8;
- (id)sharingController;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didDeselectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)loadView;
- (struct CGSize)requiredPopoverSize;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

