/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLGridTableCellAccessibility.h"

@interface BLGridTableCellAccessibility (SafeCategory)
- (id)accessibilityLabel;
- (void)dealloc;
- (id)_accessibilityOverrideChildren;
- (id)accessibilityContainerElements;
- (void)setNumberOfColumns:(int)fp8;
- (BOOL)isAccessibilityElement;
@end

