/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSArray, UIView;

@interface BLHelpManager : _ACAccountTypeIdentifierTwitter
{
    UIView *m_helpContainer;
    NSArray *m_placeholders;
}

- (void)setPlaceholders:(id)fp8;
- (void)setHelpContainer:(id)fp8;
- (id)helpContainer;
- (void)dealloc;
- (void)didMoveToWindow;
- (id)placeholders;

@end

