/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIView;

@interface BLHelpViewController : _ACAccountTypeIdentifierTwitter
{
    UIView *m_baseView;
}

- (void)setBaseView:(id)fp8;
- (id)baseView;
- (void)dealloc;
- (void)viewWillAppear:(BOOL)fp8;
- (id)initWithNibName:(id)fp8 overView:(id)fp12;

@end

