/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIView;

@interface BLHelpPlaceholder : _ACAccountTypeIdentifierTwitter
{
    UIView *m_viewToAttachTo;
    UIView *m_viewToTrack;
}

- (void)setViewToTrack:(id)fp8;
- (id)viewToTrack;
- (void)setViewToAttachTo:(id)fp8;
- (id)viewToAttachTo;
- (id)copyWithZone:(struct _NSZone *)fp8;

@end

