/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface BLHistogramAnalysis : _ACAccountTypeIdentifierTwitter
{
    float m_blackPoint;
    float m_whitePoint;
    float m_blackPointRed;
    float m_whitePointRed;
    float m_blackPointGreen;
    float m_whitePointGreen;
    float m_blackPointBlue;
    float m_whitePointBlue;
}

- (void)setWhitePointBlue:(float)fp8;
- (float)whitePointBlue;
- (void)setBlackPointBlue:(float)fp8;
- (float)blackPointBlue;
- (void)setWhitePointGreen:(float)fp8;
- (float)whitePointGreen;
- (void)setBlackPointGreen:(float)fp8;
- (float)blackPointGreen;
- (void)setWhitePointRed:(float)fp8;
- (float)whitePointRed;
- (void)setBlackPointRed:(float)fp8;
- (float)blackPointRed;
- (void)setWhitePoint:(float)fp8;
- (float)whitePoint;
- (void)setBlackPoint:(float)fp8;
- (float)blackPoint;
- (id)analysisDictionary;
- (id)description;
- (void)dealloc;
- (id)initWithAnalysisDictionary:(id)fp8;
- (id)initWithBLImage:(id)fp8;

@end

