/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface BLHorizonDetection : _ACAccountTypeIdentifierTwitter
{
    char *m_grayScale;
    char *m_rgb;
    char *m_orgEdge;
    char *m_processedEdge;
    char *m_bwLabelSceneMap;
    int m_rows;
    int m_cols;
    int m_isHor;
    int m_numLines;
    float m_scaleFactor;
    CDAnonymousStruct13 *m_detectedLinePointer;
    CDAnonymousStruct11 *m_detectedHorPointerH;
    float *m_edgeAngle;
}

+ (void)findHorizonForImage:(id)fp8 horizonLineH:(CDAnonymousStruct11 *)fp12;
- (void)edgeOrientationAnalysisFindModes:(char *)fp8;
- (void)preProcessEdgeAnglePDF;
- (void)preProcessEdgeCC;
- (void)preProcessEdgeCheckNB;
- (void)imageStatisticalAnalysis:(unsigned int *)fp8 numCC:(int)fp12;
- (void)sceneClassification;
- (void)lineOverlapHorBW:(CDAnonymousStruct13 *)fp8 numLines:(int)fp12;
- (void)horizonDetection;
- (void)applyLineFilters;
- (void)findHorizon:(id)fp8 horizonLineH:(CDAnonymousStruct11 *)fp12;
- (void)extractGrayRGBData:(id)fp8;

@end

