/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSMutableArray;

@interface BLImageManager : _ACAccountTypeIdentifierTwitter
{
    NSMutableArray *m_requestQueueLow;
    NSMutableArray *m_itemsInProcessLow;
    NSMutableArray *m_requestQueueNormal;
    NSMutableArray *m_itemsInProcessNormal;
    NSMutableArray *m_requestQueueHigh;
    NSMutableArray *m_itemsInProcessHigh;
}

+ (id)sharedImageManager;
- (void)setItemsInProcessHigh:(id)fp8;
- (id)itemsInProcessHigh;
- (void)setRequestQueueHigh:(id)fp8;
- (id)requestQueueHigh;
- (void)setItemsInProcessNormal:(id)fp8;
- (id)itemsInProcessNormal;
- (void)setRequestQueueNormal:(id)fp8;
- (id)requestQueueNormal;
- (void)setItemsInProcessLow:(id)fp8;
- (id)itemsInProcessLow;
- (void)setRequestQueueLow:(id)fp8;
- (id)requestQueueLow;
- (void)dealloc;
- (void)cancelImageRequest:(unsigned int)fp8;
- (BOOL)cancelImageRequest:(unsigned int)fp8 inRequests:(id)fp12 inProcess:(id)fp16;
- (unsigned int)requestImageForPhoto:(id)fp8 size:(struct CGSize)fp12 scale:(float)fp20 offset:(struct CGPoint)fp24 priority:(int)fp32 completion:(id)fp(null);
- (unsigned int)requestImageForPhoto:(id)fp8 size:(struct CGSize)fp12 priority:(int)fp20 completion:(id)fp(null);
- (unsigned int)requestImageForPhoto:(id)fp8 type:(int)fp12 maxEdgeLength:(int)fp16 priority:(int)fp20 completion:(id)fp(null);
- (unsigned int)requestImageForPhoto:(id)fp8 maxEdgeLength:(int)fp12 priority:(int)fp16 completion:(id)fp(null);
- (unsigned int)requestImageForPhoto:(id)fp8 minEdgeLength:(int)fp12 priority:(int)fp16 completion:(id)fp(null);
- (unsigned int)requestImageForPhoto:(id)fp8 type:(int)fp12 size:(struct CGSize)fp16 priority:(int)fp24 completion:(id)fp(null);
- (unsigned int)requestImageForPhoto:(id)fp8 type:(int)fp12 priority:(int)fp16 completion:(id)fp(null);
- (unsigned int)requestPromiseImageForPhoto:(id)fp8 priority:(int)fp12 completion:(id)fp(null);
- (unsigned int)requestPromiseImageForPhoto:(id)fp8 priority:(int)fp12 options:(int)fp16 completion:(id)fp(null);
- (unsigned int)addRequest:(id)fp8;
- (void)processQueue;
- (BOOL)processRequests:(id)fp8 inProcess:(id)fp12;
- (void)processRequest:(id)fp8;
- (void)startRequest:(id)fp8;
- (void)finishRequest:(id)fp8 image:(id)fp12 isPlaceholder:(BOOL)fp16;
- (id)lookupImageRequestID:(unsigned int)fp8 inArray:(id)fp12;
- (void)queuesForRequest:(id)fp8 inProcess:(id *)fp12 requests:(id *)fp16;
- (id)init;
- (void)unlock;
- (void)lock;

@end

