/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class CIImage, UIImage;

@interface BLImage : _ACAccountTypeIdentifierTwitter
{
    UIImage *m_UIImage;
    struct CGImage *m_CGImage;
    CIImage *m_CIImage;
    int m_originalType;
    struct CGSize m_size;
}

- (id)CIImage;
- (int)imageOrientation;
- (float)scale;
- (struct CGImage *)CGImage;
- (id)UIImage;
- (struct CGSize)size;
- (void)dealloc;
- (id)initWithFileAtURL:(id)fp8;
- (id)init;

@end

