/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLEditor.h"

@class BLHelpController, BLJournalController, NSString, UIButton, UIImageView, UIView;

@interface BLJournalEditor : BLEditor
{
    BLJournalController *m_journalController;
    UIView *m_headerView;
    UIButton *m_backButton;
    UIButton *m_previousPageButton;
    UIButton *m_pageListButton;
    UIButton *m_nextPageButton;
    UIButton *m_helpButton;
    UIButton *m_addButton;
    UIButton *m_gearButton;
    UIButton *m_shareButton;
    UIButton *m_editButton;
    NSString *m_titleText;
    UIView *m_middleSubHeaderView;
    UIView *m_topSubView;
    UIView *m_bottomSubView;
    UIImageView *m_topShadowView;
    BLHelpController *m_helpController;
    BOOL m_ignoreEditMode;
    BOOL m_hasChanges;
}

- (void)setJournalController:(id)fp8;
- (id)journalController;
- (void)finishBeforeTransitionWithCompletionBlock:(id)fp(null);
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)updateIPhoneHeaderRotation:(int)fp8;
- (void)updateIPhoneHeaderForPortrait;
- (void)updateIPhoneHeaderForLandscape;
- (void)updatePageControls;
- (void)updateEditorStyle;
- (void)updateIPadEditorStyle;
- (id)journalImageNamed:(id)fp8 dark:(BOOL)fp12 stretch:(BOOL)fp16 state:(id)fp20;
- (id)journalImageNamed:(id)fp8 dark:(BOOL)fp12 stretch:(BOOL)fp16 state:(id)fp20 orientation:(id)fp24;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)forceRotationUpdate;
- (void)updateIPhoneHeaderEditMode;
- (BOOL)editMode;
- (void)viewDidUnload;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)willResignActive:(id)fp8;
- (BOOL)hasChanges;
- (id)headerView;
- (void)albumChanged;
- (void)a_editPhotos:(id)fp8;
- (id)name;
- (void)setAlbum:(id)fp8;
- (void)a_done:(id)fp8;

@end

