/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSString;

@interface BLJournalTheme : _ACAccountTypeIdentifierTwitter
{
    NSString *m_name;
    int m_backgroundStyle;
    int m_layoutStyle;
    int m_frameStyle;
    float m_gridCellSize;
    float m_gridDividerSize;
    float m_gridMarginSize;
    float m_gridCellSize_iphone;
    float m_gridDividerSize_iphone;
    float m_gridMarginSize_iphone;
}

+ (id)themeNamed:(id)fp8;
+ (id)themes;
- (int)frameStyle;
- (int)layoutStyle;
- (int)backgroundStyle;
- (id)name;
- (BOOL)hasGaps;
- (BOOL)hasDarkBackground;
- (struct CGSize)frameSizeForSizeInGrid:(struct CGSize)fp8;
- (id)previewImage;
- (id)displayName;
- (int)differenceWithTheme:(id)fp8;
- (void)dealloc;
- (float)gridMarginSize;
- (float)gridDividerSize;
- (float)gridCellSize;
- (id)initWithName:(id)fp8 bkgdStyle:(int)fp12 layoutStyle:(int)fp16 frameStyle:(int)fp20;

@end

