/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLJournalElementView.h"

#import "BLTextViewDelegate-Protocol.h"
#import "BLViewAnimatorDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class BLJournalController, BLTextView, NSDictionary, UIImageView, UINavigationBar;

@interface BLJournalTextView : BLJournalElementView <UITextViewDelegate, BLTextViewDelegate, BLViewAnimatorDelegate>
{
    BLTextView *m_textView;
    UIImageView *m_imageView1;
    UIImageView *m_imageView2;
    NSDictionary *m_initialState;
    BOOL m_resizing;
    UINavigationBar *m_textNavBar;
    BLJournalController *m_controller;
    struct CGPoint m_originalScrollOffset;
    struct CGSize m_originalScrollSize;
    struct CGSize m_originalScrollContentSize;
    struct CGRect m_lastCaretRect;
    struct CGPoint m_originalTextViewCenter;
    struct CGRect m_usableBounds;
    BOOL m_zoomedIn;
    float m_scaleFactor;
    struct CGRect m_zoomedTextViewBounds;
    BOOL m_useCaretHeight;
}

+ (float)inlineHeightForWidth:(float)fp8 element:(id)fp12;
+ (struct __CTFont *)fontForTextType:(int)fp8;
- (void)textViewTextChanged:(id)fp8;
- (void)textViewEndedEditing:(id)fp8;
- (void)textViewBeganEditing:(id)fp8;
- (void)textViewDidResize:(id)fp8;
- (id)textViewMagnifierBackgroundColorForTextView:(id)fp8;
- (BOOL)canAnimateFrame;
- (void)menuInGrid:(id)fp8;
- (void)menuInline:(id)fp8;
- (BOOL)canPerformAction:(SEL)fp8 withSender:(id)fp12;
- (id)menuItems;
- (void)setEditMode:(BOOL)fp8;
- (void)journalStyleChanged:(int)fp8;
- (struct CGRect)dragImageFinalFrame;
- (void)sizeChanged;
- (void)elementContentChanged;
- (BOOL)isTextElementView;
- (BOOL)shouldDisableGestureRecognizer:(id)fp8;
- (void)endEditing;
- (void)removeViewController:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)beginEditing;
- (id)textElement;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 element:(id)fp24;
- (void)updateSubviews;
- (void)updateTextVisible;
- (void)updateLayoutForEditing:(BOOL)fp8 animate:(BOOL)fp12;
- (void)updateColors;
- (id)headerTitleForTextType:(int)fp8;

@end

