/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLSharingServiceViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class BLJournalController, NSTimer, UIActivityIndicatorView, UIButton, UILabel, UIPopoverController, UITableView, UIView;

@interface BLJournaliCloudPublishViewController : BLSharingServiceViewController <UITableViewDataSource, UITableViewDelegate>
{
    UITableView *m_tableView;
    UIView *m_buttonContainerView;
    UIView *m_shelfButtonContainerView;
    UIView *m_bottomProgressContainer;
    UILabel *m_progressLabel;
    UIButton *m_emailButton;
    UIButton *m_safariButton;
    UIButton *m_shelfSafariButton;
    UIButton *m_shelfEmailButton;
    BOOL m_hasInternet;
    BOOL m_hasiCloud;
    BOOL m_hasPublishStatus;
    NSTimer *m_timer;
    BOOL m_isChecking;
    UIActivityIndicatorView *m_activityIndicator;
    BLJournalController *journalController;
    UIPopoverController *popoverDelegate;
}

- (void)setPopoverDelegate:(id)fp8;
- (id)popoverDelegate;
- (void)setJournalController:(id)fp8;
- (id)journalController;
- (id)tableView:(id)fp8 viewForFooterInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForFooterInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)switchChanged:(id)fp8;
- (void)publish:(id)fp8;
- (void)a_shelfSafari:(id)fp8;
- (void)a_shelfEmail:(id)fp8;
- (void)a_safari:(id)fp8;
- (void)a_email:(id)fp8;
- (void)email:(BOOL)fp8;
- (void)safari:(BOOL)fp8;
- (void)check:(id)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)loadView;
- (struct CGSize)requiredPopoverSize;
- (void)reachabilityChanged:(id)fp8;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

