/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "BLJournalThemePickerViewDelegate-Protocol.h"

@class BLJournalThemePickerView, UIButton, UIPopoverController;

@interface BLJournalThemeSettingsViewController : _ACAccountTypeIdentifierTwitter <BLJournalThemePickerViewDelegate>
{
    UIPopoverController *m_popoverController;
    BLJournalThemePickerView *m_pickerView;
    UIButton *m_autoLayoutButton;
    UIButton *m_resetLayoutButton;
}

- (void)setPopoverController:(id)fp8;
- (id)popoverController;
- (void)resetLayout:(id)fp8;
- (void)autoLayout:(id)fp8;
- (void)done:(id)fp8;
- (void)didSelectThemeName:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)loadView;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (void)dealloc;

@end

