/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "UIScrollViewDelegate-Protocol.h"

@class NSArray, UIImageView, UILabel, UIPageControl, UIScrollView;

@interface BLJournalThemePickerView : _ACAccountTypeIdentifierTwitter <UIScrollViewDelegate>
{
    NSArray *m_themes;
    unsigned int m_index;
    UIImageView *m_iPhoneBackgroundTopView;
    UIImageView *m_iPhoneBackgroundBottomView;
    UIScrollView *m_scrollView;
    UIPageControl *m_pageControl;
    UILabel *m_nameLabel;
    id <BLJournalThemePickerViewDelegate> m_delegate;
}

- (void)scrollViewDidEndDecelerating:(id)fp8;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)scrollViewWillEndDragging:(id)fp8 withVelocity:(struct CGPoint)fp12 targetContentOffset:(inout struct CGPoint *)fp20;
- (void)scrollViewOffsetChanged;
- (void)a_pageValueChanged:(id)fp8;
- (void)setSelectedThemeName:(id)fp8;
- (id)selectedThemeName;
- (void)setDelegate:(id)fp8;
- (void)dealloc;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)init;
- (void)setupSubviews;
- (void)selectedThemeChanged;
- (void)updatePageControl;
- (void)updateThemeName;
- (void)scrollToThemeIndex:(unsigned int)fp8 animated:(BOOL)fp12;
- (unsigned int)scrolledThemeIndex;
- (unsigned int)getThemeIndexForX:(float)fp8;
- (float)getOffsetForThemeIndex:(unsigned int)fp8;

@end

