/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLSharingServiceViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class UIActivityIndicatorView, UIButton, UIImageView, UIView, UIWindow;

@interface BLJournalAddItemsViewController : BLSharingServiceViewController <UIGestureRecognizerDelegate>
{
    UIView *m_viewPopoverDisplayedFrom;
    UIActivityIndicatorView *m_activityIndicator;
    UIWindow *m_window;
    UIImageView *m_dragImageView;
    struct CGRect m_dragSourceRect;
    int m_dragButtonTag;
    BOOL m_dragInProgress;
    UIButton *m_headerButton;
    UIButton *m_pageButton;
    UIButton *m_textButton;
    UIButton *m_foodButton;
    UIButton *m_memoryButton;
    UIButton *m_quoteButton;
    UIButton *m_ticketButton;
    UIButton *m_flagButton;
    UIButton *m_currencyButton;
    UIButton *m_weatherButton;
    UIButton *m_noteButton;
    UIButton *m_photoButton;
    UIButton *m_calendarButton;
    UIButton *m_mapButton;
    UIButton *m_spaceButton;
}

- (void)setSpaceButton:(id)fp8;
- (id)spaceButton;
- (void)setMapButton:(id)fp8;
- (id)mapButton;
- (void)setCalendarButton:(id)fp8;
- (id)calendarButton;
- (void)setPhotoButton:(id)fp8;
- (id)photoButton;
- (void)setNoteButton:(id)fp8;
- (id)noteButton;
- (void)setWeatherButton:(id)fp8;
- (id)weatherButton;
- (void)setCurrencyButton:(id)fp8;
- (id)currencyButton;
- (void)setFlagButton:(id)fp8;
- (id)flagButton;
- (void)setTicketButton:(id)fp8;
- (id)ticketButton;
- (void)setQuoteButton:(id)fp8;
- (id)quoteButton;
- (void)setMemoryButton:(id)fp8;
- (id)memoryButton;
- (void)setFoodButton:(id)fp8;
- (id)foodButton;
- (void)setTextButton:(id)fp8;
- (id)textButton;
- (void)setPageButton:(id)fp8;
- (id)pageButton;
- (void)setHeaderButton:(id)fp8;
- (id)headerButton;
- (void)setViewPopoverDisplayedFrom:(id)fp8;
- (id)viewPopoverDisplayedFrom;
- (void)userLongPressed:(id)fp8;
- (id)popoverParentView;
- (void)a_dismiss:(id)fp8;
- (void)a_touchUpInside:(id)fp8;
- (void)doTouchUpInside:(id)fp8;
- (void)setupWindow;
- (id)buttonAtLocation:(struct CGPoint)fp8;
- (id)dragImageForOperation:(int)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (struct CGSize)calculatedPopoverContentSize;
- (struct CGSize)requiredPopoverSize;
- (void)dealloc;
- (void)releaseUI;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

