/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLJournalCalendarViewAccessibility.h"

@interface BLJournalCalendarViewAccessibility (SafeCategory)
- (id)accessibilityValue;
- (id)accessibilityLabel;
- (BOOL)isAccessibilityElement;
- (void)setDate:(id)fp8;
@end

