/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class BLJournalElement, BLSelectionFrame, UIImageView;

@interface BLJournalElementView : _ACAccountTypeIdentifierTwitter <UIGestureRecognizerDelegate, UIActionSheetDelegate>
{
    BLJournalElement *m_element;
    BOOL m_dragging;
    BOOL m_selected;
    struct CGRect m_targetFrame;
    BLSelectionFrame *m_selectionView;
    UIImageView *m_centerRightHandle;
    UIImageView *m_bottomCenterHandle;
    UIImageView *m_bottomRightHandle;
}

+ (float)inlineHeightForWidth:(float)fp8 element:(id)fp12;
- (BOOL)selected;
- (BOOL)dragging;
- (void)setElement:(id)fp8;
- (id)element;
- (BOOL)canAnimateFrame;
- (void)resumeImageFetching;
- (void)suspendImageFetching;
- (BOOL)addedToJournal;
- (void)mediaChanged:(id)fp8;
- (void)setEditMode:(BOOL)fp8;
- (void)journalStyleChanged:(int)fp8;
- (void)didResize;
- (void)willResize;
- (void)didAdjustScale;
- (void)adjustScale:(float)fp8;
- (void)willAdjustScaleCenteredAt:(struct CGPoint)fp8;
- (void)unload;
- (void)load:(BOOL)fp8;
- (void)endEditing;
- (void)beginEditing;
- (struct CGRect)dragImageFinalFrame;
- (void)setTargetFrame:(struct CGRect)fp8;
- (struct CGRect)targetFrame;
- (void)setFrame:(struct CGRect)fp8;
- (void)moveToTargetFrame;
- (void)sizeChanged;
- (void)elementContentChanged;
- (id)journal;
- (id)page;
- (BOOL)isPhotoElementView;
- (BOOL)isTextElementView;
- (BOOL)shouldDisableGestureRecognizer:(id)fp8;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (void)setSelected:(BOOL)fp8;
- (void)didDeselect;
- (void)didSelect;
- (void)hideMenu;
- (void)showMenu;
- (void)menuDelete:(id)fp8;
- (BOOL)canPerformAction:(SEL)fp8 withSender:(id)fp12;
- (BOOL)canBecomeFirstResponder;
- (id)menuItems;
- (id)deleteButtonName;
- (id)deleteActionName;
- (struct CGSize)selectionFrameOutset;
- (void)setDragging:(BOOL)fp8;
- (BOOL)supportsGestureType:(int)fp8 atLocation:(struct CGPoint)fp12;
- (struct CGRect)contentRect;
- (void)dealloc;
- (id)copyOfElementView;
- (id)overlayView;
- (id)initWithFrame:(struct CGRect)fp8 element:(id)fp24;

@end

