/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLJournalElement.h"

@class CLLocation, NSDictionary;

@interface BLJournalMapElement : BLJournalElement
{
    BOOL m_automatic;
    BOOL m_showPins;
    NSDictionary *m_mapData;
    CLLocation *m_location;
    NSDictionary *m_lastViewData;
}

- (BOOL)showPins;
- (BOOL)automatic;
- (void)dealloc;
- (Class)elementViewClass;
- (struct CGSize)maxSizeInGrid;
- (struct CGSize)minSizeInGrid;
- (BOOL)canResetSize;
- (BOOL)canAutoResizeInGrid:(struct CGSize)fp8;
- (BOOL)isCustomResizable;
- (struct CGSize)sizeInGridForSize:(int)fp8;
- (id)locations;
- (id)mapDataHash;
- (void)setLastViewData:(id)fp8;
- (void)setMapData:(id)fp8;
- (id)lastViewData;
- (id)mapData;
- (void)setShowPins:(BOOL)fp8;
- (void)setAutomatic:(BOOL)fp8;
- (void)updateAutomaticSettings;
- (id)dictionary;
- (id)initWithDictionary:(id)fp8 page:(id)fp12;
- (id)init;

@end

