/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class BLJournalViewerController, BLMedia, BLTiledImageView, BLViewerMovieItemWrapper, UIImageView, UIScrollView, UIView;

@interface BLJournalViewerItem : _ACAccountTypeIdentifierTwitter <UIScrollViewDelegate, UIGestureRecognizerDelegate>
{
    BLJournalViewerController *m_controller;
    BLMedia *m_photo;
    int m_index;
    UIScrollView *m_scrollView;
    UIView *m_contentView;
    UIImageView *m_imageView;
    BLTiledImageView *m_fullImageView;
    BLViewerMovieItemWrapper *m_movieView;
    unsigned int m_imageRequestID;
    unsigned int m_fullImageRequestID;
}

- (void)dealloc;
- (void)unloadFullImage;
- (void)unload;
- (id)enclosingScrollView:(id)fp8;
- (void)didRotate:(BOOL)fp8 scrollViewSize:(struct CGSize)fp12;
- (void)willRotate:(BOOL)fp8;
- (void)loadHighPriority:(BOOL)fp8 visibility:(int)fp12;
- (void)playStop:(id)fp8;
- (BOOL)playPause:(id)fp8;
- (struct CGRect)contentFrameForSize:(struct CGSize)fp8;
- (struct CGRect)frameInScrollView:(struct CGSize)fp8;
- (void)loadFullSize:(BOOL)fp8 highPriority:(BOOL)fp12 visibility:(int)fp16;
- (void)setHidden:(BOOL)fp8;
- (void)makeVisible:(int)fp8;
- (id)photo;
- (id)initWithPhoto:(id)fp8 controller:(id)fp12 index:(int)fp16;

@end

