/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLJournalElementView.h"

#import "UIPopoverControllerDelegate-Protocol.h"

@class BLJournalCountryPickerViewController, UIImageView, UIPopoverController;

@interface BLJournalFlagView : BLJournalElementView <UIPopoverControllerDelegate>
{
    UIImageView *m_imageView;
    UIPopoverController *m_countryPickerPopoverController;
    BLJournalCountryPickerViewController *m_countryPickerViewController;
}

- (void)elementContentChanged;
- (void)endEditing;
- (void)beginEditing;
- (struct CGRect)contentRect;
- (struct CGRect)dragImageFinalFrame;
- (id)flagElement;
- (id)initWithFrame:(struct CGRect)fp8 element:(id)fp24;
- (void)setCountryName:(id)fp8;

@end

