/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLJournalElement.h"

@class BLMedia, NSString;

@interface BLJournalPhotoElement : BLJournalElement
{
    BLMedia *m_photo;
    NSString *m_photoUuid;
    int m_mode;
    CDAnonymousStruct7 m_cropInfo;
    unsigned int m_thumbnailRequestID;
    unsigned int m_imageRequestID;
}

+ (id)photoUuidsWithDictionary:(id)fp8;
- (CDAnonymousStruct7)cropInfo;
- (void)setMode:(int)fp8;
- (int)mode;
- (void)setPhotoUuid:(id)fp8;
- (id)photoUuid;
- (BOOL)canResetSize;
- (BOOL)canAutoResizeInGrid:(struct CGSize)fp8;
- (BOOL)isCustomResizable;
- (BOOL)isResizable;
- (struct CGSize)sizeInGridForSize:(int)fp8;
- (void)removedFromJournal;
- (void)addedToJournal;
- (void)setCaption:(id)fp8 undoMgr:(id)fp12;
- (void)setCropInfo:(CDAnonymousStruct7)fp8 oldCropInfo:(CDAnonymousStruct7)fp20 undoMgr:(id)fp32;
- (void)resetCropInfo;
- (void)setCropInfo:(CDAnonymousStruct7)fp8;
- (void)setTargetRect:(struct CGRect)fp8 forContentRect:(struct CGRect)fp24;
- (struct CGRect)targetRectFromContentRect:(struct CGRect)fp8;
- (struct CGRect)maxContentRectFittingInRect:(struct CGRect)fp8;
- (float)maxScaleForContentRect:(struct CGRect)fp8;
- (Class)elementViewClass;
- (void)setPhoto:(id)fp8;
- (id)photo;
- (BOOL)isFavoriteElement;
- (BOOL)isPhotoElement;
- (void)dealloc;
- (id)dictionary;
- (id)initWithDictionary:(id)fp8 page:(id)fp12;
- (id)init;

@end

