/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLJournalElement.h"

@interface BLJournalWeatherElement : BLJournalElement
{
    BOOL m_automatic;
    int m_condition;
    float m_temperature;
}

- (float)temperature;
- (int)condition;
- (BOOL)automatic;
- (void)setAutomatic:(BOOL)fp8;
- (void)updateAutomaticSettings;
- (void)setCondition:(int)fp8 temperature:(float)fp12;
- (void)setTemperature:(float)fp8;
- (void)setCondition:(int)fp8;
- (Class)elementViewClass;
- (struct CGSize)sizeInGridForSize:(int)fp8;
- (id)dictionary;
- (id)initWithDictionary:(id)fp8 page:(id)fp12;
- (id)init;

@end

