/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class BLJournalPage, NSString;

@interface BLJournalElement : _ACAccountTypeIdentifierTwitter
{
    NSString *m_uuid;
    BLJournalPage *m_page;
    BOOL m_inline;
    int m_size;
    struct CGSize m_customSizeInGrid;
    float m_inlineHeight;
}

+ (id)photoUuidsWithDictionary:(id)fp8;
- (struct CGSize)customSizeInGrid;
- (void)setPage:(id)fp8;
- (id)page;
- (void)setUuid:(id)fp8;
- (id)uuid;
- (id)nearbyPhotoWithLocation:(BOOL)fp8;
- (void)updateAutomaticSettings;
- (id)countryName;
- (void)setCountryName:(id)fp8;
- (struct CGSize)frameSize;
- (struct CGSize)maxSizeInGrid;
- (struct CGSize)minSizeInGrid;
- (BOOL)canResetSize;
- (BOOL)canAutoResizeInGrid:(struct CGSize)fp8;
- (BOOL)isCustomResizable;
- (BOOL)isResizable;
- (void)dealloc;
- (id)photo;
- (void)removedFromJournal;
- (void)addedToJournal;
- (void)notifyElementChanged;
- (float)inlineHeightForWidth:(float)fp8;
- (void)setInlineHeight:(float)fp8;
- (void)setIsInline:(BOOL)fp8 undoMgr:(id)fp12;
- (void)setIsInline:(BOOL)fp8;
- (BOOL)isInline;
- (void)setCustomSizeInGrid:(struct CGSize)fp8 oldSize:(struct CGSize)fp16 undoMgr:(id)fp24;
- (void)setCustomSizeInGrid:(struct CGSize)fp8;
- (void)setCustomSizeInGrid:(struct CGSize)fp8 simplify:(BOOL)fp16 notify:(BOOL)fp20;
- (struct CGSize)sizeInGrid;
- (int)sizeForSizeInGrid:(struct CGSize)fp8;
- (struct CGSize)sizeInGridForSize:(int)fp8;
- (void)setSize:(int)fp8 oldSize:(int)fp12 undoMgr:(id)fp16;
- (void)setSize:(int)fp8;
- (void)setSize:(int)fp8 notify:(BOOL)fp12;
- (int)size;
- (void)setTargetRect:(struct CGRect)fp8 forContentRect:(struct CGRect)fp24;
- (struct CGRect)targetRectFromViewRect:(struct CGRect)fp8;
- (struct CGRect)targetRectFromContentRect:(struct CGRect)fp8;
- (struct CGRect)contentRectFromViewRect:(struct CGRect)fp8;
- (id)newElementView;
- (id)newElementViewWithFrame:(struct CGRect)fp8;
- (Class)elementViewClass;
- (unsigned int)elementIndex;
- (BOOL)isFavoriteElement;
- (BOOL)isTextElement;
- (BOOL)isPhotoElement;
- (id)album;
- (id)journal;
- (id)saveLayout;
- (void)restoreLayout:(id)fp8;
- (id)dictionary;
- (id)initWithDictionary:(id)fp8 page:(id)fp12;
- (id)init;

@end

