/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class BLJournal, NSDate, NSMutableArray, NSString;

@interface BLJournalPage : _ACAccountTypeIdentifierTwitter
{
    NSString *m_uuid;
    BLJournal *m_journal;
    NSString *m_title;
    NSDate *m_startDate;
    NSDate *m_endDate;
    NSMutableArray *m_elements;
}

+ (id)photoUuidsWithDictionary:(id)fp8;
- (void)setElements:(id)fp8;
- (id)elements;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setJournal:(id)fp8;
- (id)journal;
- (void)setUuid:(id)fp8;
- (id)uuid;
- (void)restoreLayout:(id)fp8;
- (id)saveLayout;
- (void)performResetLayout;
- (void)performAutoLayout;
- (int)performAutoLayoutForGridSize:(struct CGSize)fp8 otherGridSize:(struct CGSize)fp16 elements:(id)fp24 startIndex:(unsigned int)fp28;
- (void)addPhoto:(id)fp8;
- (BOOL)containsDate:(id)fp8;
- (void)updateDateRange;
- (void)updateAutomaticSettings;
- (id)layoutDictionary;
- (void)reappropriateElements;
- (void)appropriateElementsFromPage:(id)fp8;
- (id)nextPage;
- (id)previousPage;
- (unsigned int)pageIndex;
- (void)changeTitleTo:(id)fp8;
- (id)displayTitle;
- (void)albumNameChanged;
- (id)photos;
- (struct CGSize)contentSize;
- (void)resizeElement:(id)fp8 by:(float)fp12;
- (void)didMoveElement:(id)fp8 initialState:(id)fp12 undoMgr:(id)fp16;
- (void)moveElement:(id)fp8 toPageIndex:(unsigned int)fp12 elementIndex:(unsigned int)fp16 fromPageIndex:(unsigned int)fp20 elementIndex:(unsigned int)fp24 undoMgr:(id)fp28;
- (void)moveElement:(id)fp8 toIndex:(unsigned int)fp12;
- (id)willMoveElement:(id)fp8;
- (void)notifyPageChanged;
- (void)addPageBreakBeforeElement:(id)fp8;
- (id)performAddOperation:(int)fp8 atIndex:(unsigned int)fp12 undoMgr:(id)fp16;
- (id)actionNameForAddOperation:(int)fp8;
- (id)newJournalElement:(int)fp8;
- (void)removeElement:(id)fp8;
- (void)removeElement:(id)fp8 undoMgr:(id)fp12 actionName:(id)fp16;
- (void)addElement:(id)fp8 atIndex:(unsigned int)fp12 undoMgr:(id)fp16 actionName:(id)fp20;
- (id)removeElementsStartingAtIndex:(unsigned int)fp8;
- (void)addElements:(id)fp8;
- (void)addElement:(id)fp8 atIndex:(unsigned int)fp12;
- (id)album;
- (void)dealloc;
- (id)dictionary;
- (id)initWithDictionary:(id)fp8 journal:(id)fp12;
- (id)initWithJournal:(id)fp8;
- (id)init;

@end

