/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIView;

@interface BLLandscapeSplitView : _ACAccountTypeIdentifierTwitter
{
    UIView *m_viewToCenter;
    BOOL m_leftHandLayout;
}

- (BOOL)leftHandLayout;
- (void)setM_viewToCenter:(id)fp8;
- (id)m_viewToCenter;
- (void)setFrame:(struct CGRect)fp8;
- (void)setLeftHandLayout:(BOOL)fp8;

@end

