/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLEffectController.h"

@class BLLevelEffectLayerView, CIContext, CIImage, NSMutableDictionary, UIImageView;

@interface BLLevelEffectController : BLEffectController
{
    BLLevelEffectLayerView *m_imageView;
    int m_inLiveChangeCount;
    BOOL m_inUndoGroupChange;
    BOOL m_inGroupChange;
    BOOL m_firstEffectChange;
    NSMutableDictionary *m_originalAdjustments;
    BOOL m_aChangeWasMade;
    UIImageView *m_animatingImageView;
    BOOL m_haveStartedRemovalOfAnimatedImageView;
    BOOL m_imageRendering;
    BOOL m_pendingRender;
    BOOL m_pendingRenderQuality;
    BOOL m_pendingRenderWithCrop;
    BOOL m_pendingRenderWithAdjustments;
    id m_pendingRenderCompletionBlock;
    CIContext *m_ciContext;
    CIImage *m_lastRenderedImage;
}

- (void)setLastRenderedImage:(id)fp8;
- (id)lastRenderedImage;
- (void)setCiContext:(id)fp8;
- (id)ciContext;
- (void)setAnimatingImageView:(id)fp8;
- (id)animatingImageView;
- (void)setOriginalAdjustments:(id)fp8;
- (id)originalAdjustments;
- (void)setImageView:(id)fp8;
- (id)imageView;
- (struct CGRect)swapImageFrame;
- (id)swapImage;
- (void)updateImageWithQuality:(BOOL)fp8;
- (id)adjustmentDefaultValues;
- (void)performStartOrEndGroupChangeForAction:(id)fp8 withTool:(int)fp12;
- (void)endGroupChangeForAction:(id)fp8;
- (void)beginGroupChangeForAction:(id)fp8;
- (void)effectDidChange:(id)fp8;
- (void)effectWillChange:(id)fp8;
- (id)valueForKey:(id)fp8;
- (void)performSetValue:(id)fp8 forKey:(id)fp12 forUndo:(BOOL)fp16 withTool:(int)fp20;
- (void)setValue:(id)fp8 forKey:(id)fp12;
- (struct CGSize)updateImageSize;
- (void)updateImage;
- (void)renderImageWithQuality:(BOOL)fp8 withCrop:(BOOL)fp12 withAdjustments:(BOOL)fp16 async:(BOOL)fp20 completion:(id)fp(null);
- (void)updateMainView;
- (void)layoutSubviewsOfView:(id)fp8;
- (void)dealloc;
- (void)finish;
- (void)setup;

@end

