/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class BLLoupeImageView, BLUISound, UIImageView;

@interface BLLoupeView : _ACAccountTypeIdentifierTwitter
{
    BLLoupeImageView *m_imageView;
    BLLoupeImageView *m_lowResImageView;
    UIImageView *m_loupeRingView;
    BOOL m_leftHandLayout;
    BOOL m_positionSet;
    BLUISound *m_tickSound;
    float m_lastTickLevel;
}

- (void)setTickSound:(id)fp8;
- (void)setLeftHandLayout:(BOOL)fp8;
- (BOOL)leftHandLayout;
- (void)setPosition:(struct CGPoint)fp8 inView:(id)fp16;
- (id)tickSound;
- (id)lowResImage;
- (void)setLowResImage:(id)fp8;
- (id)promiseImage;
- (void)setPromiseImage:(id)fp8;
- (float)magnification;
- (void)setMagnification:(float)fp8;
- (void)dealloc;
- (id)initWithLowResImage:(id)fp8 fullImageSize:(struct CGSize)fp12 leftHandLayout:(BOOL)fp20 loupeType:(int)fp24;

@end

