/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class BLLoupeView, NSMutableDictionary, NSTimer, UIImage, UIView;

@interface BLLoupe : _ACAccountTypeIdentifierTwitter
{
    BLLoupeView *m_loupeView;
    int m_loupeType;
    struct CGAffineTransform m_pointTransform;
    UIView *m_viewToMagnify;
    UIImage *m_sampleImage;
    struct CGPoint m_pendingSamplePoint;
    BOOL m_sampling;
    BOOL m_pendingSample;
    int m_touchCount;
    struct CGPoint m_startLocation;
    struct CGPoint m_startCenter;
    double m_startTime;
    NSMutableDictionary *m_valueDictionary;
    BOOL m_panning;
    BOOL m_shouldGoAway;
    NSTimer *m_inertiaTimer;
    struct CGPoint m_inertiaVelocity;
}

- (void)setPointTransform:(struct CGAffineTransform)fp8;
- (struct CGAffineTransform)pointTransform;
- (void)sampleForWhiteBalanceAtPoint:(struct CGPoint)fp8;
- (void)dealloc;
- (id)initWithView:(id)fp8 lowResImage:(id)fp12 highResImage:(id)fp16 photo:(id)fp20 outerView:(id)fp24 leftHandLayout:(BOOL)fp28 loupeType:(int)fp32;
- (id)initWithView:(id)fp8 lowResImage:(id)fp12 photo:(id)fp16 outerView:(id)fp20 leftHandLayout:(BOOL)fp24 loupeType:(int)fp28;
- (void)userRotated:(id)fp8;
- (void)recognizerAction:(id)fp8;
- (void)userTapped:(id)fp8;
- (void)userPanned:(id)fp8;
- (void)timer;
- (void)setLoupeCenter:(struct CGPoint)fp8;
- (struct CGRect)maxRect;
- (void)goAway;
- (void)stopTimer;
- (BOOL)leftHandLayout;
- (void)setLeftHandLayout:(BOOL)fp8;
- (id)valueDictionary;

@end

