/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class BLMainTabController, NSMutableArray, UIImageView;

@interface BLMainTabCell : _ACAccountTypeIdentifierTwitter
{
    BLMainTabController *m_controller;
    int m_numberOfColumns;
    NSMutableArray *m_cellViews;
    int m_rowNumber;
    UIImageView *m_backgroundImage;
    float m_reflectionAlpha;
}

- (int)rowNumber;
- (void)setCellViews:(id)fp8;
- (int)numberOfColumns;
- (void)dealloc;
- (void)viewWillDisappear;
- (void)setFrame:(struct CGRect)fp8;
- (void)animateIn:(BOOL)fp8 fromRight:(BOOL)fp12 delay:(float)fp16;
- (void)acquireViews;
- (BOOL)zoomNewItems;
- (void)setView:(id)fp8 forIndex:(int)fp12;
- (void)setObject:(id)fp8 forIndex:(int)fp12 reloadBlock:(id)fp(null);
- (id)newViewForFrame:(struct CGRect)fp8 index:(int)fp24;
- (struct CGRect)frameForColumn:(int)fp8;
- (void)setRowNumber:(int)fp8;
- (void)setNumberOfColumns:(int)fp8;
- (id)initWithNumberOfColumns:(int)fp8 controller:(id)fp12;
- (void)updateBackgroundImage;
- (id)cellViews;

@end

