/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIActivityIndicatorView, UIImageView, UIView;

@interface BLMainTabItemView : _ACAccountTypeIdentifierTwitter
{
    id m_object;
    int m_index;
    id m_reloadBlock;
    unsigned int m_requestID;
    UIImageView *m_thumbView;
    UIActivityIndicatorView *m_activityIndicator;
    UIView *m_movingToView;
}

- (void)setMovingToView:(id)fp8;
- (id)movingToView;
- (void)setReloadBlock:(id)fp(null);
- (id)reloadBlock;
- (void)setObject:(id)fp8;
- (id)object;
- (void)dealloc;
- (void)viewWillDisappear;
- (void)getThumbnail:(BOOL)fp8;
- (void)setImage:(id)fp8;
- (id)imageCache;
- (id)posterMedia;
- (BOOL)wantHighResThumbnails;
- (int)thumbSize;
- (id)key;
- (void)userTapped;
- (void)showEditor;
- (void)startSpinner;
- (void)stopSpinner;
- (id)initWithFrame:(struct CGRect)fp8 index:(int)fp24;

@end

