/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLMainViewController.h"

@interface BLMainViewController (Backup)
- (void)restoreSandbox;
- (void)backupSandbox;
- (id)preferencesToSave;
- (id)foldersToBackup;
- (id)libraryFolderPath;
- (id)savedPrefsPath;
- (id)sandboxCopyFolderPath:(BOOL)fp8;
- (id)documentsFolderPath;
@end

