/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLMainViewControllerAccessibility.h"

@interface BLMainViewControllerAccessibility (SafeCategory)
- (void)popViewController;
- (void)showViewController:(id)fp8 slide:(BOOL)fp12 hideStatus:(BOOL)fp16 makePrimary:(BOOL)fp20 tabIndex:(int)fp24 albumToSet:(id)fp28;
- (void)showViewController:(id)fp8 fromView:(id)fp12 hideStatus:(BOOL)fp16;
@end

