/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@class BLEffectSettingsViewController, BLExternalDisplayController, BLJournalEditor, BLMainTabController, BLPhotoEditor, BLWebViewController, NSMutableArray, NSMutableDictionary, UIButton, UIImageView, UIPopoverController, UIView, UIViewController;

@interface BLMainViewController : BLViewController <UIGestureRecognizerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, UIPopoverControllerDelegate>
{
    BLPhotoEditor *m_viewControllerPortrait;
    BLPhotoEditor *m_viewControllerLandscape;
    BLJournalEditor *m_journalEditor;
    BLWebViewController *m_webViewController;
    BLMainTabController *m_currentTabController;
    int m_mainTabIndex;
    UIViewController *m_currentViewController;
    UIView *m_tabArea;
    UIView *m_tabBackground;
    UIView *m_topBarBackground;
    UIView *m_topShadow;
    UIImageView *m_backgroundCover;
    UIView *m_leftControls;
    UIView *m_rightControls;
    BOOL m_orientationChangeDisabled;
    BLMainTabController *m_leftTabController;
    BLMainTabController *m_rightTabController;
    BOOL m_ignoreTabChanges;
    int m_initialTabIndex;
    BLMainTabController *m_tabControllers[4];
    NSMutableArray *m_controllerStack;
    BOOL m_switchTabsImmediately;
    UIImageView *m_coverView;
    NSMutableDictionary *m_valueDict;
    BLExternalDisplayController *m_externalDisplayController;
    BLEffectSettingsViewController *m_settingsController;
    UIButton *m_editJournalsButton;
    UIPopoverController *m_settingsPopoverController;
    BLEffectSettingsViewController *m_settingsModalViewController;
    UIView *m_settingsFromView;
    UIButton *m_settingsButton;
    UIView *m_locationAlertView;
}

+ (id)controller;
- (void)setDisableOrientationChange:(BOOL)fp8;
- (BOOL)disableOrientationChange;
- (void)setLocationAlertView:(id)fp8;
- (void)setSettingsFromView:(id)fp8;
- (id)settingsFromView;
- (void)setSettingsModalViewController:(id)fp8;
- (void)setEditJournalsButton:(id)fp8;
- (id)editJournalsButton;
- (void)setSettingsController:(id)fp8;
- (void)setRightTabController:(id)fp8;
- (id)rightTabController;
- (void)setLeftTabController:(id)fp8;
- (id)leftTabController;
- (int)mainTabIndex;
- (void)setCurrentTabController:(id)fp8;
- (id)currentTabController;
- (void)setWebViewController:(id)fp8;
- (void)setCurrentViewController:(id)fp8;
- (id)currentViewController;
- (void)setJournalEditor:(id)fp8;
- (id)journalEditor;
- (void)setViewControllerPortrait:(id)fp8;
- (id)viewControllerPortrait;
- (void)setViewControllerLandscape:(id)fp8;
- (id)viewControllerLandscape;
- (void)dealloc;
- (id)valueDict;
- (void)didReceiveMemoryWarning;
- (BOOL)askToLookupLocations:(id)fp(null);
- (void)updateLocationAlert;
- (id)locationAlertView;
- (void)a_action:(id)fp8;
- (void)a_setEditMode:(id)fp8;
- (void)a_help:(id)fp8;
- (void)delayedHelp;
- (void)a_hidePopovers:(id)fp8;
- (BOOL)removePopovers:(BOOL)fp8;
- (void)a_settings:(id)fp8;
- (void)hideSettingsPopover:(BOOL)fp8;
- (void)adjustSettingsPopover:(id)fp8;
- (void)showSettingsPopover:(id)fp8;
- (void)setSettingsPopoverController:(id)fp8;
- (id)settingsModalViewController;
- (id)settingsPopoverController;
- (void)popoverControllerDidDismissPopover:(id)fp8;
- (BOOL)popoverControllerShouldDismissPopover:(id)fp8;
- (id)settingsController;
- (BOOL)iCloudAvailable;
- (void)viewDidAppear:(BOOL)fp8;
- (void)showInitialTab;
- (void)viewWillAppear:(BOOL)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)viewDidLoad;
- (BOOL)gestureRecognizerShouldBegin:(id)fp8;
- (void)userPannedLeftRight:(id)fp8;
- (void)setVelocityToZero;
- (void)showPhotoEditorForAlbum:(id)fp8 fromView:(id)fp12;
- (void)showPhotoEditorForAlbum:(id)fp8 photo:(id)fp12;
- (void)showPhotoEditorForAlbum:(id)fp8;
- (void)showPhotoEditorForAlbum:(id)fp8 makePrimary:(BOOL)fp12 editMode:(BOOL)fp16;
- (void)setupSelectionForAlbum:(id)fp8;
- (void)showURL:(id)fp8;
- (id)webViewController;
- (void)showJournal:(id)fp8;
- (void)a_editorDone:(id)fp8;
- (void)dismissViewController;
- (void)popViewController;
- (void)showViewController:(id)fp8 slide:(BOOL)fp12 hideStatus:(BOOL)fp16;
- (void)showViewController:(id)fp8 slide:(BOOL)fp12 hideStatus:(BOOL)fp16 makePrimary:(BOOL)fp20 tabIndex:(int)fp24 albumToSet:(id)fp28;
- (void)showViewController:(id)fp8 fromView:(id)fp12 hideStatus:(BOOL)fp16;
- (void)animateStatusBar:(BOOL)fp8;
- (struct CGRect)wrapperFrame:(BOOL)fp8;
- (id)wrapperView;
- (void)updatePhotoController;
- (id)photoEditor;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)setMainTabIndex:(int)fp8;
- (id)tabControllerForIndex:(int)fp8;
- (id)currentBackName;
- (id)currentTabName;
- (id)frontMostViewController;
- (void)switchToTab:(id)fp8;
- (void)switchToTab:(id)fp8 animationType:(int)fp12;
- (void)awakeFromNib;

@end

