/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIImageView, UILabel, UITapGestureRecognizer;

@interface BLMomentaryImageView : _ACAccountTypeIdentifierTwitter
{
    UIImageView *_backgroundView;
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UITapGestureRecognizer *_tapGestureRecognizer;
    BOOL _hiding;
}

+ (id)sharedInstance;
- (void)showImageWithCGImage:(struct CGImage *)fp8 title:(id)fp12 inSuperview:(id)fp16;
- (void)showImageWithCGImage:(struct CGImage *)fp8 title:(id)fp12;
- (void)showImageWithData:(id)fp8 title:(id)fp12 inSuperview:(id)fp16;
- (void)showImageWithData:(id)fp8 title:(id)fp12;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)dealloc;
- (void)_showInSuperview:(id)fp8;
- (void)_handleTapGesture:(id)fp8;
- (void)_viewWasHidden:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)_delayedShow;
- (void)_delayedHide;

@end

