/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIActivityIndicatorView, UIBezierPath, UILabel, UIProgressView;

@interface BLMomentaryActivityView : _ACAccountTypeIdentifierTwitter
{
    UIBezierPath *_innerRoundedRectanglePath;
    UIBezierPath *_outterRoundedRectanglePath;
    UILabel *_label;
    UIActivityIndicatorView *_activityIndicatorView;
    UIProgressView *_progressView;
    float _progress;
    BOOL _autoHide;
    BOOL _hiding;
}

+ (id)sharedInstance;
- (void)hide;
- (void)showWithMessage:(id)fp8 progress:(float)fp12 afterDelay:(double)fp16 inSuperview:(id)fp24 andAutoHide:(BOOL)fp28;
- (void)showWithMessage:(id)fp8 progress:(float)fp12 inSuperview:(id)fp16;
- (void)showWithMessage:(id)fp8 progress:(float)fp12;
- (void)showWithMessage:(id)fp8 inSuperview:(id)fp12 andAutoHide:(BOOL)fp16;
- (void)showWithMessage:(id)fp8 inSuperview:(id)fp12;
- (void)showWithMessage:(id)fp8;
- (void)drawRect:(struct CGRect)fp8;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)dealloc;
- (void)_viewWasHidden:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)_delayedShow;
- (void)_delayedHide;

@end

