/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSLock, NSMutableDictionary;

@interface BLNetworkObserver : _ACAccountTypeIdentifierTwitter
{
    NSLock *_lock;
    NSMutableDictionary *_reachabilityRequests;
    unsigned int _networkReachability;
    struct __SCNetworkReachability *_networkReach;
    struct __CFDictionary *_networkObservers;
    BOOL _networkNotified;
    BOOL _networkReachable;
}

+ (id)sharedNetworkObserver;
- (void)removeNetworkReachableObserver:(id)fp8;
- (void)addNetworkReachableObserver:(id)fp8 selector:(SEL)fp12;
- (BOOL)isNetworkReachable;
- (void)_networkReachableFirstCallBack:(id)fp8;
- (void)_networkReachableCallBack:(unsigned int)fp8;
- (void)_networkObserversInitialize;
- (void)removeObserver:(id)fp8 forHostname:(id)fp12;
- (void)removeObserver:(id)fp8;
- (void)addObserver:(id)fp8 selector:(SEL)fp12 forHostname:(id)fp16;
- (void)dealloc;
- (id)init;

@end

