/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSString;

@interface BLOAuthToken : _ACAccountTypeIdentifierTwitter
{
    NSString *m_key;
    NSString *m_secret;
}

+ (id)tokenWithKey:(id)fp8 andSecret:(id)fp12;
- (void)setSecret:(id)fp8;
- (id)secret;
- (void)setKey:(id)fp8;
- (id)key;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithKey:(id)fp8 andSecret:(id)fp12;

@end

