/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class BLOAuthConsumer, BLOAuthToken, NSMutableArray, NSString;

@interface BLOAuthURLRequest : _ACAccountTypeIdentifierTwitter
{
    NSString *m_timestamp;
    NSString *m_nonce;
    NSString *m_version;
    NSString *m_signatureMethod;
    NSMutableArray *m_extraOAuthParameters;
    BLOAuthToken *m_token;
    BLOAuthConsumer *m_consumer;
}

+ (id)requestWithURL:(id)fp8 cachePolicy:(unsigned int)fp12 timeoutInterval:(double)fp16 token:(id)fp24 consumer:(id)fp28 andParameters:(id)fp32;
- (void)performRequestWithCompletionBlock:(id)fp(null);
- (void)updateAuthorizationHeader;
- (id)parameterString;
- (id)signatureBaseString;
- (id)parametersFromQueryComponent;
- (void)updateNonce;
- (void)updateTimestamp;
- (void)addOAuthParmeter:(id)fp8;
- (void)dealloc;
- (id)initWithURL:(id)fp8 cachePolicy:(unsigned int)fp12 timeoutInterval:(double)fp16 token:(id)fp24 consumer:(id)fp28 andParameters:(id)fp32;

@end

