/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIImage;

@interface BLPageControl : _ACAccountTypeIdentifierTwitter
{
    UIImage *m_normalImage;
    UIImage *m_currentImage;
}

- (void)setCurrentImage:(id)fp8;
- (void)setNormalImage:(id)fp8;
- (void)dealloc;
- (void)awakeFromNib;
- (void)endTrackingWithTouch:(id)fp8 withEvent:(id)fp12;
- (void)updateCurrentPageDisplay;
- (void)setCurrentPage:(int)fp8;
- (void)updateDots;
- (id)currentImage;
- (id)normalImage;

@end

