/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLPhotoFXRangeView.h"

@interface BLPhotoFXIndexedView : BLPhotoFXRangeView
{
}

- (void)setValueFromTouches:(id)fp8;
- (void)updateHighlight;
- (int)tagAtLocation:(struct CGPoint)fp8;
- (void)highlightThumbWithTag:(int)fp8;

@end

