/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLMainTabController.h"

@class BLAlbum;

@interface BLPhotoListViewController : BLMainTabController
{
    BLAlbum *m_album;
}

+ (id)controller;
- (void)setAlbum:(id)fp8;
- (id)album;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (id)cellsToAnimate;
- (id)emptyImageKey;
- (id)emptyLabel;
- (id)helpTag;
- (void)setupObjects;
- (void)showEditorFromView:(id)fp8;
- (void)showEditorFromView:(id)fp8 withSelectedItems:(id)fp12;
- (int)numberOfColumns;
- (Class)itemViewClass;
- (Class)cellClass;
- (id)tabNibName;
- (int)cacheLimit;

@end

