/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIView;

@interface BLPhotoFXCardHolder : _ACAccountTypeIdentifierTwitter
{
    UIView *m_cardWrapper;
    BOOL m_leftHandLayout;
}

- (BOOL)leftHandLayout;
- (void)setCardWrapper:(id)fp8;
- (id)cardWrapper;
- (void)dealloc;
- (void)awakeFromNib;
- (void)setLeftHandLayout:(BOOL)fp8;
- (void)updateCardCenter;
- (struct CGPoint)cardCenter;

@end

