/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLMainTabCell.h"

@interface BLPhotoListCell : BLMainTabCell
{
}

- (id)newViewForFrame:(struct CGRect)fp8 index:(int)fp24;
- (void)updateBackgroundImage;
- (struct CGRect)frameForColumn:(int)fp8;

@end

