/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLLeftHandView.h"

@class BLBlurredLabel, UIImageView, UIView;

@interface BLPhotoFXCardView : BLLeftHandView
{
    float m_rotation;
    float m_rotationOffset;
    BOOL m_showLabel;
    BOOL m_highlighted;
    BLBlurredLabel *m_blurredLabel;
    UIView *m_blurredWrapper;
    UIView *m_shadowView;
    UIImageView *m_highlightView;
}

- (BOOL)highlighted;
- (BOOL)showLabel;
- (float)rotationOffset;
- (float)rotation;
- (void)awakeFromNib;
- (void)didMoveToSuperview;
- (void)setHighlighted:(BOOL)fp8;
- (void)setLeftHandLayout:(BOOL)fp8;
- (int)minEdgeWidth;
- (void)updateCenters;
- (void)setCenter:(struct CGPoint)fp8;
- (void)updateShadowCenter;
- (void)setShowLabel:(BOOL)fp8;
- (void)setRotationOffset:(float)fp8;
- (void)setRotation:(float)fp8;
- (void)setThumbnail:(id)fp8;
- (void)view:(id)fp8 setThumbnail:(id)fp12;
- (void)a_forceCurrentCard:(id)fp8;
- (float)defaultEffectValue;

@end

