/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLPhotoFXCardViewAccessibility.h"

@interface BLPhotoFXCardViewAccessibility (SafeCategory)
- (unsigned long long)accessibilityTraits;
- (struct CGPoint)accessibilityActivationPoint;
- (id)accessibilityHint;
- (id)accessibilityLabel;
- (BOOL)accessibilityElementsHidden;
- (BOOL)isAccessibilityElement;
- (BOOL)_axIsEffectChooser;
@end

