/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSDictionary, UIView;

@interface BLPhotoFXCardWrapper : _ACAccountTypeIdentifierTwitter <UIGestureRecognizerDelegate>
{
    UIView *m_leftPin;
    UIView *m_rightPin;
    UIView *m_bigShadow;
    NSDictionary *m_valueDict;
    BOOL m_shadowMoved;
    int m_state;
    int m_index;
    float m_startAngle;
    BOOL m_fanInProgress;
    UIView *m_coverView;
    int m_cardCount;
    BOOL m_leftHandLayout;
    BOOL m_wakingUp;
}

- (int)index;
- (int)state;
- (BOOL)leftHandLayout;
- (void)setBigShadow:(id)fp8;
- (id)bigShadow;
- (void)setRightPin:(id)fp8;
- (id)rightPin;
- (void)setLeftPin:(id)fp8;
- (id)leftPin;
- (void)dealloc;
- (void)willMoveToWindow:(id)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)setLeftHandLayout:(BOOL)fp8;
- (void)setState:(int)fp8 index:(int)fp12;
- (void)setIndex:(int)fp8;
- (void)setState:(int)fp8;
- (void)awakeFromNib;
- (void)panelDidShow:(id)fp8;
- (void)updateCurrentPhoto;
- (void)updateCenters;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (void)userTapped;
- (void)a_fanOut:(id)fp8;
- (void)cardTapped:(id)fp8;
- (void)removeCoverView;
- (void)addCoverView;
- (void)cardsSwiped:(id)fp8;
- (void)setRotation:(float)fp8;
- (float)angle:(id)fp8;
- (struct CGPoint)cardCenter;
- (void)updateCardAngles:(BOOL)fp8 constantDuration:(BOOL)fp12;
- (void)updateCenter;
- (float)upAngle;
- (float)angleStep;
- (id)currentCard;
- (id)backGroundView;
- (void)setThumbnail:(id)fp8;

@end

