/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UILabel, UIView;

@interface BLPopupSliderButton : _ACAccountTypeIdentifierTwitter
{
    UIView *m_viewToShow;
    UIView *m_outerView;
    UILabel *m_keyToWatch1;
    UILabel *m_keyToWatch2;
    BOOL m_pressed;
    int m_count;
}

- (BOOL)pressed;
- (void)setKeyToWatch2:(id)fp8;
- (id)keyToWatch2;
- (void)setKeyToWatch1:(id)fp8;
- (id)keyToWatch1;
- (void)setViewToShow:(id)fp8;
- (id)viewToShow;
- (void)setOuterView:(id)fp8;
- (id)outerView;
- (void)dealloc;
- (void)willMoveToWindow:(id)fp8;
- (void)effectDidChange:(id)fp8;
- (void)effectWillChange:(id)fp8;
- (BOOL)isWatchedKey:(id)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)awakeFromNib;
- (void)a_hidePopOver:(id)fp8;
- (void)hide;
- (void)a_togglePressed:(id)fp8;
- (void)setPressed:(BOOL)fp8;
- (void)setSelected:(BOOL)fp8 animated:(BOOL)fp12;
- (id)backGroundView;

@end

