/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSArray, NSDate, NSString, NSURL;

@interface BLPost : _ACAccountTypeIdentifierTwitter
{
    int m_type;
    NSArray *m_comments;
    NSURL *m_imageUrl;
    NSString *m_status;
    NSString *m_name;
    NSDate *m_date;
}

+ (id)postWithType:(int)fp8 date:(id)fp12 andName:(id)fp16;
- (void)setDate:(id)fp8;
- (id)date;
- (void)setName:(id)fp8;
- (id)name;
- (void)setStatus:(id)fp8;
- (id)status;
- (void)setImageUrl:(id)fp8;
- (id)imageUrl;
- (void)setComments:(id)fp8;
- (id)comments;
- (void)setType:(int)fp8;
- (int)type;
- (id)description;
- (void)dealloc;

@end

