/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLMainTabItemView.h"

#import "UITextFieldDelegate-Protocol.h"

@class UIButton, UIImageView, UITextField;

@interface BLProjectListItem : BLMainTabItemView <UITextFieldDelegate>
{
    UITextField *m_label;
    UIImageView *m_borderView;
    UIButton *m_deleteButton;
    UIButton *m_favoriteButton;
    BOOL m_editMode;
    BOOL m_added;
}

- (BOOL)editMode;
- (void)setFavoriteButton:(id)fp8;
- (id)favoriteButton;
- (void)setDeleteButton:(id)fp8;
- (id)deleteButton;
- (void)setObject:(id)fp8;
- (void)albumContentsChanged:(id)fp8;
- (id)imageCache;
- (id)posterMedia;
- (BOOL)wantHighResThumbnails;
- (int)thumbSize;
- (id)key;
- (id)initWithFrame:(struct CGRect)fp8 index:(int)fp24;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (void)textFieldDidEndEditing:(id)fp8;
- (void)textFieldDidBeginEditing:(id)fp8;
- (void)scrollViewForKeyboard:(id)fp8;
- (id)enclosingScrollViewForView:(id)fp8;
- (id)imageNameForIndex:(int)fp8;
- (void)setEditMode:(BOOL)fp8;
- (void)setEditMode:(BOOL)fp8 animated:(BOOL)fp12;
- (void)removeButtons;
- (void)showEditor;
- (void)startSpinner;
- (void)a_makeFavorite:(id)fp8;
- (void)a_deleteProject:(id)fp8;

@end

