/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLImage.h"

@class BLAdjustmentModel, BLCropModel, BLPhotoEffectsModel, BLRepairModel, BLRetouchModel, CIContext, NSLock, UIImage;

@interface BLPromiseImage : BLImage
{
    struct CGImage *m_sourceCGImage;
    int m_backOrientation;
    int m_initialOrientation;
    int m_actualOrientation;
    struct CGSize m_sourceSize;
    BLCropModel *m_cropModel;
    BLAdjustmentModel *m_adjustmentModel;
    BLPhotoEffectsModel *m_photoEffectsModel;
    BLRetouchModel *m_retouchModel;
    BLRepairModel *m_repairModel;
    CIContext *m_ciContext;
    UIImage *m_repairImage;
    NSLock *m_repairImageLock;
}

+ (struct CGSize)maximumSizeForFlattening;
+ (id)CIContext;
- (id)flattenedSquareThumbImageOfDimension:(float)fp8;
- (id)flattenedImageInBoundingSize:(struct CGSize)fp8;
- (id)flattenedImageInBoundingSize:(struct CGSize)fp8 shouldScaleForScreen:(BOOL)fp16;
- (id)CIImage;
- (id)UIImage;
- (struct CGImage *)CGImage;
- (struct CGSize)maximumSize;
- (void)drawInContext:(struct CGContext *)fp8 forRect:(struct CGRect)fp12 andSize:(struct CGSize)fp28;
- (id)flattenedImageFromRect:(struct CGRect)fp8;
- (void)setRepairLayerStack:(id)fp8;
- (void)setRetouchLayerStack:(id)fp8;
- (BOOL)hasRotation;
- (BOOL)hasRepair;
- (BOOL)hasRetouch;
- (BOOL)hasPhotoFX;
- (BOOL)hasColor;
- (BOOL)hasExposure;
- (BOOL)hasCrop;
- (BOOL)hasEdits;
- (void)dealloc;
- (id)initWithCGImage:(struct CGImage *)fp8 backOrientation:(int)fp12 orientation:(int)fp16 adjustmentData:(id)fp20 andAnalysisData:(id)fp24 andOptionFlags:(int)fp28;
- (id)initWithCGImage:(struct CGImage *)fp8 orientation:(int)fp12 adjustmentData:(id)fp16 andAnalysisData:(id)fp20 andOptionFlags:(int)fp24;
- (id)initWithCGImage:(struct CGImage *)fp8 orientation:(int)fp12 adjustmentData:(id)fp16 andAnalysisData:(id)fp20;

@end

