/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLMainTabController.h"

@class NSArray, UIButton, UIView;

@interface BLProjectListViewController : BLMainTabController
{
    UIButton *m_editButton;
    UIView *m_iPhoneEditView;
    UIView *m_iPhoneBarBackground;
    BOOL m_editMode;
    BOOL m_layoutDone;
    BOOL m_observerAdded;
    BOOL m_firstTimeDone;
    double m_lastUpdateTime;
    BOOL m_updatePending;
    NSArray *m_arrangedProjects;
    NSArray *m_journalList;
    NSArray *m_remoteJournals;
}

+ (id)controller;
- (void)setRemoteJournals:(id)fp8;
- (id)remoteJournals;
- (void)setJournalList:(id)fp8;
- (id)journalList;
- (void)setIPhoneEditView:(id)fp8;
- (id)iPhoneEditView;
- (void)setArrangedProjects:(id)fp8;
- (id)arrangedProjects;
- (BOOL)editMode;
- (void)setM_iPhoneBarBackground:(id)fp8;
- (id)m_iPhoneBarBackground;
- (void)setM_editButton:(id)fp8;
- (id)m_editButton;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (id)emptyImageKey;
- (id)emptyLabel;
- (id)helpTag;
- (void)setupObjects;
- (BOOL)requestRemoteJournals;
- (void)updateJournals;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)a_edit:(id)fp8;
- (id)settingsNibName;
- (void)setEditMode:(BOOL)fp8;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 viewForHeaderInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForHeaderInSection:(int)fp12;
- (id)font;
- (int)numberOfSectionsInTableView:(id)fp8;
- (id)objectsToDisplayInSection:(int)fp8;
- (void)dismissViewController;
- (void)reloadAnimated;
- (void)updateArrangedAlbumsWithAlbums:(id)fp8;
- (int)numberOfColumns;
- (Class)itemViewClass;
- (Class)cellClass;
- (id)tabNibName;

@end

