/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface BLQueue : _ACAccountTypeIdentifierTwitter
{
    struct dispatch_queue_s *m_queue;
}

+ (void)queueOnMainThread:(id)fp(null) withDelay:(void)fp8;
+ (void)queueOnMainThread:(id)fp(null);
+ (void)queueAsyncWithPool:(id)fp(null);
+ (void)queueAsyncHighPriority:(id)fp(null);
+ (void)queueAsyncLowPriority:(id)fp(null);
+ (void)queueAsync:(id)fp(null) withDelay:(void)fp8;
+ (void)queueAsync:(id)fp(null);
- (void)queueSync:(id)fp(null);
- (void)queueAsyncWithPool:(id)fp(null);
- (void)queueAsync:(id)fp(null);
- (void)dealloc;
- (id)initWithLabel:(const char *)fp8;

@end

