/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class BLRetouchCoverButton, UIView;

@interface BLRetouchBrushContainer : _ACAccountTypeIdentifierTwitter
{
    UIView *m_indicators;
    UIView *m_shadow;
    UIView *m_parent;
    BOOL m_circle;
    BOOL m_wakingUp;
    BLRetouchCoverButton *m_coverButton;
}

+ (id)currentContainer;
- (BOOL)circle;
- (void)setM_shadow:(id)fp8;
- (id)m_shadow;
- (void)setM_indicators:(id)fp8;
- (id)m_indicators;
- (void)dealloc;
- (void)awakeFromNib;
- (void)willMoveToWindow:(id)fp8;
- (void)willMoveToSuperview:(id)fp8;
- (void)panelDidAppear:(id)fp8;
- (void)panelDidShow:(id)fp8;
- (void)toolWillChange;
- (void)setCircle:(BOOL)fp8;
- (void)setCircle:(BOOL)fp8 brushType:(int)fp12;
- (void)updateCircleWithDuration:(float)fp8 brushType:(int)fp12;
- (void)removeCoverButton;
- (id)backGroundView;

@end

