/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface BLReachabilityManager : _ACAccountTypeIdentifierTwitter
{
}

+ (id)sharedInstance;
- (void)checkReachabilityForHostname:(id)fp8 timeout:(double)fp12 completionBlock:(id)fp(null);
- (void)dealloc;
- (void)cancelWithInfo:(id)fp8;

@end

