/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLRetouchOffsetView.h"

@class NSTimer, UIButton, UIView;

@interface BLRepairOffsetView : BLRetouchOffsetView
{
    UIView *m_halo;
    UIView *m_orb1;
    UIView *m_orb2;
    UIView *m_orb3;
    UIView *m_orb4;
    UIButton *m_eraseButton;
    UIButton *m_magicEdgesButton;
    NSTimer *m_timer;
    struct CGPoint m_initialOrbCenters[4];
    float m_angles[4];
    float m_haloGlow;
    float m_positionRamp;
}

- (void)setM_eraseButton:(id)fp8;
- (id)m_eraseButton;
- (void)setM_magicEdgesButton:(id)fp8;
- (id)m_magicEdgesButton;
- (void)setM_orb4:(id)fp8;
- (id)m_orb4;
- (void)setM_orb3:(id)fp8;
- (id)m_orb3;
- (void)setM_orb2:(id)fp8;
- (id)m_orb2;
- (void)setM_orb1:(id)fp8;
- (id)m_orb1;
- (void)setM_halo:(id)fp8;
- (id)m_halo;
- (void)dealloc;
- (void)setValue:(float)fp8;
- (void)awakeFromNib;
- (void)updateEnable;
- (void)bounceBrush;
- (void)updatePosition;
- (void)updateOrbAlphas;
- (void)stopTimer;
- (void)startTimer;
- (void)timerAction;

@end

