/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLRetouchLayer.h"

@class CIContext, CIImage, NSMutableArray, UIImage;

@interface BLRetouchRedEyeLayer : BLRetouchLayer
{
    NSMutableArray *m_eyePoints;
    struct CGSize m_maskSize;
    UIImage *m_repairSourceImage;
    CIContext *m_ciContext;
    CIImage *m_ciSourceImage;
    UIImage *m_repairedImage;
}

+ (id)addAutoRedEyeCorrection:(id)fp8 toLayerData:(id)fp12 maskSize:(struct CGSize)fp16 newTimestampIncrement:(double *)fp24;
+ (int)indexOfPointNear:(struct CGPoint)fp8 inEyePoints:(id)fp16 andMaskSize:(struct CGSize)fp20;
- (void)setRepairedImage:(id)fp8;
- (id)repairedImage;
- (id)repairSourceImage;
- (void)setMaskSize:(struct CGSize)fp8;
- (struct CGSize)maskSize;
- (void)clearRedEyes;
- (struct CGContext *)newContextForRect:(struct CGRect)fp8 inDestRect:(struct CGRect)fp24 withPadding:(float)fp40 andScale:(float)fp44;
- (struct CGRect)area;
- (void)dealloc;
- (void)setRepairSourceImage:(id)fp8;
- (struct CGRect)tapAtPoint:(struct CGPoint)fp8 actualLocation:(struct CGPoint *)fp16 foundEye:(char *)fp20 addedEye:(char *)fp24;
- (void)setLayerData:(id)fp8;
- (id)layerData;
- (int)indexOfPointNear:(struct CGPoint)fp8;
- (void)setEyePoints:(id)fp8;
- (id)eyePoints;
- (void)repairRedEyes;
- (struct CGRect)maskFrame;
- (BOOL)hasLayerMask;
- (float)amount;
- (void)hasLayerMaskDidChange;

@end

