/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSString;

@interface BLRemoteJournal : _ACAccountTypeIdentifierTwitter
{
    NSString *m_uuid;
    NSString *m_title;
    double m_dateModified;
    BOOL m_onIndexPage;
    NSString *m_posterImagePath;
    BOOL m_urlRequestInProgress;
}

+ (void)removeObsoleteRemoteURLs:(id)fp8;
+ (id)remoteJournalWithUUID:(id)fp8 title:(id)fp12 dateModified:(double)fp16 onIndexPage:(BOOL)fp24 andPosterImagePath:(id)fp28;
- (void)setUrlRequestInProgress:(BOOL)fp8;
- (BOOL)urlRequestInProgress;
- (void)setPosterImagePath:(id)fp8;
- (id)posterImagePath;
- (void)setOnIndexPage:(BOOL)fp8;
- (BOOL)onIndexPage;
- (void)setDateModified:(double)fp8;
- (double)dateModified;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setUuid:(id)fp8;
- (id)uuid;
- (void)dealloc;
- (id)initWithUUID:(id)fp8;
- (id)posterImage;
- (id)urlString;
- (void)setRating:(int)fp8;
- (int)rating;
- (id)description;

@end

