/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class BLRetouchLayerStack, NSDictionary, NSLock;

@interface BLRetouchModel : _ACAccountTypeIdentifierTwitter
{
    NSDictionary *m_strokesDataDictionary;
    BLRetouchLayerStack *m_layerStack;
    NSLock *m_lock;
}

- (id)imageForWorkingImage:(id)fp8 workingTransform:(struct CGAffineTransform)fp12 inDestRect:(struct CGRect)fp36 withPadding:(float)fp52;
- (float)paddingForSize:(struct CGSize)fp8;
- (BOOL)needsPadding;
- (BOOL)hasLayerStack;
- (void)setLayerStack:(id)fp8;
- (void)releaseLayerStack;
- (void)buildLayerStackWithMaskSourceImage:(id)fp8;
- (BOOL)hasRetouch;
- (void)dealloc;
- (id)initWithAdjustmentsDictionary:(id)fp8;

@end

