/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIImageView;

@interface BLResizableImageView : _ACAccountTypeIdentifierTwitter
{
    UIImageView *m_topLeftView;
    UIImageView *m_topCenterView;
    UIImageView *m_topRightView;
    UIImageView *m_centerLeftView;
    UIImageView *m_centerView;
    UIImageView *m_centerRightView;
    UIImageView *m_bottomLeftView;
    UIImageView *m_bottomCenterView;
    UIImageView *m_bottomRightView;
}

- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 image:(id)fp24 capInsets:(struct UIEdgeInsets)fp28;

@end

