/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLBaseLayerStack.h"

@class UIImage;

@interface BLRepairLayerStack : BLBaseLayerStack
{
    UIImage *m_sourceImage;
    UIImage *m_analysisImage;
    UIImage *m_repairSourceImage;
    struct CGSize m_repairSourceSize;
    UIImage *m_redEyeSourceImage;
    struct CGSize m_redEyeSourceSize;
    int m_mode;
}

+ (id)layerStack;
+ (id)addAutoRedEyeCorrection:(id)fp8 toCurrentStrokesDataDictionary:(id)fp12 forSourceSize:(struct CGSize)fp16;
+ (int)maxEdgeSize;
- (int)mode;
- (void)setRedEyeSourceSize:(struct CGSize)fp8;
- (struct CGSize)redEyeSourceSize;
- (id)redEyeSourceImage;
- (void)setRepairSourceSize:(struct CGSize)fp8;
- (struct CGSize)repairSourceSize;
- (id)repairSourceImage;
- (id)analysisImage;
- (void)setSourceImage:(id)fp8;
- (id)sourceImage;
- (void)repairChanged;
- (void)redEyeChanged;
- (struct CGContext *)newContextForRect:(struct CGRect)fp8 inDestRect:(struct CGRect)fp24 withPadding:(float)fp40 andScale:(float)fp44;
- (BOOL)readyToDrawForMode:(int)fp8;
- (void)setMode:(int)fp8;
- (id)redEyeRepairedImage;
- (void)setRedEyeRepairedImage:(id)fp8;
- (id)repairedImage;
- (void)setRepairedImage:(id)fp8;
- (double)timestamp;
- (void)dealloc;
- (BOOL)hasRedEye;
- (BOOL)hasRepair;
- (BOOL)haveLayerMask;
- (BOOL)readyToDraw;
- (void)setStrokesDataDictionary:(id)fp8;
- (id)strokesDataDictionary;
- (void)setRedEyeSourceImage:(id)fp8;
- (void)setRepairSourceImage:(id)fp8;
- (void)setAnalysisImage:(id)fp8;
- (void)setMaskSize:(struct CGSize)fp8;
- (id)init;

@end

