/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLLeftHandView.h"

@class BLEffectIndicator, UIView;

@interface BLRetouchToolWrapper : BLLeftHandView
{
    UIView *m_indicatorView;
    UIView *m_innerButton;
    UIView *m_toolView;
    int m_toolWidth;
    UIView *m_repairBanner;
    UIView *m_redEyeBanner;
    UIView *m_saturateBanner;
    UIView *m_desaturateBanner;
    UIView *m_lightenBanner;
    UIView *m_darkenBanner;
    UIView *m_softenBanner;
    UIView *m_sharpenBanner;
    UIView *m_combinedBanner;
    BLEffectIndicator *m_repairIndicator;
    BLEffectIndicator *m_redEyeIndicator;
    BLEffectIndicator *m_saturateIndicator;
    BLEffectIndicator *m_desaturateIndicator;
    BLEffectIndicator *m_lightenIndicator;
    BLEffectIndicator *m_darkenIndicator;
    BLEffectIndicator *m_sharpenIndicator;
    BLEffectIndicator *m_softenIndicator;
}

+ (id)retouchToolWrapper;
- (void)setToolView:(id)fp8;
- (id)toolView;
- (void)setSoftenIndicator:(id)fp8;
- (id)softenIndicator;
- (void)setSharpenIndicator:(id)fp8;
- (id)sharpenIndicator;
- (void)setDarkenIndicator:(id)fp8;
- (id)darkenIndicator;
- (void)setLightenIndicator:(id)fp8;
- (id)lightenIndicator;
- (void)setDesaturateIndicator:(id)fp8;
- (id)desaturateIndicator;
- (void)setSaturateIndicator:(id)fp8;
- (id)saturateIndicator;
- (void)setRedEyeIndicator:(id)fp8;
- (id)redEyeIndicator;
- (void)setRepairIndicator:(id)fp8;
- (id)repairIndicator;
- (void)setCombinedBanner:(id)fp8;
- (id)combinedBanner;
- (void)setSoftenBanner:(id)fp8;
- (id)softenBanner;
- (void)setSharpenBanner:(id)fp8;
- (id)sharpenBanner;
- (void)setDarkenBanner:(id)fp8;
- (id)darkenBanner;
- (void)setLightenBanner:(id)fp8;
- (id)lightenBanner;
- (void)setDesaturateBanner:(id)fp8;
- (id)desaturateBanner;
- (void)setSaturateBanner:(id)fp8;
- (id)saturateBanner;
- (void)setRedEyeBanner:(id)fp8;
- (id)redEyeBanner;
- (void)setRepairBanner:(id)fp8;
- (id)repairBanner;
- (void)setM_indicatorView:(id)fp8;
- (id)m_indicatorView;
- (void)setM_innerButton:(id)fp8;
- (id)m_innerButton;
- (void)updateIndicatorBannersForDisabledToolTypes:(int)fp8;
- (void)dealloc;
- (void)awakeFromNib;
- (void)addTools;
- (void)setFrame:(struct CGRect)fp8;
- (void)updateSubviews;

@end

