/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLEffectIndicator.h"

@interface BLRetouchIndicator : BLEffectIndicator
{
    BLEffectIndicator *m_otherIndicator;
}

- (void)setM_otherIndicator:(id)fp8;
- (id)m_otherIndicator;
- (void)takeValue;

@end

