/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLEffectForwardingView.h"

@class UIView;

@interface BLRetouchForwardingView : BLEffectForwardingView
{
    UIView *m_sliderView;
}

- (void)setSliderView:(id)fp8;
- (id)sliderView;
- (void)dealloc;
- (void)willMoveToWindow:(id)fp8;

@end

