/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIButton;

@interface BLRetouchIPhoneAmountView : _ACAccountTypeIdentifierTwitter
{
    UIButton *m_coverButton;
}

- (void)willMoveToWindow:(id)fp8;
- (void)a_hide:(id)fp8;
- (void)hide;
- (void)show;
- (id)backGroundView;

@end

