/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLBrushStroke.h"

@interface BLRepairBrushStroke : BLBrushStroke
{
    struct CGPoint m_repairTextureOffset;
}

- (void)setRepairTextureOffset:(struct CGPoint)fp8;
- (struct CGPoint)repairTextureOffset;
- (id)keysToEncode;

@end

