/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class BLBaseLayerStack;

@interface BLRetouchLayer : _ACAccountTypeIdentifierTwitter
{
    BLRetouchLayer *m_layerBelow;
    BOOL m_enabled;
    BLBaseLayerStack *m_layerStack;
}

+ (id)layer;
- (void)setEnabled:(BOOL)fp8;
- (BOOL)enabled;
- (void)setLayerStack:(id)fp8;
- (id)layerStack;
- (void)setLayerBelow:(id)fp8;
- (id)layerBelow;
- (void)dealloc;
- (id)init;
- (BOOL)hasLayerMask;
- (void)setLayerData:(id)fp8;
- (id)layerData;
- (struct CGContext *)newContextForRect:(struct CGRect)fp8 inDestRect:(struct CGRect)fp24 withPadding:(float)fp40 andScale:(float)fp44;
- (struct CGSize)imageSize;
- (BOOL)boolForKey:(id)fp8;

@end

