/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface BLRetouchReefBlurOperator : _ACAccountTypeIdentifierTwitter
{
}

+ (struct CGContext *)newContext:(struct CGContext *)fp8 withBlur:(float)fp12;
+ (struct CGContext *)newContext:(struct CGContext *)fp8 withUnsharpMask:(float)fp12 threshold:(float)fp16 strength:(float)fp20;

@end

