/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface BLSaturationHistogramAnalysis : _ACAccountTypeIdentifierTwitter
{
    float m_highSaturationPoint;
}

- (void)setHighSaturationPoint:(float)fp8;
- (float)highSaturationPoint;
- (id)analysisDictionary;
- (id)description;
- (void)dealloc;
- (id)initWithAnalysisDictionary:(id)fp8;
- (id)initWithBLImage:(id)fp8;

@end

