/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIPopoverController;

@interface BLSharingNavigationController : _ACAccountTypeIdentifierTwitter
{
    UIPopoverController *m_popoverDelegate;
}

- (id)popoverDelegate;
- (void)pushViewController:(id)fp8 animated:(BOOL)fp12;
- (void)setViewControllers:(id)fp8 animated:(BOOL)fp12;
- (void)setPopoverDelegate:(id)fp8;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

