/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLSharingServiceViewController.h"

@class UIButton, UITableView, UIView;

@interface BLShareToButtonController : BLSharingServiceViewController
{
    UIButton *journalButtonLandscape;
    UIButton *iTunesButtonLandscape;
    UIButton *slideshowButtonLandscape;
    UIButton *emailButtonLandscape;
    UIButton *cameraRollButtonLandscape;
    UIButton *beamButtonLandscape;
    UIButton *flickrButtonLandscape;
    UIButton *twitterButtonLandscape;
    UIButton *facebookButtonLandscape;
    UIButton *printButtonLandscape;
    UITableView *tableView;
    UIButton *journalButtonPortrait;
    UIButton *iTunesButtonPortrait;
    UIButton *slideshowButtonPortrait;
    UIButton *emailButtonPortrait;
    UIButton *cameraRollButtonPortrait;
    UIButton *beamButtonPortrait;
    UIButton *flickrButtonPortrait;
    UIButton *twitterButtonPortrait;
    UIButton *facebookButtonPortrait;
    UIButton *printButtonPortrait;
    UIView *portraitContentView;
    UIView *landscapeContentView;
    UIView *barButtonView;
}

- (void)setBarButtonView:(id)fp8;
- (id)barButtonView;
- (void)setLandscapeContentView:(id)fp8;
- (id)landscapeContentView;
- (void)setPortraitContentView:(id)fp8;
- (id)portraitContentView;
- (void)setPrintButtonPortrait:(id)fp8;
- (id)printButtonPortrait;
- (void)setFacebookButtonPortrait:(id)fp8;
- (id)facebookButtonPortrait;
- (void)setTwitterButtonPortrait:(id)fp8;
- (id)twitterButtonPortrait;
- (void)setFlickrButtonPortrait:(id)fp8;
- (id)flickrButtonPortrait;
- (void)setBeamButtonPortrait:(id)fp8;
- (id)beamButtonPortrait;
- (void)setCameraRollButtonPortrait:(id)fp8;
- (id)cameraRollButtonPortrait;
- (void)setEmailButtonPortrait:(id)fp8;
- (id)emailButtonPortrait;
- (void)setSlideshowButtonPortrait:(id)fp8;
- (id)slideshowButtonPortrait;
- (void)setITunesButtonPortrait:(id)fp8;
- (id)iTunesButtonPortrait;
- (void)setJournalButtonPortrait:(id)fp8;
- (id)journalButtonPortrait;
- (void)setTableView:(id)fp8;
- (id)tableView;
- (void)setPrintButtonLandscape:(id)fp8;
- (id)printButtonLandscape;
- (void)setFacebookButtonLandscape:(id)fp8;
- (id)facebookButtonLandscape;
- (void)setTwitterButtonLandscape:(id)fp8;
- (id)twitterButtonLandscape;
- (void)setFlickrButtonLandscape:(id)fp8;
- (id)flickrButtonLandscape;
- (void)setBeamButtonLandscape:(id)fp8;
- (id)beamButtonLandscape;
- (void)setCameraRollButtonLandscape:(id)fp8;
- (id)cameraRollButtonLandscape;
- (void)setEmailButtonLandscape:(id)fp8;
- (id)emailButtonLandscape;
- (void)setSlideshowButtonLandscape:(id)fp8;
- (id)slideshowButtonLandscape;
- (void)setITunesButtonLandscape:(id)fp8;
- (id)iTunesButtonLandscape;
- (void)setJournalButtonLandscape:(id)fp8;
- (id)journalButtonLandscape;
- (void)a_cancel:(id)fp8;
- (void)a_print:(id)fp8;
- (void)a_facebook:(id)fp8;
- (void)a_twitter:(id)fp8;
- (void)a_flickr:(id)fp8;
- (void)a_beam:(id)fp8;
- (void)a_cameraRoll:(id)fp8;
- (void)a_email:(id)fp8;
- (void)a_slideshow:(id)fp8;
- (void)a_iTunes:(id)fp8;
- (void)a_journal:(id)fp8;
- (void)pushWithType:(int)fp8;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)viewWillAppear:(BOOL)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (struct CGSize)requiredPopoverSize;
- (void)dealloc;
- (void)releaseLocals;

@end

