/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLSharingServiceViewController.h"

#import "BLMarkingTarget-Protocol.h"
#import "UIPrintInteractionControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class UIActivityIndicatorView, UITableView, UIView;

@interface BLSharingViewController : BLSharingServiceViewController <UITableViewDelegate, UITableViewDataSource, UIPrintInteractionControllerDelegate, BLMarkingTarget>
{
    UIActivityIndicatorView *m_activityIndicator;
    BOOL m_hasActivity;
    int m_shareType;
    UITableView *m_tableView;
    id m_markingCompletedBlock;
    UIView *m_barButtonView;
}

- (void)setBarButtonView:(id)fp8;
- (id)barButtonView;
- (int)shareType;
- (void)setTableView:(id)fp8;
- (id)tableView;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)printInteractionControllerDidPresentPrinterOptions:(id)fp8;
- (id)printInteractionControllerParentViewController:(id)fp8;
- (void)facebook:(id)fp8;
- (void)twitter:(id)fp8;
- (void)flickr:(id)fp8;
- (void)print:(id)fp8;
- (void)beam:(id)fp8;
- (void)iTunes:(id)fp8;
- (id)iTunesDestinationFolder;
- (void)cameraRoll:(id)fp8;
- (void)email:(id)fp8;
- (void)slideshow:(id)fp8;
- (void)journal:(id)fp8;
- (void)markingCancelled;
- (void)markingCompleted:(id)fp8;
- (void)chooseWithCompletionBlock:(id)fp(null);
- (void)setShareType:(int)fp8;
- (void)logout:(id)fp8;
- (void)loginInfoChanged:(id)fp8;
- (void)setHasActivity:(BOOL)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (struct CGSize)requiredPopoverSize;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

