/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIBarButtonItem, UIPopoverController;

@interface BLSharingServiceViewController : _ACAccountTypeIdentifierTwitter
{
    UIPopoverController *m_popoverDelegate;
    struct CGSize m_requiredPopoverSize;
    unsigned int m_backgroundTaskIdentifier;
    BOOL m_backgroundTaskInProgress;
    UIBarButtonItem *m_shareButton;
}

- (void)setBackgroundTaskInProgress:(BOOL)fp8;
- (BOOL)backgroundTaskInProgress;
- (void)setBackgroundTaskIdentifier:(unsigned int)fp8;
- (unsigned int)backgroundTaskIdentifier;
- (void)setPopoverDelegate:(id)fp8;
- (id)popoverDelegate;
- (void)endBackgroundTask;
- (void)startBackgroundTaskWithExceptionHandler:(id)fp(null);
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidUnload;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)resizeIfNeeded;
- (struct CGSize)calculatedPopoverContentSize;
- (void)viewDidLoad;
- (void)a_share:(id)fp8;
- (void)setBottomButtonName:(id)fp8;
- (struct CGSize)requiredPopoverSize;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

