/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class BLBarView, BLViewerController, NSString, UIView;

@interface BLSidePanelController : _ACAccountTypeIdentifierTwitter
{
    BLViewerController *m_viewerController;
    UIView *m_view;
    BLBarView *m_landscapeHeader;
    UIView *m_leftEdge;
    UIView *m_rightEdge;
    NSString *m_nibName;
    int m_tool;
    BOOL m_showing;
    BOOL m_leftHandLayout;
    int m_lastTool;
}

- (BOOL)leftHandLayout;
- (void)setViewerController:(id)fp8;
- (id)viewerController;
- (void)setTool:(int)fp8;
- (int)tool;
- (void)setNibName:(id)fp8;
- (id)nibName;
- (void)setView:(id)fp8;
- (void)setM_landscapeHeader:(id)fp8;
- (id)m_landscapeHeader;
- (void)setM_rightEdge:(id)fp8;
- (id)m_rightEdge;
- (void)setM_leftEdge:(id)fp8;
- (id)m_leftEdge;
- (void)dealloc;
- (void)a_done:(id)fp8;
- (void)toolChanged;
- (void)animateOut;
- (void)animateIn:(BOOL)fp8;
- (id)keyframeAnimationForStartAngle:(float)fp8 endAngle:(float)fp12;
- (void)setupDimmingAnimationForInView:(id)fp8 outView:(id)fp12;
- (void)animationDidStop:(id)fp8 finished:(BOOL)fp12;
- (void)addSidePanel;
- (void)removeSidePanel;
- (id)initWithNibName:(id)fp8 tool:(int)fp12 viewerController:(id)fp16;
- (id)view;
- (void)setLeftHandLayout:(BOOL)fp8;
- (void)setLeftHandLayout:(BOOL)fp8 forView:(id)fp12;
- (BOOL)isLandscapeOrientation;

@end

