/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLSharingServiceViewController.h"

#import "MPAssetKeyDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class BLJournal, BLSlideshowMusicPicker, BLSlideshowStylePicker, NSArray, NSMutableDictionary, NSOperationQueue, NSString, UITableView, UIView;

@interface BLSlideshowSettingsViewController : BLSharingServiceViewController <UITableViewDelegate, UITableViewDataSource, MPAssetKeyDelegate>
{
    UITableView *m_tableView;
    NSArray *m_slideshowPhotos;
    NSMutableDictionary *m_assetDictionary;
    BLSlideshowStylePicker *m_stylePickerController;
    BLSlideshowMusicPicker *m_musicPickerController;
    BLJournal *m_journal;
    NSString *m_albumTitle;
    NSMutableDictionary *m_faces;
    NSOperationQueue *m_faceQueue;
    UIView *m_ContainerView;
    int m_selectedStyle;
    BOOL m_playMusic;
    BOOL m_useMusicLibrary;
    int m_sharer;
    BOOL m_cancellable;
}

+ (id)creationDateFromMedia:(id)fp8;
+ (BOOL)useMarimbaFadeIn:(id)fp8;
+ (id)orderedStylesIDs;
+ (id)sharedController;
- (id)albumTitle;
- (void)setJournal:(id)fp8;
- (id)journal;
- (void)setSharer:(int)fp8;
- (int)sharer;
- (void)setCancellable:(BOOL)fp8;
- (BOOL)isCancellable;
- (id)slideshowPhotos;
- (void)dealloc;
- (int)modalPresentationStyle;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (float)tableView:(id)fp8 heightForFooterInSection:(int)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)musicTitle;
- (int)musicType;
- (int)selectedSongIndex;
- (id)mediaItemsFromSongIDs;
- (void)playMusicChanged:(id)fp8;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (struct CGImage *)retainedCGImageForAssetKey:(id)fp8 andSize:(struct CGSize)fp12 orientation:(char *)fp20 thumbnailIfPossible:(BOOL)fp24 now:(BOOL)fp28;
- (struct CGImage *)retainedCGImageForAssetKey:(id)fp8 andSize:(struct CGSize)fp12 orientation:(char *)fp20;
- (id)absolutePathForStillAssetAtPath:(id)fp8 andSize:(struct CGSize)fp12;
- (id)absolutePathForAssetKey:(id)fp8 andSize:(struct CGSize)fp12;
- (id)absolutePathForAssetKey:(id)fp8;
- (void)a_share:(id)fp8;
- (void)cancel:(id)fp8;
- (void)setupSlideshowWithNewRunLoop:(id)fp8;
- (void)startSlideshow;
- (id)_createDatelineDictionary;
- (void)setSlideshowPhotos:(id)fp8;
- (void)setAlbumTitle:(id)fp8;
- (id)detectRegionsOfInterestForAssetKey:(id)fp8;
- (void)_detectFaces;
- (id)document:(int)fp8;
- (struct CGSize)requiredPopoverSize;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

