/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "MRRenderingDelegate-Protocol.h"

@class AVAudioPlayer, BLSlideshowPlayerView, MPDocument, MPMusicPlayerController, MRMarimbaLayer, UIActivityIndicatorView, UIButton, UIView, UIWindow;

@interface BLSlideshowPlayerViewController : _ACAccountTypeIdentifierTwitter <MRRenderingDelegate>
{
    MRMarimbaLayer *m_marimbaLayer;
    BLSlideshowPlayerView *m_layerView;
    MPDocument *m_currentDocument;
    UIView *m_overlayView;
    UIView *m_airplayView;
    UIButton *m_playButtonItem;
    UIButton *m_pauseButtonItem;
    UIActivityIndicatorView *m_spinner;
    UIWindow *m_externalWindow;
    int m_nextOrientation;
    float m_lastAngle;
    struct CGSize m_lastSize;
    MPMusicPlayerController *m_musicPlayerController;
    AVAudioPlayer *m_audioPlayer;
    BOOL m_hasMusic;
    int m_sharer;
    BOOL m_toolBarsAreVisible;
    BOOL m_isSetup;
}

+ (void)releaseSharedManager;
+ (BOOL)isInstantiated;
+ (id)sharedController;
- (void)setSpinner:(id)fp8;
- (id)spinner;
- (void)setAirplayView:(id)fp8;
- (id)airplayView;
- (void)setExternalWindow:(id)fp8;
- (id)externalWindow;
- (void)setToolBarsAreVisible:(BOOL)fp8;
- (BOOL)toolBarsAreVisible;
- (void)setPauseButtonItem:(id)fp8;
- (id)pauseButtonItem;
- (void)setPlayButtonItem:(id)fp8;
- (id)playButtonItem;
- (void)setOverlayView:(id)fp8;
- (id)overlayView;
- (void)setCurrentDocument:(id)fp8;
- (id)currentDocument;
- (void)setLayerView:(id)fp8;
- (id)layerView;
- (void)setMarimbaLayer:(id)fp8;
- (id)marimbaLayer;
- (void)dealloc;
- (void)cleanup;
- (void)viewDidUnload;
- (void)_gotoNextInBackground;
- (void)stepForward:(id)fp8;
- (void)_gotoPrevInBackground;
- (void)stepBack:(id)fp8;
- (void)close:(id)fp8;
- (void)_didFinishPlaying:(id)fp8;
- (void)_playInBackground;
- (void)screenDidConnect:(id)fp8;
- (void)screenDidDisconnect:(id)fp8;
- (void)toggleHUD;
- (void)_configurePlayButton:(BOOL)fp8;
- (void)pause;
- (void)animationFinished:(id)fp8 finished:(BOOL)fp12 context:(void *)fp16;
- (void)_playAfterWarmup:(id)fp8;
- (void)_pauseInBackground;
- (void)_warmupOnBackgroundThread:(id)fp8;
- (void)togglePlay:(id)fp8;
- (void)loadSlideshowWithDocument:(id)fp8 orientation:(int)fp12;
- (void)setupPlayerWithDocument:(id)fp8 mediaItems:(id)fp12 orientation:(int)fp16 sharedFrom:(int)fp20;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)startSlideshow;
- (void)viewWillAppear:(BOOL)fp8;
- (void)didReceiveMemoryWarning;
- (int)modalPresentationStyle;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidLoad;
- (int)modalTransitionStyle;

@end

