/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLDarkGradientView.h"

@class UIImageView;

@interface BLSpinner : BLDarkGradientView
{
    UIImageView *m_imageView;
    BOOL m_animating;
}

+ (id)spinner;
- (void)dealloc;
- (BOOL)isAnimating;
- (void)stopAnimating;
- (void)startAnimatingAfterDelay:(double)fp8;
- (void)startAnimating;
- (void)didMoveToSuperview;
- (void)fadeIn;
- (id)init;
- (id)splitImage:(id)fp8;

@end

