/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLStraightenDialAccessibility.h"

@interface BLStraightenDialAccessibility (SafeCategory)
- (unsigned long long)accessibilityTraits;
- (void)accessibilityDecrement;
- (void)accessibilityIncrement;
- (void)_axAdjust:(BOOL)fp8;
- (void)setValue:(float)fp8;
- (id)accessibilityValue;
- (void)tapPiece:(id)fp8;
- (id)accessibilityLabel;
- (BOOL)isAccessibilityElement;
@end

