/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class BLTextView;

@interface BLTextContainer : _ACAccountTypeIdentifierTwitter
{
    BLTextView *m_textView;
}

- (void)setTextView:(id)fp8;
- (id)textView;
- (void)drawRect:(struct CGRect)fp8;

@end

