/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIImage, UIView;

@interface BLTextMagnifyView : _ACAccountTypeIdentifierTwitter
{
    UIView *m_sourceView;
    UIView *m_secondarySourceView;
    struct CGPoint m_secondarySourceViewOffset;
    UIImage *m_mask;
    UIImage *m_overlay;
    UIImage *m_underlay;
    struct CGPoint m_point;
    float m_scale;
    float m_touchVerticalOffset;
    float m_textHeight;
    int m_orientation;
    float m_angleOfRotation;
}

- (void)setMaskImage:(id)fp8;
- (id)maskImage;
- (void)setUnderlayImage:(id)fp8;
- (id)underlayImage;
- (void)setOverlayImage:(id)fp8;
- (id)overlayImage;
- (void)setMagnifyScale:(float)fp8;
- (float)magnifyScale;
- (void)drawRect:(struct CGRect)fp8;
- (void)showLoupeForPoint:(struct CGPoint)fp8 heightOffset:(float)fp16 inView:(id)fp20 withSecondaryView:(id)fp24;
- (struct CGPoint)pointForScaleAnimation;
- (void)updateForOrientation;
- (void)hideLoupe;
- (void)snapshotSourceView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

