/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class BLTextContainer, BLTextView, UIColor;

@interface BLTextSelectionView : _ACAccountTypeIdentifierTwitter
{
    BLTextView *m_textView;
    BLTextContainer *textContainerView;
    struct __CTFrame *m_CTFrame;
    UIColor *m_selectionColor;
    UIColor *m_spellingColor;
    UIColor *m_endCapColor;
    BLTextContainer *m_textContainerView;
}

- (void)setEndCapColor:(id)fp8;
- (id)endCapColor;
- (void)setSpellingColor:(id)fp8;
- (id)spellingColor;
- (void)setSelectionColor:(id)fp8;
- (id)selectionColor;
- (void)setCTFrame:(struct __CTFrame *)fp8;
- (struct __CTFrame *)CTFrame;
- (void)setTextContainerView:(id)fp8;
- (id)textContainerView;
- (void)setTextView:(id)fp8;
- (id)textView;
- (void)drawRect:(struct CGRect)fp8;
- (void)drawSpellingErrors;
- (void)drawRangeAsSelection:(struct _NSRange)fp8 isMarkedText:(BOOL)fp16;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

