/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIImageView;

@interface BLThumbView : _ACAccountTypeIdentifierTwitter
{
    UIImageView *m_imageView;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (id)image;
- (void)setImage:(id)fp8;

@end

