/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class BLGridController, BLMedia, BLSelectionFrame, BLThumbView, UIImageView, UILabel, UISwipeGestureRecognizer, UIView;

@interface BLThumbBorderView : _ACAccountTypeIdentifierTwitter <UIGestureRecognizerDelegate>
{
    BLMedia *m_photo;
    unsigned int m_requestID;
    BLThumbView *m_thumbView;
    BOOL m_rotated;
    BLSelectionFrame *m_selectionFrame;
    BLGridController *m_controller;
    UIView *m_owner;
    UIImageView *m_badges[4];
    UILabel *m_caption;
    UIView *m_captionBackground;
    UIImageView *m_markedBadge;
    UIImageView *m_videoBadge;
    UIImageView *m_rawBadge;
    UIImageView *m_inJournalBadge;
    UIView *m_blackOverlay;
    double m_lastTapTime;
    BOOL m_leftHandLayout;
    UISwipeGestureRecognizer *m_swipeRecognizer;
}

- (BOOL)leftHandLayout;
- (void)setOwner:(id)fp8;
- (id)owner;
- (BOOL)rotated;
- (id)photo;
- (void)dealloc;
- (void)removeFromSuperview;
- (void)setLeftHandLayout:(BOOL)fp8;
- (void)didMoveToSuperview;
- (void)willMoveToSuperview:(id)fp8;
- (void)updateRecognizer:(BOOL)fp8;
- (void)userSwiped:(id)fp8;
- (void)flickrLoginStatusChanged:(id)fp8;
- (void)facebookLoginStatusChanged:(id)fp8;
- (void)photoImageChanged:(id)fp8;
- (void)setPhoto:(id)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)saveToThumbnailCache:(id)fp8 forKey:(id)fp12;
- (void)updateMarkedBadge;
- (void)updateCaption;
- (void)updateBadges;
- (void)updateInJournalBadgeTo:(BOOL)fp8;
- (void)updateVideoBadgeTo:(BOOL)fp8;
- (void)updateRAWBadgeTo:(BOOL)fp8;
- (void)updateBadgesTo:(id)fp8;
- (void)updateForMarkingLimit:(id)fp8;
- (void)updateForMarkingLimitAnimated:(BOOL)fp8;
- (void)selectionChanged;
- (void)moveToFrontIfSelected;
- (void)setRotated:(BOOL)fp8;
- (id)initWithFrame:(struct CGRect)fp8 rotate:(BOOL)fp24 controller:(id)fp28;
- (BOOL)gestureRecognizer:(id)fp8 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)fp12;
- (void)userLongPressed:(id)fp8;
- (void)userTapped;

@end

