/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class UIImage;

@interface BLTiledImageView : _ACAccountTypeIdentifierTwitter
{
    UIImage *m_image;
}

+ (Class)layerClass;
- (id)image;
- (void)dealloc;
- (void)drawLayer:(id)fp8 inContext:(struct CGContext *)fp12;
- (void)drawRect:(struct CGRect)fp8;
- (void)setImage:(id)fp8;

@end

