/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface BLTripItAccess : _ACAccountTypeIdentifierTwitter
{
    BOOL m_hasCachedLoginState;
    int m_cachedLoginState;
}

+ (id)sharedInstance;
- (void)setCachedLoginState:(int)fp8;
- (int)cachedLoginState;
- (void)setHasCachedLoginState:(BOOL)fp8;
- (BOOL)hasCachedLoginState;
- (void)performPOSTRequestWithURL:(id)fp8 parameters:(id)fp12 andCompletionBlock:(id)fp(null);
- (void)performGETRequestWithURL:(id)fp8 andCompletionBlock:(id)fp(null);
- (id)accessSecret;
- (id)accessToken;
- (void)requestPastTripsWithCompletionBlock:(id)fp(null);
- (void)requestUpcomingTripsWithCompletionBlock:(id)fp(null);
- (void)checkLoggedInWithCompletionBlock:(id)fp(null);
- (void)logout;
- (void)authenticateWithViewController:(id)fp8 andCompletionBlock:(id)fp(null);
- (id)consumerSecret;
- (id)consumerKey;
- (void)dealloc;
- (id)init;

@end

