/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSArray, NSMutableDictionary, NSPredicate, NSURL;

@interface BLUbiquityProgressWatcher : _ACAccountTypeIdentifierTwitter
{
    NSURL *m_url;
    float m_progress;
    NSMutableDictionary *m_statistics;
    BOOL m_queuedNotify;
    BOOL m_notifying;
    NSPredicate *m_predicate;
    NSArray *m_scopes;
}

- (float)progress;
- (void)metadataUpdated:(id)fp8;
- (void)metadataFinished:(id)fp8;
- (void)notify;
- (void)stopObservingChanges;
- (void)startObservingChanges;
- (void)initializeStatisticsWithCompletionBlock:(id)fp(null);
- (void)dealloc;
- (id)initWithURL:(id)fp8 predicate:(id)fp12 andScopes:(id)fp16;

@end

