/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLUIViewAccessibility.h"

@interface BLUIViewAccessibility (SafeCategory)
- (void)accessibilityDecrement;
- (void)accessibilityIncrement;
- (void)_axModifyValue:(BOOL)fp8;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityLabel;
- (BOOL)_blaxIsJournalThemeChooser;
@end

