/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLUIImageViewAccessibility.h"

@interface BLUIImageViewAccessibility (SafeCategory)
- (void)accessibilityIncrement;
- (void)accessibilityDecrement;
- (void)_axImageModifyValue:(BOOL)fp8;
- (id)accessibilityValue;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (void)_accessibilityScrollToVisible;
- (BOOL)_accessibilityShouldUseViewHierarchyForFindingScrollParent;
- (BOOL)isAccessibilityElement;
- (BOOL)_axIsHistogramChanger;
- (id)_axHistorgramParent;
@end

