/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLUIImageAccessibility.h"

@interface BLUIImageAccessibility (SafeCategory)
- (id)bezeledImageWithShadowRed:(float)fp8 green:(float)fp12 blue:(float)fp16 alpha:(float)fp20 fillRed:(float)fp24 green:(float)fp28 blue:(float)fp32 alpha:(float)fp36 drawShadow:(BOOL)fp40;
@end

