/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLViewerControllerAccessibility.h"

@interface BLViewerControllerAccessibility (SafeCategory)
- (void)updateToolButtons;
- (void)a_showTools:(id)fp8;
- (void)a_hideTools:(id)fp8;
- (void)moveToolsOut;
- (void)slideToolsIn;
- (void)slideToolSelectorOut;
- (void)a_previousPhoto:(id)fp8;
- (void)a_nextPhoto:(id)fp8;
- (void)rotatePhoto:(id)fp8 by90DegreeTurnsClockwise:(int)fp12 forUndo:(BOOL)fp16 scrollView:(id)fp20 viewerItemWrapper:(id)fp24;
@end

