/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLViewerController.h"

@class BLBarView, BLLeftHandView, UIPanGestureRecognizer, UISwipeGestureRecognizer, UIView;

@interface BLViewerControllerLandscape : BLViewerController
{
    BLLeftHandView *m_sidePanel;
    BLBarView *m_sidePanelHeader;
    UIView *m_leftSwipeArea;
    UIView *m_rightSwipeArea;
    UIView *m_sidePanelResizeParent;
    UIPanGestureRecognizer *m_sidePanelRecognizer;
    UIPanGestureRecognizer *m_panelSizeRecognizer;
    UISwipeGestureRecognizer *m_swipeLeftRecognizer;
    UISwipeGestureRecognizer *m_swipeRightRecognizer;
}

- (void)setM_rightSwipeArea:(id)fp8;
- (id)m_rightSwipeArea;
- (void)setM_leftSwipeArea:(id)fp8;
- (id)m_leftSwipeArea;
- (void)setM_sidePanelHeader:(id)fp8;
- (id)m_sidePanelHeader;
- (void)setM_sidePanel:(id)fp8;
- (id)m_sidePanel;
- (void)setView:(id)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)transferComplete;
- (BOOL)transferrableView:(id)fp8;
- (void)setupPanels;
- (void)setViewerMode:(int)fp8 animated:(BOOL)fp12;
- (void)resizeSidePanel:(id)fp8;
- (void)moveSidePanelHeader:(id)fp8;
- (void)restoreSidePanel;
- (void)setLeftHandLayout:(BOOL)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)updateRecognizers;
- (void)toggleSidePanelSwipe:(id)fp8;
- (void)toggleSidePanel:(BOOL)fp8;
- (void)changeShowGrid:(id)fp8;
- (void)updateBarStates;
- (void)setSidePanelLeftHandLayout:(BOOL)fp8;
- (BOOL)gestureRecognizerShouldBegin:(id)fp8;

@end

