/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLViewerController.h"

@interface BLViewerController (BLViewerControllerMovieAdditions)
- (void)pause;
- (void)stop;
- (void)playPause:(id)fp8;
- (void)loadMovieFromFileURL:(id)fp8 forPage:(int)fp12;
- (id)currentPlayer:(id)fp8;
- (id)currentPlayer;
@end

