/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

struct CATransform3D {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
    float _field7;
    float _field8;
    float _field9;
    float _field10;
    float _field11;
    float _field12;
    float _field13;
    float _field14;
    float _field15;
    float _field16;
};

struct CGAffineTransform {
    float a;
    float b;
    float c;
    float d;
    float tx;
    float ty;
};

struct CGColor;

struct CGColorSpace;

struct CGContext;

struct CGImage;

struct CGImageSource;

struct CGPoint {
    float x;
    float y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    float width;
    float height;
};

struct FunctionInterpreter<double> {
    void **_field1;
    struct Parser<double> *_field2;
    struct Parser<double> *_field3;
    struct ParserVariable<double> *_field4;
    int _field5;
};

struct FunctionInterpreter<float> {
    void **_field1;
    struct Parser<float> *_field2;
    struct Parser<float> *_field3;
    struct ParserVariable<float> *_field4;
    int _field5;
};

struct Parser<double>;

struct Parser<float>;

struct ParserVariable<double>;

struct ParserVariable<float>;

struct UIEdgeInsets {
    float top;
    float left;
    float bottom;
    float right;
};

struct _NSRange {
    unsigned int location;
    unsigned int length;
};

struct _NSZone;

struct __CFData;

struct __CFDictionary;

struct __CFString;

struct __CTFont;

struct __CTFrame;

struct __CVBuffer;

struct __SCNetworkReachability;

struct __sFILE {
    char *_field1;
    int _field2;
    int _field3;
    short _field4;
    short _field5;
    struct __sbuf _field6;
    int _field7;
    void *_field8;
    void *_field9;
    void *_field10;
    void *_field11;
    void *_field12;
    struct __sbuf _field13;
    struct __sFILEX *_field14;
    int _field15;
    unsigned char _field16[3];
    unsigned char _field17[1];
    struct __sbuf _field18;
    int _field19;
    long long _field20;
};

struct __sFILEX;

struct __sbuf {
    char *_field1;
    int _field2;
};

struct __zFlags {
    unsigned int providerSuppliesContents:1;
    unsigned int providerSuppliesStreams:1;
    unsigned int providerSuppliesProperties:1;
    unsigned int noContentsCaching:1;
    unsigned int fileOpen:1;
    unsigned int reserved:27;
};

struct dispatch_queue_s;

struct objc_method;

struct sqlite3;

struct sqlite3_stmt;

typedef struct {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
    float _field7;
    float _field8;
    float _field9;
    float _field10;
    float _field11;
    float _field12;
    float _field13[16];
    float _field14[16];
    float _field15[16];
    char _field16;
    char _field17;
    char _field18;
    char _field19;
    char _field20;
} CDAnonymousStruct1;

typedef struct {
    unsigned char blue;
    unsigned char green;
    unsigned char red;
    unsigned char alpha;
} CDAnonymousStruct2;

typedef struct {
    Class _field1;
    id _field2;
    id _field3;
} CDAnonymousStruct3;

typedef struct {
    int _field1;
    int _field2;
} CDAnonymousStruct4;

typedef struct {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
} CDAnonymousStruct5;

typedef struct {
    char _field1;
} CDAnonymousStruct6;

typedef struct {
    float xOffset;
    float yOffset;
    float scale;
} CDAnonymousStruct7;

typedef struct {
    id _field1;
    char _field2;
} CDAnonymousStruct8;

typedef struct {
    struct {
        float _field1;
        float _field2;
        float _field3;
        float _field4;
    } _field1;
    struct {
        float _field1;
        float _field2;
        float _field3;
        float _field4;
    } _field2;
    struct {
        float _field1;
        float _field2;
        float _field3;
        float _field4;
    } _field3;
} CDAnonymousStruct9;

typedef struct {
    double _field1;
    double _field2;
} CDAnonymousStruct10;

typedef struct {
    struct CGPoint _field1[2];
    float _field2;
    char _field3;
} CDAnonymousStruct11;

typedef struct {
    unsigned char length;
    float v[4];
} CDAnonymousStruct12;

typedef struct {
    struct CGPoint _field1;
    struct CGPoint _field2;
    float *_field3;
    float _field4;
    int _field5;
    int _field6;
    float _field7;
    float _field8;
    float _field9;
    float _field10;
    float _field11;
    float _field12;
    struct CGPoint _field13;
    struct CGPoint _field14;
    float _field15;
    int _field16;
    int _field17;
    int _field18;
    int _field19;
} CDAnonymousStruct13;

typedef struct {
    int _field1;
    long _field2;
    long _field3;
} CDAnonymousStruct14;

