/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "NSDiscardableContent-Protocol.h"

@interface DiscardableCFData : _ACAccountTypeIdentifierTwitter <NSDiscardableContent>
{
    struct __CFData *m_data;
    unsigned int m_accessCount;
}

+ (id)discardableCFData:(struct __CFData *)fp8;
- (void)setAccessCount:(unsigned int)fp8;
- (unsigned int)accessCount;
- (void)setData:(struct __CFData *)fp8;
- (struct __CFData *)data;
- (BOOL)isContentDiscarded;
- (void)discardContentIfPossible;
- (void)endContentAccess;
- (BOOL)beginContentAccess;
- (void)dealloc;
- (id)initWithCFData:(struct __CFData *)fp8;

@end

