/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "FBLoginDialogDelegate-Protocol.h"
#import "FBRequestDelegate-Protocol.h"

@class FBDialog, NSArray, NSDate, NSMutableSet, NSString;

@interface Facebook : _ACAccountTypeIdentifierTwitter <FBLoginDialogDelegate, FBRequestDelegate>
{
    NSString *_accessToken;
    NSDate *_expirationDate;
    id <FBSessionDelegate> _sessionDelegate;
    NSMutableSet *_requests;
    FBDialog *_loginDialog;
    FBDialog *_fbDialog;
    NSString *_appId;
    NSString *_urlSchemeSuffix;
    NSArray *_permissions;
    BOOL _isExtendingAccessToken;
    NSDate *_lastAccessTokenUpdate;
}

- (void)setAppId:(id)fp8;
- (id)appId;
- (void)setUrlSchemeSuffix:(id)fp8;
- (id)urlSchemeSuffix;
- (void)setPermissions:(id)fp8;
- (id)permissions;
- (void)setSessionDelegate:(id)fp8;
- (id)sessionDelegate;
- (void)setExpirationDate:(id)fp8;
- (id)expirationDate;
- (void)setAccessToken:(id)fp8;
- (id)accessToken;
- (void)requestLoading:(id)fp8;
- (void)request:(id)fp8 didReceiveResponse:(id)fp12;
- (void)request:(id)fp8 didLoadRawResponse:(id)fp12;
- (void)request:(id)fp8 didLoad:(id)fp12;
- (void)request:(id)fp8 didFailWithError:(id)fp12;
- (void)fbDialogNotLogin:(BOOL)fp8;
- (void)fbDialogLogin:(id)fp8 expirationDate:(id)fp12;
- (BOOL)isSessionValid;
- (void)dialog:(id)fp8 andParams:(id)fp12 andDelegate:(id)fp16;
- (void)dialog:(id)fp8 andDelegate:(id)fp12;
- (id)requestWithGraphPath:(id)fp8 andParams:(id)fp12 andHttpMethod:(id)fp16 andDelegate:(id)fp20;
- (id)requestWithGraphPath:(id)fp8 andParams:(id)fp12 andDelegate:(id)fp16;
- (id)requestWithGraphPath:(id)fp8 andDelegate:(id)fp12;
- (id)requestWithMethodName:(id)fp8 andParams:(id)fp12 andHttpMethod:(id)fp16 andDelegate:(id)fp20;
- (id)requestWithParams:(id)fp8 andDelegate:(id)fp12;
- (void)logout;
- (BOOL)handleOpenURL:(id)fp8;
- (BOOL)shouldExtendAccessToken;
- (void)extendAccessTokenIfNeeded;
- (void)extendAccessToken;
- (void)authorize:(id)fp8;
- (id)parseURLParams:(id)fp8;
- (void)authorizeWithFBAppAuth:(BOOL)fp8 safariAuth:(BOOL)fp12;
- (id)getOwnBaseUrl;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (id)openUrl:(id)fp8 params:(id)fp12 httpMethod:(id)fp16 delegate:(id)fp20;
- (void)invalidateSession;
- (void)dealloc;
- (id)initWithAppId:(id)fp8 urlSchemeSuffix:(id)fp12 andDelegate:(id)fp16;
- (id)initWithAppId:(id)fp8 andDelegate:(id)fp12;

@end

