/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol FBLoginDialogDelegate <NSObject>
- (void)fbDialogNotLogin:(BOOL)fp8;
- (void)fbDialogLogin:(id)fp8 expirationDate:(id)fp12;
@end

