/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FBDialog.h"

@interface FBLoginDialog : FBDialog
{
    id <FBLoginDialogDelegate> _loginDelegate;
}

- (void)webView:(id)fp8 didFailLoadWithError:(id)fp12;
- (void)dialogDidCancel:(id)fp8;
- (void)dialogDidSucceed:(id)fp8;
- (id)initWithURL:(id)fp8 loginParams:(id)fp12 delegate:(id)fp16;

@end

