/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSData, NSDictionary, NSManagedObject, NSMutableDictionary, NSString, NSURL;

@interface HLHelpBundle : _ACAccountTypeIdentifierTwitter
{
    NSManagedObject *representedObject;
    NSString *bundleIdentifier;
    NSString *bundleVersion;
    NSString *bundlePlatform;
    NSURL *bundleBaseURL;
    NSDictionary *availableLanguages;
    NSString *preferredLanguage;
    NSData *stylesheet;
    NSString *cachedStylesheetPath;
    NSManagedObject *_contentObject;
    BOOL _isLoaded;
    NSString *_lprojHint;
    NSMutableDictionary *_allTopics;
}

+ (void)loadLocalizedStrings;
+ (id)localizedStringForKey:(id)fp8 value:(id)fp12 language:(id)fp16;
+ (id)managedObjectContext;
+ (id)managedObjectModel;
+ (id)persistentStoreCoordinator;
+ (id)bundleForURL:(id)fp8 identifier:(id)fp12 version:(id)fp16 platform:(id)fp20;
+ (id)bundleForApplicationVersion:(id)fp8 platform:(id)fp12;
+ (id)bundleForApplicationForPlatform:(id)fp8;
+ (id)bundleForIdentifier:(id)fp8 version:(id)fp12 platform:(id)fp16;
- (void)setCachedStylesheetPath:(id)fp8;
- (id)cachedStylesheetPath;
- (void)setStylesheet:(id)fp8;
- (id)stylesheet;
- (void)setPreferredLanguage:(id)fp8;
- (id)preferredLanguage;
- (void)setAvailableLanguages:(id)fp8;
- (id)availableLanguages;
- (void)setBundleBaseURL:(id)fp8;
- (id)bundleBaseURL;
- (void)setBundlePlatform:(id)fp8;
- (id)bundlePlatform;
- (void)setBundleVersion:(id)fp8;
- (id)bundleVersion;
- (void)setBundleIdentifier:(id)fp8;
- (id)bundleIdentifier;
- (void)setRepresentedObject:(id)fp8;
- (id)representedObject;
- (void)dealloc;
- (unsigned int)characterDirection;
- (id)flattenHTML:(id)fp8;
- (id)filteredTopicsUsingPredicate:(id)fp8 forLanguage:(id)fp12;
- (id)filteredTopicsUsingPredicate:(id)fp8;
- (id)metadataForLanguage:(id)fp8;
- (id)topicWithIdentifier:(id)fp8 forLanguage:(id)fp12;
- (id)topicWithIdentifier:(id)fp8;
- (id)allTopicsForLanguage:(id)fp8;
- (id)allTopics;
- (id)flattenTopics:(id)fp8;
- (id)contentDictionaryForLanguage:(id)fp8;
- (id)contentDataForLanguage:(id)fp8;
- (id)contentVersionForLanguage:(id)fp8;
- (id)contentBaseURLForLanguage:(id)fp8;
- (id)contentObjectForLanguage:(id)fp8;
- (void)loadRemoteStylesheet;
- (void)loadLocalStylesheet;
- (void)loadStylesheet;
- (void)loadRemoteLocalizations;
- (void)loadLocalLocalizations;
- (id)bundleResourceForURL:(id)fp8;
- (void)loadBundleResources;
- (BOOL)loadBundle;
- (id)initWithURL:(id)fp8 identifier:(id)fp12 version:(id)fp16 platform:(id)fp20;
- (id)initWithApplicationVersion:(id)fp8 platform:(id)fp12;
- (id)initWithApplicationForPlatform:(id)fp8;
- (id)initWithIdentifier:(id)fp8 version:(id)fp12 platform:(id)fp16;
- (id)init;
- (void)setLastScrollY:(id)fp8;
- (id)lastScrollY;
- (void)setLastTopicIdentifier:(id)fp8;
- (id)lastTopicIdentifier;
- (id)metadata;
- (id)contentDictionary;
- (id)contentData;
- (id)contentVersion;
- (id)contentBaseURL;
- (id)contentObject;

@end

