/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSDictionary, NSString;

@interface HLHelpConfig : _ACAccountTypeIdentifierTwitter
{
    NSString *_identifier;
    NSString *md5Identifer;
    BOOL debug;
    NSDictionary *configDictionary;
}

+ (id)helpConfigForApplicationDebug:(BOOL)fp8;
+ (id)helpConfigForApplication;
+ (id)helpConfigForBundleIdentifier:(id)fp8 debug:(BOOL)fp12;
+ (id)helpConfigForBundleIdentifier:(id)fp8;
- (void)setDebug:(BOOL)fp8;
- (BOOL)debug;
- (id)identifier;
- (void)dealloc;
- (id)defaultURLForPlatform:(id)fp8;
- (id)URLForVersion:(id)fp8 platform:(id)fp12;
- (id)configurationForVersion:(id)fp8;
- (void)loadConfig;
- (id)initWithBundleIdentifier:(id)fp8;
- (id)defaultVersion;
- (id)description;
- (id)versions;
- (id)configFilename;
- (id)configURL;
- (id)md5Identifier;

@end

