/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class HLHelpBundle, NSString, UIColor, UIViewController;

@interface HLHelpLibraryCoordinator : _ACAccountTypeIdentifierTwitter
{
    BOOL debug;
    id delegate;
    HLHelpBundle *helpBundle;
    NSString *presentationMethod;
    UIViewController *rootViewController;
    UIColor *tintColor;
    id doneButtonTarget;
    SEL doneButtonAction;
}

+ (BOOL)currentDeviceIsiPad;
+ (id)coordinatorForApplication;
+ (id)coordinatorForHelpBundle:(id)fp8;
- (void)setDoneButtonAction:(SEL)fp8;
- (SEL)doneButtonAction;
- (void)setDoneButtonTarget:(id)fp8;
- (id)doneButtonTarget;
- (void)setRootViewController:(id)fp8;
- (id)rootViewController;
- (void)setTintColor:(id)fp8;
- (id)tintColor;
- (void)setHelpBundle:(id)fp8;
- (id)helpBundle;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setDebug:(BOOL)fp8;
- (BOOL)debug;
- (void)dealloc;
- (void)showHelp:(id)fp8;
- (id)viewControllersStartingAtTopicIdentifier:(id)fp8;
- (id)viewControllerForTopicIdentifier:(id)fp8;
- (void)presentInlineHelp:(id)fp8 inNavigationController:(id)fp12;
- (void)presentModalHelp:(id)fp8 inViewController:(id)fp12;
- (id)doneButton;
- (void)hideHelp:(id)fp8;
- (void)didHideHelp:(id)fp8;
- (void)willHideHelp:(id)fp8;
- (void)didShowHelp:(id)fp8;
- (void)willShowHelp:(id)fp8;
- (id)initWithHelpBundle:(id)fp8;

@end

