/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSDictionary, NSMutableArray, NSThread, UISearchBar;

@interface HLTopicMapViewController : _ACAccountTypeIdentifierTwitter <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate>
{
    NSMutableArray *searchResults;
    id coordinator;
    NSDictionary *representedObject;
    NSArray *metaSection;
    UISearchBar *searchBar;
    NSThread *searchThread;
}

+ (id)topicMapViewController;
- (void)setSearchBar:(id)fp8;
- (id)searchBar;
- (void)setSearchResults:(id)fp8;
- (id)searchResults;
- (void)setCoordinator:(id)fp8;
- (id)coordinator;
- (void)setRepresentedObject:(id)fp8;
- (id)representedObject;
- (void)searchBarCancelButtonClicked:(id)fp8;
- (void)searchBarSearchButtonClicked:(id)fp8;
- (void)searchBarTextDidEndEditing:(id)fp8;
- (void)searchBarTextDidBeginEditing:(id)fp8;
- (void)searchBar:(id)fp8 textDidChange:(id)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 titleForFooterInSection:(int)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (id)emptyCellForRowAtIndexPath:(id)fp8;
- (id)showVersionCellForRowAtIndexPath:(id)fp8;
- (id)changeLanguageCellForRowAtIndexPath:(id)fp8;
- (id)copyrightCellForRowAtIndexPath:(id)fp8;
- (id)searchResultCellForRowAtIndexPath:(id)fp8;
- (id)navigationCellForRowAtIndexPath:(id)fp8;
- (id)topicsFromArray:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)languageDidChange:(id)fp8;
- (void)didReceiveMemoryWarning;
- (BOOL)hasSearchResults;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (id)helpBundle;

@end

