/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MCAction.h"

@class NSMutableArray;

@interface MCActionGroup : MCAction
{
    NSMutableArray *_actions;
}

+ (id)actionGroup;
- (void)_copySelfToSnapshot:(id)fp8;
- (void)moveActionsAtIndices:(id)fp8 toIndex:(unsigned int)fp12;
- (void)removeAllActions;
- (void)removeActionsAtIndices:(id)fp8;
- (void)insertActions:(id)fp8 atIndex:(unsigned int)fp12;
- (void)insertAction:(id)fp8 atIndex:(unsigned int)fp12;
- (void)addActions:(id)fp8;
- (void)addAction:(id)fp8;
- (id)actionAtIndex:(unsigned int)fp8;
- (unsigned int)countOfActions;
- (id)actions;
- (id)imprint;
- (void)demolish;
- (id)initWithImprint:(id)fp8;
- (id)init;

@end

