/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MCAction.h"

@class NSString;

@interface MCActionTrigger : MCAction
{
    NSString *_actionKey;
}

+ (id)actionTriggerForTargetPlugObjectID:(id)fp8 withActionKey:(id)fp12;
- (void)setActionKey:(id)fp8;
- (id)actionKey;
- (void)_copySelfToSnapshot:(id)fp8;
- (id)imprint;
- (void)demolish;
- (id)initWithImprint:(id)fp8;

@end

