/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MCAnimationKeyframe.h"

@interface MCAnimationKeyframe1D : MCAnimationKeyframe
{
    float mValue;
}

+ (id)keyframeWithScalar:(float)fp8 atTime:(double)fp12 offsetKind:(int)fp20;
+ (id)keyframeWithScalar:(float)fp8 atTime:(double)fp12;
- (float)value;
- (void)_copySelfToSnapshot:(id)fp8;
- (id)description;
- (void)setValue:(float)fp8;
- (id)imprint;
- (id)initWithImprint:(id)fp8;

@end

