/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MCObjectLight.h"

@class NSString;

@interface MCAnimationPath : MCObjectLight
{
    NSString *mKey;
    BOOL mIsTriggered;
}

+ (id)animationPathWithKey:(id)fp8;
- (void)setIsTriggered:(BOOL)fp8;
- (BOOL)isTriggered;
- (void)setKey:(id)fp8;
- (id)key;
- (void)_copySelfToSnapshot:(id)fp8;
- (id)imprint;
- (void)demolish;
- (id)initWithImprint:(id)fp8;

@end

