/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MCAnimationPath.h"

@class NSArray, NSMutableSet;

@interface MCAnimationPathKeyframed : MCAnimationPath
{
    NSMutableSet *mKeyframes;
    NSArray *mCachedOrderedKeyframes;
}

+ (double)timeForKeyframe:(id)fp8 inPlug:(id)fp12;
+ (id)animationPathWithKey:(id)fp8;
+ (id)keyPathsForValuesAffectingValueForKey:(id)fp8;
- (void)_copySelfToSnapshot:(id)fp8;
- (id)description;
- (void)removeAllKeyframes;
- (void)removeKeyframe:(id)fp8;
- (void)addKeyframe:(id)fp8;
- (id)createKeyframeWithVector:(CDAnonymousStruct12)fp8 atTime:(double)fp28 offsetKind:(int)fp36;
- (id)createKeyframeWithVector:(CDAnonymousStruct12)fp8 atTime:(double)fp28;
- (id)createKeyframeWithPoint:(struct CGPoint)fp8 atTime:(double)fp16 offsetKind:(int)fp24;
- (id)createKeyframeWithPoint:(struct CGPoint)fp8 atTime:(double)fp16;
- (id)createKeyframeWithFunction:(id)fp8 atTime:(double)fp12 offsetKind:(int)fp20 forDuration:(double)fp24;
- (id)createKeyframeWithScalar:(float)fp8 atTime:(double)fp12 offsetKind:(int)fp20;
- (id)createKeyframeWithScalar:(float)fp8 atTime:(double)fp12;
- (id)orderedKeyframesInPlug:(id)fp8;
- (unsigned int)countOfKeyframes;
- (id)keyframes;
- (id)imprint;
- (void)demolish;
- (id)initWithImprint:(id)fp8;
- (id)init;

@end

