/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MCAnimationPath.h"

@interface MCAnimationPathPhysics : MCAnimationPath
{
    float _staticFriction;
    float _kineticFriction;
    float _skinFriction;
}

- (void)setSkinFriction:(float)fp8;
- (float)skinFriction;
- (void)setKineticFriction:(float)fp8;
- (float)kineticFriction;
- (void)setStaticFriction:(float)fp8;
- (float)staticFriction;
- (void)_copySelfToSnapshot:(id)fp8;
- (id)imprint;
- (id)initWithImprint:(id)fp8;

@end

