/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MCObject.h"

@class NSMutableSet, NSString;

@interface MCAsset : MCObject
{
    NSString *mPath;
    NSMutableSet *mTexts;
}

- (void)setPath:(id)fp8;
- (id)path;
- (void)_copySelfToSnapshot:(id)fp8;
- (void)forgetText:(id)fp8;
- (void)learnText:(id)fp8;
- (BOOL)isInUse;
- (id)imprint;
- (void)demolish;
- (id)initWithImprint:(id)fp8 andMontage:(id)fp12;

@end

