/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MCObject.h"

@class MCContainer, NSArray, NSMutableSet;

@interface MCAudioPlaylist : MCObject
{
    NSMutableSet *mSongs;
    NSArray *mCachedOrderedSongs;
    float mVolume;
    double mFadeInDuration;
    double mFadeOutDuration;
    float mDuckLevel;
    double mDuckInDuration;
    double mDuckOutDuration;
    MCContainer *mContainer;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)fp8;
- (void)setContainer:(id)fp8;
- (id)container;
- (void)setDuckOutDuration:(double)fp8;
- (double)duckOutDuration;
- (void)setDuckInDuration:(double)fp8;
- (double)duckInDuration;
- (void)setDuckLevel:(float)fp8;
- (float)duckLevel;
- (void)setFadeOutDuration:(double)fp8;
- (double)fadeOutDuration;
- (void)setFadeInDuration:(double)fp8;
- (double)fadeInDuration;
- (void)setVolume:(float)fp8;
- (float)volume;
- (id)orderedSongs;
- (void)moveSongsAtIndices:(id)fp8 toIndex:(unsigned int)fp12;
- (void)removeAllSongs;
- (void)removeSongsAtIndices:(id)fp8;
- (id)insertSongsForAssets:(id)fp8 atIndex:(unsigned int)fp12;
- (id)insertSongForAsset:(id)fp8 atIndex:(unsigned int)fp12;
- (id)addSongsForAssets:(id)fp8;
- (id)addSongForAsset:(id)fp8;
- (id)songAtIndex:(unsigned int)fp8;
- (unsigned int)countOfSongs;
- (id)songs;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (id)imprint;
- (void)demolish;
- (id)initWithImprint:(id)fp8 andMontage:(id)fp12;
- (id)init;

@end

