/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MCContainer.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface MCContainerEffect : MCContainer
{
    NSMutableArray *mSlides;
    NSMutableArray *mTexts;
    NSMutableDictionary *mActions;
    NSString *mEffectID;
    NSMutableDictionary *mEffectAttributes;
    BOOL mIsLive;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)fp8;
- (void)setIsLive:(BOOL)fp8;
- (BOOL)isLive;
- (void)setEffectID:(id)fp8;
- (id)effectID;
- (void)setEffectAttributes:(id)fp8;
- (id)effectAttributes;
- (void)setEffectAttribute:(id)fp8 forKey:(id)fp12;
- (id)effectAttributeForKey:(id)fp8;
- (void)moveTextsAtIndices:(id)fp8 toIndex:(unsigned int)fp12;
- (void)removeAllTexts;
- (void)removeTextsAtIndices:(id)fp8;
- (id)insertTextsForAssets:(id)fp8 andKey:(id)fp12 atIndex:(unsigned int)fp16;
- (id)insertTextForAsset:(id)fp8 andKey:(id)fp12 atIndex:(unsigned int)fp16;
- (id)insertTextsForAttributedStrings:(id)fp8 atIndex:(unsigned int)fp12;
- (id)insertTextForAttributedString:(id)fp8 atIndex:(unsigned int)fp12;
- (id)addTextsForAssets:(id)fp8 andKey:(id)fp12;
- (id)addTextForAsset:(id)fp8 andKey:(id)fp12;
- (id)addTextsForAttributedStrings:(id)fp8;
- (id)addTextForAttributedString:(id)fp8;
- (id)textAtIndex:(unsigned int)fp8;
- (unsigned int)nextAvailableTextIndex;
- (unsigned int)countOfTexts;
- (id)orderedTexts;
- (id)texts;
- (void)moveSlidesAtIndices:(id)fp8 toIndex:(unsigned int)fp12;
- (void)removeAllSlides;
- (void)removeSlidesAtIndices:(id)fp8;
- (id)insertSlideForContainer:(id)fp8 atIndex:(unsigned int)fp12;
- (id)addSlideForContainer:(id)fp8;
- (id)insertSlidesForAssets:(id)fp8 atIndex:(unsigned int)fp12;
- (id)insertSlideForAsset:(id)fp8 atIndex:(unsigned int)fp12;
- (id)addSlidesForAssets:(id)fp8;
- (id)addSlideForAsset:(id)fp8;
- (id)insertSlideAtIndex:(int)fp8;
- (id)addSlides:(int)fp8;
- (id)addSlide;
- (id)slideAtIndex:(unsigned int)fp8;
- (unsigned int)nextAvailableSlideIndex;
- (unsigned int)countOfSlides;
- (id)orderedSlides;
- (id)slides;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (id)imprint;
- (void)demolish;
- (id)initWithImprint:(id)fp8 andMontage:(id)fp12;
- (id)initFromScratchWithMontage:(id)fp8;

@end

