/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MCAction.h"

@class NSString;

@interface MCConditionalAction : MCAction
{
    NSString *_predicate;
    MCAction *_actionIfTrue;
    MCAction *_actionIfFalse;
}

+ (id)conditionalActionWithPredicate:(id)fp8;
- (void)setActionIfFalse:(id)fp8;
- (id)actionIfFalse;
- (void)setActionIfTrue:(id)fp8;
- (id)actionIfTrue;
- (void)setPredicate:(id)fp8;
- (id)predicate;
- (void)_copySelfToSnapshot:(id)fp8;
- (id)setConditionalActionWithPredicate:(id)fp8 forCondition:(BOOL)fp12;
- (id)setActionGroupForCondition:(BOOL)fp8;
- (id)setGenericActionForTargetPlugObjectID:(id)fp8 withAttributes:(id)fp12 forCondition:(BOOL)fp16;
- (id)setAnimationTriggerForTargetPlugObjectID:(id)fp8 withAnimationKey:(id)fp12 forCondition:(BOOL)fp16;
- (id)setTransitionForTargetPlugObjectID:(id)fp8 withTransitionID:(id)fp12 forCondition:(BOOL)fp16;
- (id)imprint;
- (void)demolish;
- (id)initWithImprint:(id)fp8;

@end

