/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MCAction.h"

@class NSMutableDictionary;

@interface MCGenericAction : MCAction
{
    NSMutableDictionary *_attributes;
}

+ (id)genericActionForTargetPlugObjectID:(id)fp8 withAttributes:(id)fp12;
- (void)setAttributes:(id)fp8;
- (id)attributes;
- (void)_copySelfToSnapshot:(id)fp8;
- (id)imprint;
- (void)demolish;
- (id)initWithImprint:(id)fp8;

@end

