/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class MCPlug, NSDictionary, NSMutableDictionary, NSRecursiveLock, NSString;

@interface MCMontage : _ACAccountTypeIdentifierTwitter
{
    NSDictionary *mImprintWhileLoading;
    NSMutableDictionary *mVideoAssetsForFilePaths;
    NSMutableDictionary *mVideoAssetsForObjectIDs;
    NSMutableDictionary *mAudioAssetsForFilePaths;
    NSMutableDictionary *mAudioAssetsForObjectIDs;
    NSMutableDictionary *mContainersForObjectIDs;
    NSRecursiveLock *mLock;
    MCPlug *mRootPlug;
    double mAudioFadeOutDuration;
    NSString *mBasePath;
    unsigned long long mUUIDSeed;
}

- (void)setBasePath:(id)fp8;
- (id)basePath;
- (void)setAudioFadeOutDuration:(double)fp8;
- (double)audioFadeOutDuration;
- (id)rootPlug;
- (void)forgetAboutContainer:(id)fp8;
- (void)registerContainer:(id)fp8;
- (id)containerForObjectID:(id)fp8;
- (id)audioAssets;
- (id)videoAssets;
- (id)assets;
- (id)audioAssetForObjectID:(id)fp8;
- (id)videoAssetForObjectID:(id)fp8;
- (id)assetForObjectID:(id)fp8;
- (id)audioAssetForFileAtPath:(id)fp8;
- (id)videoAssetForFileAtPath:(id)fp8;
- (id)createNavigatorContainer;
- (id)createEffectContainer;
- (id)createParallelizerContainer;
- (id)createSerializerContainer;
- (unsigned long long)uuidSeed;
- (void)unlock;
- (void)lock;
- (id)data;
- (id)imprint;
- (void)demolish;
- (void)dealloc;
- (id)initWithData:(id)fp8 error:(id *)fp12;
- (id)initFromScratch;
- (id)init;

@end

