/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface MCObjectBase : _ACAccountTypeIdentifierTwitter
{
}

+ (void)initialize;
- (void)_copySelfToSnapshot:(id)fp8;
- (id)snapshot;
- (id)imprint;
- (BOOL)isSnapshot;
- (void)demolish;
- (void)dealloc;
- (void)finalize;

@end

