/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MCPlug.h"

@class MCContainerNavigator, NSString;

@interface MCPlugHaven : MCPlug
{
    NSString *mIDInSupercontainer;
    MCContainerNavigator *mSupercontainer;
}

- (void)setSupercontainer:(id)fp8;
- (id)supercontainer;
- (void)setIDInSupercontainer:(id)fp8;
- (id)idInSupercontainer;
- (void)_copySelfToSnapshot:(id)fp8;
- (void)setActionOnCompletion:(id)fp8;
- (id)actionOnCompletion;
- (id)imprint;
- (void)demolish;
- (id)initWithImprint:(id)fp8 andMontage:(id)fp12;

@end

