/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MCPlug.h"

@class MCContainerSerializer, NSMutableDictionary, NSString;

@interface MCPlugSerial : MCPlug
{
    unsigned int mIndex;
    NSString *mTransitionID;
    double mTransitionDuration;
    NSMutableDictionary *mTransitionAttributes;
    MCContainerSerializer *mSupercontainer;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)fp8;
- (void)setSupercontainer:(id)fp8;
- (id)supercontainer;
- (double)transitionDuration;
- (void)setTransitionID:(id)fp8;
- (id)transitionID;
- (void)setIndex:(unsigned int)fp8;
- (unsigned int)index;
- (void)_copySelfToSnapshot:(id)fp8;
- (void)setTransitionAttributes:(id)fp8;
- (id)transitionAttributes;
- (void)setTransitionAttribute:(id)fp8 forKey:(id)fp12;
- (id)transitionAttributeForKey:(id)fp8;
- (void)setTransitionDuration:(double)fp8;
- (id)imprint;
- (void)demolish;
- (id)initWithImprint:(id)fp8 andMontage:(id)fp12;

@end

