/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MCObject.h"

@class MCPlug;

@interface MCPlugProxy : MCObject
{
    MCPlug *mPlug;
}

- (void)setPlug:(id)fp8;
- (id)plug;
- (void)_copySelfToSnapshot:(id)fp8;
- (int)zIndex;
- (BOOL)isKindOfClass:(Class)fp8;
- (id)forwardingTargetForSelector:(SEL)fp8;
- (void)dealloc;

@end

