/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface MCTextConversion : _ACAccountTypeIdentifierTwitter
{
}

+ (id)attributedStringWithNSAttributesFromStringAttributes:(id)fp8;
+ (id)attributedStringWithCTAttributesFromStringAttributes:(id)fp8;
+ (id)stringAttributesWithAttributedString:(id)fp8;
+ (id)textFormatWithNSAttributesForText:(id)fp8 attributes:(id)fp12;
+ (id)textFormatWithCTAttributesForText:(id)fp8 attributes:(id)fp12;
+ (id)textFormatFromUnderlineStyle:(unsigned int)fp8;
+ (unsigned int)underlineStyleFromTextFormat:(id)fp8;
+ (id)stringFromLigature:(int)fp8;
+ (int)ligatureFromString:(id)fp8;
+ (id)stringFromTextAlignment:(int)fp8;
+ (int)textAlignmentFromString:(id)fp8;
+ (id)stretchForFontDisplayName:(id)fp8 andFamilyName:(id)fp12;
+ (id)weightForFontDisplayName:(id)fp8 andFamilyName:(id)fp12;
+ (id)styleForFontDisplayName:(id)fp8 andFamilyName:(id)fp12;

@end

