/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class MEExporterManager, MEExporter_Legacy, METask, MPDocument, NSCondition, NSString;

@interface MEExporter : _ACAccountTypeIdentifierTwitter
{
    MEExporterManager *_manager;
    MPDocument *_document;
    SEL _progressSelector;
    id _progressTarget;
    id _progressObject;
    BOOL _progressEnableImage;
    BOOL _cancelled;
    BOOL _paused;
    BOOL _enablePause;
    NSCondition *_pauseCondition;
    BOOL _useSubprocess;
    NSString *_tmpDirectory;
    void *_daFunc;
    METask *_task;
    MEExporter_Legacy *_legacyExporter;
}

- (id)tmpDirectory;
- (BOOL)isProgressImageEnabled;
- (BOOL)isPauseEnabled;
- (BOOL)isCancelled;
- (id)preferences;
- (void)resumeExport;
- (void)pauseExport;
- (void)cancelExport;
- (BOOL)exportToFile:(id)fp8 withOptions:(id)fp12 error:(id *)fp16;
- (void)setProgressSelector:(SEL)fp8 withTarget:(id)fp12 andObject:(id)fp16;
- (void)dealloc;
- (id)initWithDocument:(id)fp8;
- (id)initWithDocument:(id)fp8 andManager:(id)fp12;

@end

