/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class MEExporter, MPDocument;

@interface MEPlugin : _ACAccountTypeIdentifierTwitter
{
    MEExporter *_delegate;
    MPDocument *_document;
}

- (id)delegate;
- (void)dealloc;
- (id)initWithIdentifier:(id)fp8 andDocument:(id)fp12 andDelegate:(id)fp16;

@end

