/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MEPlugin.h"

#import "MEPluginRegistration-Protocol.h"
#import "MEPluginTypeGeneric-Protocol.h"

@class NSLock, NSOperationQueue;

@interface MEPluginHTML5 : MEPlugin <MEPluginRegistration, MEPluginTypeGeneric>
{
    NSLock *mXMLLock;
    NSOperationQueue *mImageQueue;
}

+ (BOOL)matchesOptions:(id)fp8;
+ (void)registerPluginsToLoader:(id)fp8;
- (id)_addTextLocationInfoWithEffectID:(id)fp8 presetID:(id)fp12 size:(struct CGSize)fp16 textDict:(id)fp24 textASPFactor:(float)fp28;
- (id)_addWordsLocationInfoWithEffectID:(id)fp8 size:(struct CGSize)fp12 textDict:(id)fp20;
- (void)cacheImageAtPath:(id)fp8 toPath:(id)fp12 withAssetInfo:(id)fp16 referenceOriginal:(BOOL)fp20 createCache:(BOOL)fp24;
- (BOOL)exportToFile:(id)fp8 andOptions:(id)fp12 error:(id *)fp16;
- (void)dealloc;
- (id)initWithIdentifier:(id)fp8 andDocument:(id)fp12 andDelegate:(id)fp16;

@end

