/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPAction.h"

#import "MPActionSupport-Protocol.h"

@class NSMutableArray;

@interface MPActionGroup : MPAction <MPActionSupport>
{
    NSMutableArray *_actions;
}

+ (id)actionGroup;
- (void)setAction:(id)fp8;
- (void)configureTarget;
- (void)configureAction:(id)fp8 atIndex:(int)fp12;
- (void)copyActions:(id)fp8;
- (void)removeAllActions;
- (void)removeActionsAtIndices:(id)fp8;
- (void)insertActions:(id)fp8 atIndex:(int)fp12;
- (void)addActions:(id)fp8;
- (void)insertAction:(id)fp8 atIndex:(int)fp12;
- (void)addAction:(id)fp8;
- (id)actions;
- (unsigned int)numberOfActions;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)dealloc;
- (id)initWithCoder:(id)fp8;
- (id)init;

@end

