/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "NSCoding-Protocol.h"

@class MCContainerParallelizer, MUMathExpressionDoubleBased, NSDictionary, NSMutableArray, NSMutableDictionary, NSString;

@interface MPAnimatedSet : _ACAccountTypeIdentifierTwitter <NSCoding>
{
    NSString *mAnimatedSetID;
    NSDictionary *mDescription;
    MUMathExpressionDoubleBased *mTimeOfGoodPositionFormula;
    BOOL mTimeWraps;
    NSMutableDictionary *mSlides;
    NSMutableArray *mFeaturedSlidePositions;
    NSMutableArray *mFeaturingAttributes;
    double mStartTime;
    double mIntroDuration;
    double mMainDuration;
    double mOutroDuration;
    double mTotalNumberOfIntervals;
    double mDefaultFeaturingDuration;
    double mDefaultFeaturingAnimationDuration;
    NSDictionary *mDefaultFeaturingAnimationAttributes;
    NSDictionary *mAttributes;
    BOOL mEaseInEaseOutBetweenFeaturedSlides;
    BOOL mFirstSlideIsShared;
    BOOL mLastSlideIsShared;
    NSString *mIntroAnimationID;
    NSString *mOutroAnimationID;
    float mDistance;
    float mSpeed;
    MCContainerParallelizer *mContainer;
}

- (id)container;
- (void)setSpeed:(float)fp8;
- (float)speed;
- (void)setDistance:(float)fp8;
- (float)distance;
- (void)setOutroAnimationID:(id)fp8;
- (id)outroAnimationID;
- (void)setIntroAnimationID:(id)fp8;
- (id)introAnimationID;
- (void)setLastSlideIsShared:(BOOL)fp8;
- (BOOL)lastSlideIsShared;
- (void)setFirstSlideIsShared:(BOOL)fp8;
- (BOOL)firstSlideIsShared;
- (void)setEaseInEaseOutBetweenFeaturedSlides:(BOOL)fp8;
- (BOOL)easeInEaseOutBetweenFeaturedSlides;
- (void)setAttributes:(id)fp8;
- (id)attributes;
- (void)setDefaultFeaturingAnimationDuration:(double)fp8;
- (double)defaultFeaturingAnimationDuration;
- (void)setDefaultFeaturingDuration:(double)fp8;
- (double)defaultFeaturingDuration;
- (void)setStartTime:(double)fp8;
- (double)startTime;
- (BOOL)timeWraps;
- (id)animatedSetID;
- (void)chooseAnOutroAnimation;
- (void)chooseAnIntroAnimation;
- (double)fullDuration;
- (void)setAnimationPathsForPlug:(id)fp8 atPosition:(unsigned int)fp12;
- (void)applyIntroAnimationPathsToPlug:(id)fp8 atPosition:(unsigned int)fp12;
- (double)timeOfGoodPositionForPosition:(int)fp8;
- (void)setAnimationPaths:(id)fp8 onPlug:(id)fp12 atPosition:(unsigned int)fp16 atTimeOffset:(double)fp20 withTimeOffsetKind:(int)fp28 forDuration:(double)fp32 withFunctionTimeOffset:(double)fp40 andFunctionTimeFactor:(double)fp48 easeIn:(BOOL)fp56 easeOut:(BOOL)fp60 otherAttributes:(id)fp64;
- (void)computeAnimationPathsForTime:(double)fp8 andPosition:(unsigned int)fp16 usingAnimationPaths:(id)fp20 otherAttributes:(id)fp24 plugTimeOffset:(double)fp28 plugTimeOffsetKind:(int)fp36 plugAnimationPaths:(id)fp40;
- (void)insertIntoContainer:(id)fp8;
- (void)updateContainer;
- (double)featuringTimeForSlideAtPosition:(unsigned int)fp8;
- (id)slides;
- (void)removeAllSlides;
- (void)removeSlideAtPosition:(unsigned int)fp8;
- (void)showSlide:(id)fp8 atPosition:(unsigned int)fp12 featuringAttributes:(id)fp16;
- (void)decodeFromSlides:(id)fp8;
- (BOOL)needsEvenNumberOfSlides;
- (unsigned int)maximumNumberOfSlides;
- (unsigned int)minimumNumberOfSlides;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)dealloc;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithAnimatedSetID:(id)fp8;

@end

