/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPAction.h"

@class NSMutableDictionary, NSString;

@interface MPAnimationTrigger : MPAction
{
    NSString *_animationKey;
    NSMutableDictionary *_animationAttributes;
}

+ (id)animationTrigger;
- (id)animationAttributes;
- (id)animationKey;
- (void)setAction:(id)fp8;
- (void)setAnimationAttributes:(id)fp8;
- (void)setAnimationKey:(id)fp8;
- (id)animationAttributeForKey:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)dealloc;
- (id)initWithCoder:(id)fp8;
- (id)init;

@end

