/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPAnimationKeyframe.h"

@interface MPAnimationKeyframe2D : MPAnimationKeyframe
{
    struct CGPoint _point;
}

+ (id)keyframe2DWithPoint:(struct CGPoint)fp8 atTime:(double)fp16 offsetType:(int)fp24;
+ (id)keyframe2DWithPoint:(struct CGPoint)fp8 atTime:(double)fp16;
- (void)setPoint:(struct CGPoint)fp8;
- (struct CGPoint)point;
- (id)description;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)initKeyframe2DWithPoint:(struct CGPoint)fp8 atTime:(double)fp16 offsetType:(int)fp24;

@end

