/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPAnimationKeyframe.h"

@interface MPAnimationKeyframe1D : MPAnimationKeyframe
{
    float _scalar;
}

+ (id)keyframe1DWithScalar:(float)fp8 atTime:(double)fp12 offsetType:(int)fp20;
+ (id)keyframe1DWithScalar:(float)fp8 atTime:(double)fp12;
- (void)setScalar:(float)fp8;
- (float)scalar;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)initKeyframe1DWithScalar:(float)fp8 atTime:(double)fp12 offsetType:(int)fp20;

@end

