/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPAnimationKeyframe.h"

@interface MPAnimationKeyframe (Internal)
- (void)copyStruct:(id)fp8;
- (void)setKeyframe:(id)fp8;
- (id)parentDocument;
- (void)setParentPath:(id)fp8;
@end

