/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPAnimationKeyframe.h"

@class MPVector;

@interface MPAnimationKeyframeVector : MPAnimationKeyframe
{
    MPVector *_vector;
}

+ (id)keyframeVectorWithVector:(id)fp8 atTime:(double)fp12 offsetType:(int)fp20;
+ (id)keyframeVectorWithVector:(id)fp8 atTime:(double)fp12;
- (id)vector;
- (void)setVector:(id)fp8;
- (id)description;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)initKeyframeVectorWithVector:(id)fp8 atTime:(double)fp12 offsetType:(int)fp20;

@end

