/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class MCAnimationPath, NSObject<MPAnimationSupport>;

@interface MPAnimationPath : _ACAccountTypeIdentifierTwitter <NSCoding, NSCopying>
{
    BOOL _isTriggered;
    NSObject<MPAnimationSupport> *_parentObject;
    MCAnimationPath *_animationPath;
}

+ (id)animationPath;
- (id)parent;
- (void)setIsTriggered:(BOOL)fp8;
- (BOOL)isTriggered;
- (id)key;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)init;

@end

