/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPAssetManager.h"

@interface MPAssetManager (ImageUtils)
+ (char *)convertCGImageToBufferUsingDataProvider:(struct CGImage *)fp8;
+ (char *)convertCGImageToBufferUsingRGBDevice:(struct CGImage *)fp8;
+ (char *)convertCGImageToBuffer:(struct CGImage *)fp8;
@end

