/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol MPAssetKeyDelegate
- (id)absolutePathForStillAssetAtPath:(id)fp8 andSize:(struct CGSize)fp12;
- (id)absolutePathForAssetKey:(id)fp8 andSize:(struct CGSize)fp12;
- (id)absolutePathForAssetKey:(id)fp8;
@end

