/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPAssetManager.h"

@interface MPAssetManager (Private)
- (id)prepareInfoForAssetsAtPaths:(id)fp8;
- (void)removeRegionOfInterestAtIndex:(int)fp8 forAssetAtPath:(id)fp12 saveToCache:(BOOL)fp16;
- (void)setForceOrderForRegionsOfInterest:(BOOL)fp8 forPath:(id)fp12 saveToCache:(BOOL)fp16;
- (void)moveRegionOfInterestWithPath:(id)fp8 fromIndex:(int)fp12 toIndex:(int)fp16 saveToCache:(BOOL)fp20;
- (void)updateRegionOfInterestAtIndex:(int)fp8 atPath:(id)fp12 to:(struct CGRect)fp16 saveToCache:(BOOL)fp32;
- (void)updateROIInfoAtIndex:(int)fp8 atPath:(id)fp12 to:(id)fp16 saveToCache:(BOOL)fp20;
- (void)setRegionOfInterest:(struct CGRect)fp8 atIndex:(int)fp24 forAssetAtPath:(id)fp28 saveToCache:(BOOL)fp32;
- (void)setROIInfo:(id)fp8 atIndex:(int)fp12 forAssetAtPath:(id)fp16 saveToCache:(BOOL)fp20;
- (void)addRegionOfInterest:(struct CGRect)fp8 forAssetAtPath:(id)fp24 saveToCache:(BOOL)fp28;
- (void)addROIInfo:(id)fp8 forAssetAtPath:(id)fp12 saveToCache:(BOOL)fp16;
- (struct CGRect)regionOfInterestAtIndex:(int)fp8 forAssetAtPath:(id)fp12;
- (id)roiInfoAtIndex:(int)fp8 forAssetAtPath:(id)fp12;
- (void)tryToSaveCache;
@end

