/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPAuthoringController.h"

@interface MPAuthoringController (Beats)
- (void)createBeatsThreaded:(id)fp8;
- (int)indexOfBeatWithTimestamp:(double)fp8 inBeats:(id)fp16 inRange:(struct _NSRange)fp20;
- (double)findClosestBeatForTime:(double)fp8 inBeats:(id)fp16 atIndex:(int *)fp20;
- (id)beatsForAudioPlaylist:(id)fp8 withOptions:(id)fp12;
@end

