/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPAuthoringController.h"

@interface MPAuthoringController (Manipulation)
- (void)combineSlides:(id)fp8 inDocument:(id)fp12 withOptions:(id)fp16;
- (void)removeStyledCaptionFromSlide:(id)fp8 inDocument:(id)fp12 withOptions:(id)fp16;
- (void)addStyledCaptionToSlide:(id)fp8 inDocument:(id)fp12 withOptions:(id)fp16;
- (void)removeSlidesAtIndicies:(id)fp8 inDocument:(id)fp12 withOptions:(id)fp16;
- (void)insertVideoPaths:(id)fp8 atIndex:(int)fp12 inDocument:(id)fp16 withOptions:(id)fp20;
- (void)moveSlidesFromIndicies:(id)fp8 toIndex:(int)fp12 inDocument:(id)fp16 withOptions:(id)fp20;
@end

