/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPAudioPlaylist.h"

@interface MPAudioPlaylist (Internal)
- (id)parentDocument;
- (void)setDuration:(double)fp8;
- (void)setParentObject:(id)fp8;
- (void)setPlug:(id)fp8;
- (void)setAudioPlaylist:(id)fp8;
- (void)setMontage:(id)fp8;
- (id)montage;
- (void)cleanup;
- (void)copySongs:(id)fp8;
- (void)copyStruct:(id)fp8;
@end

