/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface MPAuthoringUtilities : _ACAccountTypeIdentifierTwitter
{
}

+ (float)multilineSizeFactorFromOptions:(id)fp8;
+ (double)distanceBetween:(struct CGPoint)fp8 andPoint:(struct CGPoint)fp16;
+ (struct CGPoint)kbCenterPointFromRect:(struct CGRect)fp8;
+ (struct CGRect)rectToFitIn:(struct CGRect)fp8 withAspectRatio:(float)fp24;
+ (id)gapInformationFromOptions:(id)fp8;
+ (BOOL)useLargestEffectsFromOptions:(id)fp8;
+ (id)absolutePathsForPaths:(id)fp8 withOptions:(id)fp12;
+ (struct _NSRange)videoPathsRangeFromOptions:(id)fp8;
+ (double)fadeOutDurationFromOptions:(id)fp8;
+ (id)absolutePathAtIndex:(int)fp8 inPaths:(id)fp12 withOptions:(id)fp16;
+ (id)subtitlesFromOptions:(id)fp8;
+ (BOOL)performFaceDetectionFromOptions:(id)fp8;
+ (int)regionOfInterestPickModeFromOptions:(id)fp8;
+ (struct _NSRange)reconfigureRangeFromOptions:(id)fp8;
+ (id)layerTypeFromOptions:(id)fp8;
+ (int)presentationOrderFromOptions:(id)fp8;
+ (BOOL)alwaysIncludeLastTransitionFromOptions:(id)fp8;
+ (BOOL)shouldDuckMoviesFromOptions:(id)fp8;
+ (id)absolutePathForPath:(id)fp8 withOptions:(id)fp12;
+ (BOOL)fadeOutAudioFromOptions:(id)fp8;
+ (BOOL)useTransitionLayoutTagsWithOptions:(id)fp8;
+ (BOOL)requestGeneratedImagesFromOptions:(id)fp8;
+ (BOOL)canAdjustPhaseDurations:(id)fp8;
+ (BOOL)pickEffectsEvenlyByIDWithOptions:(id)fp8;
+ (BOOL)pickTransitionsEvenlyByIDWithOptions:(id)fp8;
+ (BOOL)useROIAspectRatioFromOptions:(id)fp8;
+ (int)reorderModeFromOptions:(id)fp8;
+ (id)colorSchemeFromOptions:(id)fp8;
+ (BOOL)effectDecidesTransitionFromOptions:(id)fp8;
+ (float)movieVolumeFromOptions:(id)fp8;
+ (BOOL)padTextOnlyEffects:(id)fp8;
+ (BOOL)useUniformDurations:(id)fp8;
+ (double)minimumEffectDurationFromOptions:(id)fp8;
+ (double)maximumTransitionDurationFromOptions:(id)fp8;
+ (double)minimumTransitionDurationFromOptions:(id)fp8;
+ (int)numberOfLayersFromOptions:(id)fp8;
+ (BOOL)layerHasImagesFromOptions:(id)fp8;
+ (id)layerDescriptionForLayerWithZIndex:(int)fp8 forStyle:(id)fp12;
+ (double)exportTransitionDurationFromOptions:(id)fp8;
+ (id)exportTransitionIDFromOptions:(id)fp8;
+ (id)loopTransitionIDFromOptions:(id)fp8;
+ (float)effectPadding:(id)fp8;
+ (BOOL)shouldComputeLoopTransitionFromOptions:(id)fp8;
+ (BOOL)shouldComputeSlideFiltersFromOptions:(id)fp8;
+ (id)lastPresetFromOptions:(id)fp8;
+ (BOOL)shouldComputeTransitionsFromOptions:(id)fp8;
+ (BOOL)shouldComputeFramesFromOptions:(id)fp8;
+ (id)presetIDFromPresetID:(id)fp8;
+ (id)idFromPresetID:(id)fp8;
+ (id)titleEffectFromOptions:(id)fp8;
+ (id)introEffectIDFromOptions:(id)fp8;
+ (int)maxNumberOfSlidesToPreloadFromOptions:(id)fp8;
+ (int)minimumNumberOfDynamicSlidesToAddFromOptions:(id)fp8;
+ (BOOL)scaleOutroEffectFromOptions:(id)fp8;
+ (double)outroDurationFromOptions:(id)fp8;
+ (double)introDurationFromOptions:(id)fp8;
+ (id)outroEffectIDFromOptions:(id)fp8;
+ (id)transitionListFromOptions:(id)fp8;
+ (id)ignoreTransitionListFromOptions:(id)fp8;
+ (BOOL)repeatTransitionsFromOptions:(id)fp8;
+ (BOOL)collectVersionInformationFromOptions:(id)fp8;
+ (float)kenBurnsZoomFactorFromOptions:(id)fp8;
+ (id)effectListFromOptions:(id)fp8;
+ (float)aspectRatioFromOptions:(id)fp8;
+ (unsigned int)randomSeedFromOptions:(id)fp8;
+ (BOOL)useDefaultAudioFromOptions:(id)fp8;
+ (BOOL)useTitleEffectFromOptions:(id)fp8;
+ (BOOL)useROIFromOptions:(id)fp8;
+ (BOOL)useBestAspectRatioFromOptions:(id)fp8;
+ (double)transitionDurationFromOptions:(id)fp8;
+ (BOOL)canRepeatPreset:(id)fp8;
+ (BOOL)effectNeedsPreviousAttributesFromOptions:(id)fp8;
+ (BOOL)canRepeatEffectWithPreset:(id)fp8;
+ (double)layerOffsetFromOptions:(id)fp8;
+ (double)durationPerEffectFromOptions:(id)fp8;
+ (BOOL)matchPhasesWithTransitionFromOptions:(id)fp8;
+ (struct CGColor *)backgroundColorFromOptions:(id)fp8;
+ (BOOL)replaceAudioPlaylistFromOptions:(id)fp8;
+ (double)beatFactorFromOptions:(id)fp8;
+ (double)layerTimeScaleFromOptions:(id)fp8;
+ (BOOL)lockTransitionDurationFromOptions:(id)fp8;
+ (BOOL)createBeatsFromOptions:(id)fp8;
+ (BOOL)alignToBeatsFromOptions:(id)fp8;
+ (BOOL)layerCanSkipScaleCalculation:(id)fp8 withOptions:(id)fp12;
+ (int)kenBurnsLevelFromOptions:(id)fp8;
+ (BOOL)kenBurnsAlwaysZoomInFromOptions:(id)fp8;
+ (float)kenBurnsEndZoomLevelFromOptions:(id)fp8;
+ (float)kenBurnsStartZoomLevelFromOptions:(id)fp8;
+ (float)kenBurnsPanFactorFromOptions:(id)fp8;
+ (float)maxKenBurnsZoomFromOptions:(id)fp8;
+ (float)kenBurnsLikelihoodFromOptions:(id)fp8;
+ (int)croppingModeFromOptions:(id)fp8;
+ (int)audioScalingModeFromOptions:(id)fp8;
+ (double)audioDurationFromOptions:(id)fp8;
+ (int)layerIndexFromOptions:(id)fp8;
+ (id)styleFromOptions:(id)fp8;
+ (id)urlsFromPaths:(id)fp8;
+ (BOOL)ignoreClusteringForImages:(id)fp8 withOptions:(id)fp12;

@end

