/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPAuthoringController.h"

@interface MPAuthoringController (Animation)
+ (id)transitionAnimatedSetsBetween:(id)fp8 and:(id)fp12;
- (void)createAnimatedSetsInLayer2:(id)fp8 withOptions:(id)fp12;
- (void)createAnimatedSetsInLayer:(id)fp8 withOptions:(id)fp12;
@end

