/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSMutableArray, NSMutableDictionary, NSMutableSet, NSString;

@interface MPCluster : _ACAccountTypeIdentifierTwitter
{
    NSMutableArray *mSlides;
    NSMutableSet *mPathsInCluster;
    NSString *mName;
    float mRating;
    NSMutableDictionary *mUsageCounterPerLayer;
}

- (void)setUsageCounterPerLayer:(id)fp8;
- (id)usageCounterPerLayer;
- (void)setRating:(float)fp8;
- (float)rating;
- (void)setName:(id)fp8;
- (id)name;
- (void)setItems:(id)fp8;
- (id)items;
- (id)description;
- (void)detailedDescription;
- (id)usageCountDescription;
- (void)resetAllUsageCounters;
- (float)usageCountForLayer:(id)fp8;
- (void)setUsageCountForLayer:(id)fp8 to:(float)fp12;
- (id)allSlidesSortedChronologically;
- (BOOL)clusterContainsSlideAtPath:(id)fp8;
- (id)allSlides;
- (int)slideCount;
- (void)removeAllSlides;
- (void)addSlide:(id)fp8;
- (void)dealloc;
- (id)init;

@end

