/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPCropController.h"

@interface MPCropController (Private)
- (double)durationOfSlide:(id)fp8;
- (void)applyMultiFaceAnimatedCropToSlide:(id)fp8 withOptions:(id)fp12;
- (void)applyAnimatedCropToSlide:(id)fp8 withOptions:(id)fp12 centeredAt:(struct CGPoint)fp16 alwaysZoomIn:(BOOL)fp24;
- (struct CGPoint)checkFarApartROIs:(id)fp8 withImageSize:(struct CGSize)fp12 visibleAspectRatio:(float)fp20 roiCenter:(struct CGPoint)fp24;
- (void)applyStationaryCropToSlide:(id)fp8 withOptions:(id)fp12;
- (void)applyAnimatedCropWithROIsToSlide:(id)fp8 withOptions:(id)fp12;
- (void)applyAnimatedCropToSlide:(id)fp8 withOptions:(id)fp12;
- (void)applyCropToSlide:(id)fp8 withOptions:(id)fp12;
- (void)cleanup;
- (void)setupWithDocument:(id)fp8 andOptions:(id)fp12;
@end

