/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPDocument.h"

#import "MPLayerableSupportInternal-Protocol.h"

@interface MPDocument (Internal) <MPLayerableSupportInternal>
- (BOOL)needsToRemoveFadeIn;
- (double)removeFadeInIfNeeded;
- (BOOL)isInBatchModify;
- (void)configureActions;
- (BOOL)layersCanPositionZIndex;
- (void)setTemporarilyCacheAbsolutePaths:(BOOL)fp8;
- (void)setAbsoluteStillPath:(id)fp8 forKey:(id)fp12;
- (id)cachedAbsoluteStillPathFromPath:(id)fp8;
- (void)setAbsolutePath:(id)fp8 forKey:(id)fp12;
- (id)cachedAbsolutePathFromPath:(id)fp8;
- (BOOL)isLive;
- (BOOL)detectFacesInBackground;
- (double)aspectRatioDidChange:(float)fp8 atTime:(double)fp12;
- (BOOL)nearingEndWithOptions:(id)fp8;
- (id)organizedRandomTransitions;
- (void)organizeRandomTransitions;
- (void)setAudioFadeOutDuration:(double)fp8;
- (double)fadeOutAudioDuration;
- (void)setLastRandomTransition:(id)fp8;
- (id)lastRandomTransition;
- (id)descriptionForRandomTransitionPresetID:(id)fp8;
- (id)flightPlanFrom:(struct CGPoint)fp8 to:(struct CGPoint)fp16;
- (int)mapLevelForPath:(id)fp8;
- (struct CGPoint)pointForMap:(id)fp8 withAttributes:(id)fp12;
- (struct CGPoint)latLongPointForMap:(id)fp8 withAttributes:(id)fp12;
- (id)tiledMapPathsForAttributes:(id)fp8;
- (id)altitudeForPath:(id)fp8;
- (id)definedPlaceNameForPath:(id)fp8;
- (id)neighborhoodForPath:(id)fp8;
- (id)areaForPath:(id)fp8;
- (id)placeForPath:(id)fp8;
- (id)cityForPath:(id)fp8;
- (id)stateForPath:(id)fp8;
- (id)oceanForPath:(id)fp8;
- (id)countryForPath:(id)fp8;
- (id)longitudeForPath:(id)fp8;
- (id)latitudeForPath:(id)fp8;
- (id)captionForPath:(id)fp8;
- (id)keywordsForPath:(id)fp8;
- (id)creationDateForPath:(id)fp8;
- (id)regionsOfInterestForPath:(id)fp8 detect:(BOOL)fp12;
- (id)regionsOfInterestForPath:(id)fp8;
- (BOOL)isAudioAtPath:(id)fp8;
- (BOOL)isMovieAtPath:(id)fp8;
- (BOOL)isImageAtPath:(id)fp8;
- (float)volumeForPath:(id)fp8;
- (id)absoluteVideoPaths;
- (void)_setMediaProperties:(id)fp8;
- (void)setMontage:(id)fp8;
- (void)upgradeDocument;
- (id)documentLayerGroup;
- (id)actionableObjectForID:(id)fp8;
- (void)setupLayerGroups;
- (void)setupDocumentLayerGroup;
- (void)setDocumentLayerGroup:(id)fp8;
@end

