/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPDocument.h"

@interface MPDocument (Model)
- (id)mainLayers;
- (void)setAudioPlaylist:(id)fp8;
- (id)audioPlaylist;
- (double)videoDuration;
- (double)duration;
- (void)setBackgroundCGColor:(struct CGColor *)fp8;
- (struct CGColor *)backgroundCGColor;
- (id)keyedLayers;
- (void)removeLayerForKey:(id)fp8;
- (void)setLayer:(id)fp8 forKey:(id)fp12;
- (id)layerForKey:(id)fp8;
- (void)moveLayersFromIndices:(id)fp8 toIndex:(int)fp12;
- (void)removeLayersAtIndices:(id)fp8;
- (void)removeAllLayers;
- (void)insertLayers:(id)fp8 atIndex:(int)fp12;
- (void)addLayers:(id)fp8;
- (void)addLayer:(id)fp8;
- (id)layers;
@end

