/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPDocument.h"

@interface MPDocument (MediaManagement)
- (double)stopTimeForAssetAtPath:(id)fp8;
- (double)startTimeForAssetAtPath:(id)fp8;
- (id)attributeForAssetAtPath:(id)fp8 forKey:(id)fp12;
- (struct CGSize)resolutionForAssetAtPath:(id)fp8;
- (BOOL)isSupportedMovieForAssetAtPath:(id)fp8;
- (id)dataForAssetAtPath:(id)fp8 andSize:(struct CGSize)fp12;
- (struct CGImage *)thumbnailCGImageForAssetAtPath:(id)fp8 andSize:(struct CGSize)fp12;
- (struct CGImage *)CGImageForAssetAtPath:(id)fp8 andSize:(struct CGSize)fp12 orientation:(char *)fp20 thumbnailIfPossible:(BOOL)fp24 now:(BOOL)fp28;
- (struct CGImage *)CGImageForAssetAtPath:(id)fp8 andSize:(struct CGSize)fp12;
- (id)absolutePathForStillAssetAtPath:(id)fp8 andSize:(struct CGSize)fp12;
- (id)absolutePathForAssetAtPath:(id)fp8 andSize:(struct CGSize)fp12;
- (id)absolutePathForAssetAtPath:(id)fp8;
@end

