/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPEffectContainer.h"

@interface MPEffectContainer (AppleScript)
- (void)setScriptingTransition:(id)fp8;
- (id)scriptingTransition;
- (void)replaceObjectInFiltersAtIndex:(int)fp8 withObject:(id)fp12;
- (void)removeObjectFromFiltersAtIndex:(int)fp8;
- (void)insertObject:(id)fp8 inFiltersAtIndex:(int)fp12;
- (id)objectInFiltersAtIndex:(int)fp8;
- (int)countOfFilters;
- (void)replaceObjectInEffectsAtIndex:(int)fp8 withObject:(id)fp12;
- (void)removeObjectFromEffectsAtIndex:(int)fp8;
- (void)insertObject:(id)fp8 inEffectsAtIndex:(int)fp12;
- (id)objectInEffectsAtIndex:(int)fp8;
- (int)countOfEffects;
@end

