/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "MPActionableSupport-Protocol.h"
#import "MPAudioSupport-Protocol.h"
#import "MPFilterSupport-Protocol.h"
#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class MCContainerParallelizer, MCPlug, MPAudioPlaylist, MPEffectContainerInternal, MPLayer, MPTransition, NSMutableArray, NSMutableDictionary;

@interface MPEffectContainer : _ACAccountTypeIdentifierTwitter <NSCoding, NSCopying, MPFilterSupport, MPAudioSupport, MPActionableSupport>
{
    MCPlug *_containerPlug;
    MCContainerParallelizer *_containerParallelizer;
    NSMutableArray *_effects;
    NSMutableArray *_filters;
    NSMutableDictionary *_attributes;
    MPTransition *_transition;
    MPLayer *_parentLayer;
    MPEffectContainerInternal *_internal;
    MPAudioPlaylist *_audioPlaylist;
    BOOL _transitionDisconnected;
}

+ (id)effectContainer;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)fp8;
- (double)outroTransitionDuration;
- (double)introTransitionDuration;
- (void)setDuration:(double)fp8;
- (double)duration;
- (double)startTime;
- (id)parentLayer;
- (int)index;
- (void)setAudioPlaylist:(id)fp8;
- (id)audioPlaylist;
- (void)setBackgroundCGColor:(struct CGColor *)fp8;
- (void)setBackgroundColorString:(id)fp8;
- (struct CGColor *)backgroundCGColor;
- (void)moveFiltersFromIndices:(id)fp8 toIndex:(int)fp12;
- (void)removeAllFilters;
- (void)removeFiltersAtIndices:(id)fp8;
- (void)insertFilters:(id)fp8 atIndex:(int)fp12;
- (void)addFilters:(id)fp8;
- (void)addFilter:(id)fp8;
- (id)filters;
- (void)setTransition:(id)fp8;
- (id)transition;
- (void)moveEffectsFromIndices:(id)fp8 toIndex:(int)fp12;
- (void)removeAllEffects;
- (void)removeEffectsAtIndices:(id)fp8;
- (void)insertEffects:(id)fp8 atIndex:(int)fp12;
- (void)addEffects:(id)fp8;
- (void)addEffect:(id)fp8;
- (id)effects;
- (void)dealloc;
- (void)finalize;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)description;
- (id)init;

@end

