/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSMutableArray, NSMutableDictionary;

@interface MPEffectManager : _ACAccountTypeIdentifierTwitter
{
    NSMutableDictionary *mEffects;
    NSMutableDictionary *mCategories;
    NSMutableDictionary *mCachedAspectRatios;
    NSMutableArray *mRegisteredFonts;
}

+ (void)releaseSharedManager;
+ (id)sharedManager;
+ (void)initialize;
- (id)aspectRatioForEffectID:(id)fp8;
- (int)numberOfSecondarySlidesForEffectID:(id)fp8;
- (int)numberOfSlidesForEffectID:(id)fp8;
- (double)defaultPosterFrameTimeForEffect:(id)fp8;
- (double)defaultPosterFrameTimeForEffectID:(id)fp8 andPresetID:(id)fp12;
- (void)defaultDurationsForEffectID:(id)fp8 phaseInDuration:(double *)fp12 mainDuration:(double *)fp16 phaseOutDuration:(double *)fp20;
- (double)defaultPhaseOutDurationForEffectID:(id)fp8;
- (double)defaultMainDurationForEffectID:(id)fp8;
- (double)defaultPhaseInDurationForEffectID:(id)fp8;
- (id)imageInputInfoForEffectID:(id)fp8;
- (float)mediaAspectRatioForEffectID:(id)fp8 usingAttributes:(id)fp12 atIndex:(int)fp16 defaultAspectRatio:(float)fp20;
- (float)mediaAspectRatioForEffectID:(id)fp8 usingPresetID:(id)fp12 atIndex:(int)fp16 defaultAspectRatio:(float)fp20;
- (id)mediaAspectRatiosForEffectID:(id)fp8 usingPresetID:(id)fp12 defaultAspectRatio:(float)fp16;
- (float)mediaAspectRatioForEffectID:(id)fp8 usingPresetID:(id)fp12 atIndex:(int)fp16;
- (id)mediaAspectRatiosForEffectID:(id)fp8 usingPresetID:(id)fp12;
- (id)descriptionForEffectID:(id)fp8;
- (id)attributesForEffectID:(id)fp8 andPresetID:(id)fp12;
- (id)presetIDsForEffectID:(id)fp8;
- (float)maxFontSizeInEffectID:(id)fp8 presetID:(id)fp12 atIndex:(int)fp16;
- (id)defaultStringForTextInEffectID:(id)fp8 presetID:(id)fp12 atIndex:(int)fp16;
- (id)allCategoryIDs;
- (id)allEffectIDs;
- (id)effectsWithNumOfImages:(unsigned int)fp8;
- (id)settingsUIControlDescriptionsForEffect:(id)fp8;
- (id)controlForAttribute:(id)fp8 forEffectID:(id)fp12;
- (id)localizedSettingsUITitleForTitleKey:(id)fp8 inEffect:(id)fp12;
- (id)localizedCategoryNameFromCategoryID:(id)fp8;
- (id)localizedEffectNameForEffectID:(id)fp8;
- (id)effectIDsForCategoryID:(id)fp8;
- (id)categoryIDsForEffectID:(id)fp8;
- (unsigned int)numOfTextsForEffectID:(id)fp8;
- (unsigned int)numOfImagesForEffectID:(id)fp8;
- (id)versionOfEffectID:(id)fp8;
- (void)dealloc;

@end

