/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSString;

@interface MPEffectContainerInternal : _ACAccountTypeIdentifierTwitter
{
    double startTime;
    double duration;
    struct CGColor *backgroundColor;
    NSString *uuid;
}

- (void)setUuid:(id)fp8;
- (id)uuid;
- (struct CGColor *)backgroundColor;
- (void)setDuration:(double)fp8;
- (double)duration;
- (void)setStartTime:(double)fp8;
- (double)startTime;
- (void)setBackgroundColor:(struct CGColor *)fp8;
- (void)dealloc;
- (void)finalize;

@end

