/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPEffectContainer.h"

@interface MPEffectContainer (Private)
- (id)fullDebugLog;
- (BOOL)isTransitionConnected;
- (void)reconnectTransition;
- (void)disconnectTransition;
- (double)findMinDuration;
- (void)dump;
- (id)plug;
- (id)container;
@end

