/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPAssetManager.h"

@interface MPEmbeddedAssetManager : MPAssetManager
{
}

- (id)absolutePathFromPath:(id)fp8;
- (double)stopTimeForAssetAtPath:(id)fp8;
- (double)durationForAssetAtPath:(id)fp8;
- (BOOL)isAssetAtPathASupportedAudio:(id)fp8;
- (BOOL)isAssetAtPathASupportedMovie:(id)fp8;
- (BOOL)isAssetAtPathASupportedImage:(id)fp8;
- (struct CGSize)resolutionForAssetAtPath:(id)fp8;

@end

