/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class MPDocument, NSLock, NSMutableSet, NSObject<MRMarimbaPlayback>, NSOperationQueue, NSTimer;

@interface MPFaceDetector : _ACAccountTypeIdentifierTwitter
{
    MPDocument *mDocument;
    NSObject<MRMarimbaPlayback> *mRenderer;
    NSOperationQueue *mDetectionQueue;
    BOOL mIsCancelled;
    NSMutableSet *mPathsInQueue;
    NSLock *mPathQueueLock;
    NSMutableSet *mPlayingSlides;
    NSLock *mPlayingSlidesLock;
    NSLock *mStartStopLock;
    NSTimer *mCheckTimer;
}

- (void)setRenderer:(id)fp8;
- (id)renderer;
- (void)setDocument:(id)fp8;
- (id)document;
- (void)stop;
- (void)checkPlayingSlides;
- (void)_checkPlayingSlides;
- (void)_setupTimer;
- (void)detectFaces:(id)fp8;
- (BOOL)suspended;
- (void)resume;
- (void)suspend;
- (void)_start;
- (BOOL)_pathIsInQueue:(id)fp8;
- (void)_removePathToQueue:(id)fp8;
- (void)_addPathToQueue:(id)fp8;
- (void)start;
- (void)dealloc;
- (id)init;

@end

