/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface MPFileValidationManager : _ACAccountTypeIdentifierTwitter
{
}

+ (void)releaseSharedManager;
+ (id)sharedManager;
- (id)resolveAliasPath:(id)fp8;
- (void)checkFileExtension:(id)fp8 isAudio:(char *)fp12 isImage:(char *)fp16 isVideo:(char *)fp20;
- (BOOL)validateFiles:(id)fp8 allowAudio:(BOOL)fp12 allowImages:(BOOL)fp16 allowMovies:(BOOL)fp20 extensionsOnly:(BOOL)fp24;
- (BOOL)validateFilesForMovies:(id)fp8 extensionsOnly:(BOOL)fp12;
- (BOOL)validateFilesForImages:(id)fp8 extensionsOnly:(BOOL)fp12;
- (BOOL)validateFilesForAudio:(id)fp8 extensionsOnly:(BOOL)fp12;

@end

