/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPFilter.h"

@interface MPFilter (Internal)
- (id)parentDocument;
- (void)setParent:(id)fp8;
- (void)setFilter:(id)fp8;
- (void)copyAnimationPaths:(id)fp8;
- (void)copyStruct:(id)fp8;
@end

