/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPFilter.h"

@interface MPFilter (Private)
- (id)convertMCAttributeToMPAttribute:(id)fp8 withKey:(id)fp12;
- (id)convertMPAttributeToMCAttribute:(id)fp8 withKey:(id)fp12;
- (void)setDefaults;
- (id)fullDebugLog;
- (void)dump;
- (id)filter;
@end

