/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "MPAnimationSupport-Protocol.h"
#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class MCFilter, MPFilterInternal, NSMutableDictionary, NSObject<MPFilterSupport>;

@interface MPFilter : _ACAccountTypeIdentifierTwitter <NSCoding, NSCopying, MPAnimationSupport>
{
    NSMutableDictionary *_attributes;
    NSMutableDictionary *_animationPaths;
    MCFilter *_filter;
    NSObject<MPFilterSupport> *_parent;
    MPFilterInternal *_internal;
}

+ (id)filterWithFilterID:(id)fp8;
- (id)parent;
- (int)index;
- (void)removeAnimationPathForKey:(id)fp8;
- (void)setAnimationPath:(id)fp8 forKey:(id)fp12;
- (id)animationPathForKey:(id)fp8;
- (id)animationPaths;
- (void)setFilterAttribute:(id)fp8 forKey:(id)fp12;
- (id)filterAttributeForKey:(id)fp8;
- (id)filterAttributes;
- (void)setPresetID:(id)fp8;
- (id)presetID;
- (void)setFilterID:(id)fp8;
- (id)filterID;
- (void)dealloc;
- (void)finalize;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)init;
- (id)initWithFilterID:(id)fp8;

@end

