/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPFilterManager.h"

@interface MPFilterManager (Internal)
- (id)randomFilter:(BOOL)fp8;
- (id)filterPresetsMatchingCriteria:(id)fp8;
- (id)randomFilterPresetFromList:(id)fp8 abidingWithConstraints:(id)fp12;
- (id)constraintsForFilterPresetsMatchingList:(id)fp8 andCriteria:(id)fp12;
@end

