/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSArray, NSMutableDictionary;

@interface MPFilterManager : _ACAccountTypeIdentifierTwitter
{
    NSMutableDictionary *mFilters;
    NSArray *mFilterCategories;
    NSMutableDictionary *mFilterPresets;
}

+ (void)releaseSharedManager;
+ (id)sharedManager;
- (id)animationsForFilterID:(id)fp8 andPresetID:(id)fp12;
- (id)attributesForFilterID:(id)fp8 andPresetID:(id)fp12;
- (id)presetIDsForFilterID:(id)fp8;
- (id)filterCategoryIDs;
- (id)filterIDsForCategoryID:(id)fp8;
- (id)versionOfFilterID:(id)fp8;
- (id)allFilterIDs;
- (void)dealloc;

@end

