/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSString;

@interface MPFrameInternal : _ACAccountTypeIdentifierTwitter
{
    NSString *frameID;
    NSString *presetID;
}

- (void)setPresetID:(id)fp8;
- (id)presetID;
- (void)setFrameID:(id)fp8;
- (id)frameID;
- (void)dealloc;

@end

