/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol MPGeometrySupport
- (void)setScale:(float)fp8;
- (float)scale;
- (void)setYRotationAngle:(float)fp8;
- (float)yRotationAngle;
- (void)setXRotationAngle:(float)fp8;
- (float)xRotationAngle;
- (void)setSize:(struct CGSize)fp8;
- (struct CGSize)size;
- (void)setRotationAngle:(float)fp8;
- (float)rotationAngle;
- (void)setZPosition:(float)fp8;
- (float)zPosition;
- (void)setPosition:(struct CGPoint)fp8;
- (struct CGPoint)position;
- (void)setOpacity:(float)fp8;
- (float)opacity;
@end

