/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface MPKeyframeInternal : _ACAccountTypeIdentifierTwitter
{
    double time;
    unsigned int offsetType;
    double preControl;
    double postControl;
}

- (void)setPostControl:(double)fp8;
- (double)postControl;
- (void)setPreControl:(double)fp8;
- (double)preControl;
- (void)setOffsetType:(unsigned int)fp8;
- (unsigned int)offsetType;
- (void)setTime:(double)fp8;
- (double)time;

@end

