/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPLayerGroup.h"

@interface MPLayerGroup (AppleScript)
- (void)replaceObjectInLayersAtIndex:(int)fp8 withObject:(id)fp12;
- (void)removeObjectFromLayersAtIndex:(int)fp8;
- (void)insertObject:(id)fp8 inLayersAtIndex:(int)fp12;
- (id)valueInLayersWithName:(id)fp8;
- (id)objectInLayersAtIndex:(int)fp8;
- (int)countOfLayers;
@end

