/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "MPActionSupport-Protocol.h"
#import "MPActionableSupport-Protocol.h"
#import "MPAnimationSupport-Protocol.h"
#import "MPAudioSupport-Protocol.h"
#import "MPFilterSupport-Protocol.h"
#import "MPGeometrySupport-Protocol.h"
#import "MPLayerableSupport-Protocol.h"
#import "MPTimingSupport-Protocol.h"
#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class MCMontage, MCPlugParallel, MPAudioPlaylist, MPLayerInternal, NSMutableArray, NSMutableDictionary;

@interface MPLayer : _ACAccountTypeIdentifierTwitter <NSCoding, NSCopying, MPFilterSupport, MPAnimationSupport, MPAudioSupport, MPActionableSupport, MPLayerableSupport, MPGeometrySupport, MPTimingSupport, MPActionSupport>
{
    MCPlugParallel *_plug;
    NSMutableDictionary *_attributes;
    NSMutableArray *_effectContainers;
    NSMutableArray *_filters;
    NSMutableDictionary *_animationPaths;
    NSMutableDictionary *_actions;
    MPAudioPlaylist *_audioPlaylist;
    MCMontage *_montage;
    id _parent;
    MPLayerInternal *_internal;
    BOOL _skipTimeCalculations;
}

+ (id)effectLayer;
+ (id)animatedLayer;
+ (id)sequentialLayer;
+ (id)layer;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)fp8;
- (void)removeActionForKey:(id)fp8;
- (void)setAction:(id)fp8 forKey:(id)fp12;
- (id)actionForKey:(id)fp8;
- (id)actions;
- (id)layerKey;
- (id)layerID;
- (void)setLayerID:(id)fp8;
- (void)setIsAudioLayer:(BOOL)fp8;
- (BOOL)isAudioLayer;
- (void)setNumberOfLoops:(double)fp8;
- (double)numberOfLoops;
- (void)setAudioPriority:(int)fp8;
- (int)audioPriority;
- (void)setAudioPlaylist:(id)fp8;
- (id)audioPlaylist;
- (void)setStartsPaused:(BOOL)fp8;
- (BOOL)startsPaused;
- (void)setIsTriggered:(BOOL)fp8;
- (BOOL)isTriggered;
- (void)setPhaseOutDuration:(double)fp8;
- (double)phaseOutDuration;
- (void)setPhaseInDuration:(double)fp8;
- (double)phaseInDuration;
- (void)setDuration:(double)fp8;
- (double)duration;
- (void)setTimeIn:(double)fp8;
- (double)timeIn;
- (id)parent;
- (void)setZIndex:(int)fp8;
- (int)zIndex;
- (void)setYRotationAngle:(float)fp8;
- (float)yRotationAngle;
- (void)setXRotationAngle:(float)fp8;
- (float)xRotationAngle;
- (void)setSize:(struct CGSize)fp8;
- (struct CGSize)size;
- (void)setRotationAngle:(float)fp8;
- (float)rotationAngle;
- (void)setZPosition:(float)fp8;
- (float)zPosition;
- (void)setPosition:(struct CGPoint)fp8;
- (struct CGPoint)position;
- (void)setScale:(float)fp8;
- (float)scale;
- (void)setOpacity:(float)fp8;
- (float)opacity;
- (void)removeAnimationPathForKey:(id)fp8;
- (void)setAnimationPath:(id)fp8 forKey:(id)fp12;
- (id)animationPathForKey:(id)fp8;
- (id)animationPaths;
- (void)moveFiltersFromIndices:(id)fp8 toIndex:(int)fp12;
- (void)removeAllFilters;
- (void)removeFiltersAtIndices:(id)fp8;
- (void)insertFilters:(id)fp8 atIndex:(int)fp12;
- (void)addFilters:(id)fp8;
- (void)addFilter:(id)fp8;
- (id)filters;
- (void)moveEffectContainersFromIndices:(id)fp8 toIndex:(int)fp12;
- (void)removeAllEffectContainers;
- (void)removeEffectContainersAtIndices:(id)fp8;
- (void)insertEffectContainers:(id)fp8 atIndex:(int)fp12;
- (void)addEffectContainers:(id)fp8;
- (void)addEffectContainer:(id)fp8;
- (id)effectContainers;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)dealloc;
- (void)finalize;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)description;
- (id)init;

@end

