/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPLayer.h"

@interface MPLayer (AppleScript)
- (void)setScriptingAnimations:(id)fp8;
- (id)scriptingAnimations;
- (void)setWidth:(float)fp8;
- (float)width;
- (void)setHeight:(float)fp8;
- (float)height;
- (void)setYPosition:(float)fp8;
- (float)yPosition;
- (void)setXPosition:(float)fp8;
- (float)xPosition;
- (void)replaceObjectInFiltersAtIndex:(int)fp8 withObject:(id)fp12;
- (void)removeObjectFromFiltersAtIndex:(int)fp8;
- (void)insertObject:(id)fp8 inFiltersAtIndex:(int)fp12;
- (id)objectInFiltersAtIndex:(int)fp8;
- (int)countOfFilters;
- (void)replaceObjectInEffectContainersAtIndex:(int)fp8 withObject:(id)fp12;
- (void)removeObjectFromEffectContainersAtIndex:(int)fp8;
- (void)insertObject:(id)fp8 inEffectContainersAtIndex:(int)fp12;
- (id)objectInEffectContainersAtIndex:(int)fp8;
- (int)countOfEffectContainers;
@end

