/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSDictionary, NSMutableDictionary, NSRecursiveLock, NSString;

@interface MPLayerGroupInternal : _ACAccountTypeIdentifierTwitter
{
    double numberOfLoops;
    int loopingMode;
    double durationPadding;
    double duration;
    double timeIn;
    double phaseInDuration;
    double phaseOutDuration;
    NSString *backgroundAudioID;
    struct CGColor *backgroundColor;
    NSDictionary *authoredVersionInfo;
    int sendLiveNotification;
    NSRecursiveLock *liveLock;
    BOOL autoAdjustDuration;
    BOOL isDocumentLayerGroup;
    BOOL isTriggered;
    BOOL startsPaused;
    BOOL usedAllPaths;
    float opacity;
    struct CGPoint position;
    float zPosition;
    struct CGSize size;
    float rotationAngle;
    float xRotationAngle;
    float yRotationAngle;
    float scale;
    int zIndex;
    NSString *uuid;
    NSMutableDictionary *layerKeyDictionary;
    NSDictionary *initialState;
}

- (void)setUsedAllPaths:(BOOL)fp8;
- (BOOL)usedAllPaths;
- (void)setInitialState:(id)fp8;
- (id)initialState;
- (void)setLayerKeyDictionary:(id)fp8;
- (id)layerKeyDictionary;
- (void)setZIndex:(int)fp8;
- (int)zIndex;
- (void)setUuid:(id)fp8;
- (id)uuid;
- (void)setScale:(float)fp8;
- (float)scale;
- (void)setYRotationAngle:(float)fp8;
- (float)yRotationAngle;
- (void)setXRotationAngle:(float)fp8;
- (float)xRotationAngle;
- (void)setRotationAngle:(float)fp8;
- (float)rotationAngle;
- (void)setSize:(struct CGSize)fp8;
- (struct CGSize)size;
- (void)setZPosition:(float)fp8;
- (float)zPosition;
- (void)setPosition:(struct CGPoint)fp8;
- (struct CGPoint)position;
- (void)setOpacity:(float)fp8;
- (float)opacity;
- (void)setIsDocumentLayerGroup:(BOOL)fp8;
- (BOOL)isDocumentLayerGroup;
- (void)setAutoAdjustDuration:(BOOL)fp8;
- (BOOL)autoAdjustDuration;
- (void)setLiveLock:(id)fp8;
- (id)liveLock;
- (void)setSendLiveNotification:(int)fp8;
- (int)sendLiveNotification;
- (void)setAuthoredVersionInfo:(id)fp8;
- (id)authoredVersionInfo;
- (struct CGColor *)backgroundColor;
- (void)setLoopingMode:(int)fp8;
- (int)loopingMode;
- (void)setBackgroundAudioID:(id)fp8;
- (id)backgroundAudioID;
- (void)setPhaseOutDuration:(double)fp8;
- (double)phaseOutDuration;
- (void)setPhaseInDuration:(double)fp8;
- (double)phaseInDuration;
- (void)setStartsPaused:(BOOL)fp8;
- (BOOL)startsPaused;
- (void)setIsTriggered:(BOOL)fp8;
- (BOOL)isTriggered;
- (void)setTimeIn:(double)fp8;
- (double)timeIn;
- (void)setDuration:(double)fp8;
- (double)duration;
- (void)setDurationPadding:(double)fp8;
- (double)durationPadding;
- (void)setNumberOfLoops:(double)fp8;
- (double)numberOfLoops;
- (void)setBackgroundColor:(struct CGColor *)fp8;
- (void)dealloc;
- (void)finalize;

@end

