/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPLayer.h"

@interface MPLayer (Private)
- (id)parentDocument;
- (id)fullDebugLog;
- (void)dump;
- (id)allSongs;
- (id)allSlides:(BOOL)fp8;
- (id)montage;
- (id)plug;
@end

