/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPLayer.h"

#import "MPEffectSupport-Protocol.h"

@class MCContainerEffect, NSMutableArray, NSMutableDictionary, NSObject<MZEffectTiming>, NSString;

@interface MPLayerEffect : MPLayer <MPEffectSupport>
{
    MCContainerEffect *_layerEffect;
    NSString *_effectID;
    NSString *_presetID;
    NSMutableArray *_slides;
    NSMutableArray *_secondarySlides;
    NSMutableArray *_texts;
    NSMutableDictionary *_effectAttributes;
    int _randomSeed;
    NSObject<MZEffectTiming> *_effectTiming;
    BOOL _supportsEffectTiming;
}

+ (id)layerEffectWithEffectID:(id)fp8 strings:(id)fp12 paths:(id)fp16;
+ (id)layerEffectWithEffectID:(id)fp8 andStrings:(id)fp12;
+ (id)layerEffectWithEffectID:(id)fp8 andPaths:(id)fp12;
+ (id)layerEffectWithEffectID:(id)fp8;
- (id)effectTiming;
- (id)allSlides:(BOOL)fp8;
- (void)_updateTiming:(BOOL)fp8;
- (void)_updateEffectTiming;
- (void)setPhaseOutDuration:(double)fp8;
- (void)setPhaseInDuration:(double)fp8;
- (void)setDuration:(double)fp8;
- (double)mainDuration;
- (void)removeAllSecondarySlides;
- (void)moveTextsFromIndices:(id)fp8 toIndex:(int)fp12;
- (void)removeAllTexts;
- (void)removeTextsAtIndices:(id)fp8;
- (void)insertTexts:(id)fp8 atIndex:(int)fp12;
- (void)addTexts:(id)fp8;
- (void)addText:(id)fp8;
- (id)texts;
- (void)removeSecondarySlidesAtIndices:(id)fp8;
- (void)insertSecondarySlides:(id)fp8 atIndex:(int)fp12;
- (void)addSecondarySlides:(id)fp8;
- (void)addSecondarySlide:(id)fp8;
- (id)secondarySlides;
- (void)moveSlidesFromIndices:(id)fp8 toIndex:(int)fp12;
- (void)removeAllSlides;
- (void)removeSlidesAtIndices:(id)fp8;
- (void)insertSlides:(id)fp8 atIndex:(int)fp12;
- (void)addSlides:(id)fp8;
- (void)addSlide:(id)fp8;
- (id)slides;
- (void)setEffectAttribute:(id)fp8 forKey:(id)fp12;
- (id)effectAttributeForKey:(id)fp8;
- (void)setEffectAttributes:(id)fp8;
- (id)effectAttributes;
- (void)setRandomSeed:(int)fp8;
- (int)randomSeed;
- (void)setPresetID:(id)fp8;
- (id)presetID;
- (void)setEffectID:(id)fp8;
- (id)effectID;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (void)finalize;
- (id)description;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithEffectID:(id)fp8 strings:(id)fp12 paths:(id)fp16;
- (id)initWithEffectID:(id)fp8 andStrings:(id)fp12;
- (id)initWithEffectID:(id)fp8 andPaths:(id)fp12;
- (id)initWithEffectID:(id)fp8;
- (id)init;

@end

