/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPLayerEffect.h"

@interface MPLayerEffect (Internal)
- (void)copyTexts:(id)fp8;
- (void)copySecondarySlides:(id)fp8;
- (void)copySlides:(id)fp8;
- (void)setLayerEffect:(id)fp8;
- (id)slideInformation;
@end

