/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPNavigator.h"

#import "MPActionableSupportInternal-Protocol.h"
#import "MPNavigatorSupportInternal-Protocol.h"

@interface MPNavigator (Internal) <MPNavigatorSupportInternal, MPActionableSupportInternal>
- (id)layerKeyDictionary;
- (id)actionableObjectForID:(id)fp8;
- (void)reconnectAll;
- (void)copyActions:(id)fp8;
- (void)copyAnimationPaths:(id)fp8;
- (void)copyLayers:(id)fp8;
- (void)copyStruct:(id)fp8;
- (void)cleanup;
- (void)setPlug:(id)fp8;
- (void)setContainer:(id)fp8;
- (void)configureActions;
- (void)setParent:(id)fp8;
- (id)uuid;
- (id)objectID;
- (id)plugID;
- (id)parentDocument;
@end

