/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface MPPlaylistInternal : _ACAccountTypeIdentifierTwitter
{
    double duration;
    double fadeInDuration;
    double fadeOutDuration;
    double duckInDuration;
    double duckOutDuration;
    float duckLevel;
}

- (void)setDuckLevel:(float)fp8;
- (float)duckLevel;
- (void)setDuckOutDuration:(double)fp8;
- (double)duckOutDuration;
- (void)setDuckInDuration:(double)fp8;
- (double)duckInDuration;
- (void)setFadeOutDuration:(double)fp8;
- (double)fadeOutDuration;
- (void)setFadeInDuration:(double)fp8;
- (double)fadeInDuration;
- (void)setDuration:(double)fp8;
- (double)duration;

@end

