/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPSlide.h"

@interface MPSlide (Private)
- (double)maxDuration;
- (void)setMediaType:(int)fp8;
- (BOOL)hasMovie;
- (id)fullDebugLog;
- (void)dump;
- (id)slide;
@end

