/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPSong.h"

@interface MPSong (Internal)
- (void)setParentPlaylist:(id)fp8;
- (void)setSong:(id)fp8;
- (void)copyStruct:(id)fp8;
- (id)parentDocument;
- (double)stopTime;
@end

