/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSMutableDictionary, NSRecursiveLock, NSString;

@interface MPSongManager : _ACAccountTypeIdentifierTwitter
{
    NSMutableDictionary *mSongDescriptions;
    NSMutableDictionary *mSongBeats;
    NSMutableDictionary *mSongMetaData;
    NSString *mSongCacheFilePath;
    NSRecursiveLock *mSongLock;
    void *mDaFunc;
}

+ (void)releaseSharedManager;
+ (id)sharedManager;
- (id)songMetadataForPath:(id)fp8;
- (id)beatsForSongAtPath:(id)fp8 progressCallback:(void *)fp12 context:(void *)fp16;
- (void)dealloc;
- (id)init;

@end

