/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class MCSong, MPAudioPlaylist, MPSongInternal, NSString;

@interface MPSong : _ACAccountTypeIdentifierTwitter <NSCoding, NSCopying>
{
    NSString *_path;
    MCSong *_song;
    MPAudioPlaylist *_parentPlaylist;
    MPSongInternal *_internal;
}

+ (id)songWithPath:(id)fp8;
+ (id)songWithURL:(id)fp8;
+ (id)song;
- (id)parentPlaylist;
- (int)index;
- (void)setAudioVolume:(float)fp8;
- (float)audioVolume;
- (void)setFadeOutDuration:(double)fp8;
- (double)fadeOutDuration;
- (void)setFadeInDuration:(double)fp8;
- (double)fadeInDuration;
- (void)setDuration:(double)fp8;
- (double)duration;
- (void)setStartTime:(double)fp8;
- (double)startTime;
- (void)setURL:(id)fp8;
- (id)URL;
- (void)setPath:(id)fp8;
- (id)path;
- (id)description;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)initWithPath:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)init;

@end

