/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPStyleManager.h"

@interface MPStyleManager (Private)
+ (void)loadStyleManagerWithPaths:(id)fp8;
- (float)displayDurationFactorForEffectID:(id)fp8 inStyleID:(id)fp12;
- (float)displayDurationFactorForStyleID:(id)fp8;
- (int)antialiasLevelForStyleID:(id)fp8;
- (double)posterTimeForStyleID:(id)fp8;
- (id)demoDocumentWithImages:(id)fp8 properties:(id)fp12 count:(int)fp16 options:(id)fp20;
- (int)mediaPresentationOrderForStyleID:(id)fp8;
@end

