/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPStyleManager.h"

@interface MPStyleManager (VeryInternal)
- (id)_containerDescriptionForLayerAtIndex:(int)fp8 ofStyle:(id)fp12;
- (void)reloadBundles;
- (id)initWithPaths:(id)fp8;
@end

