/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class MCText, MPTextInternal, NSObject<MPEffectSupport>;

@interface MPText : _ACAccountTypeIdentifierTwitter <NSCoding, NSCopying>
{
    MCText *_text;
    MPTextInternal *_internal;
    NSObject<MPEffectSupport> *_parent;
}

+ (id)textWithAttributedString:(id)fp8;
- (float)textAreaAspectRatio;
- (double)displayDuration;
- (double)displayStartTime;
- (double)displayTime;
- (int)index;
- (id)subtitleSlide;
- (id)parentEffect;
- (void)setAttributedString:(id)fp8;
- (id)attributedString;
- (void)dealloc;
- (id)description;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)init;
- (id)initWithAttributedString:(id)fp8;

@end

