/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPText.h"

@interface MPText (Internal)
- (void)checkForMaxFontSize;
- (void)checkForPlacesLabel;
- (void)setParent:(id)fp8;
- (void)setText:(id)fp8;
- (id)nearestPlug;
- (void)copyStruct:(id)fp8;
- (id)action;
@end

