/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class MPTransitionInternal, NSMutableDictionary;

@interface MPTransition : _ACAccountTypeIdentifierTwitter <NSCoding, NSCopying>
{
    NSMutableDictionary *_attributes;
    id _parent;
    MPTransitionInternal *_internal;
}

+ (id)transitionWithTransitionID:(id)fp8;
- (id)parentContainer;
- (id)parent;
- (void)setTransitionAttribute:(id)fp8 forKey:(id)fp12;
- (id)transitionAttributeForKey:(id)fp8;
- (void)setTransitionAttributes:(id)fp8;
- (id)transitionAttributes;
- (void)setDuration:(double)fp8;
- (double)duration;
- (void)setPresetID:(id)fp8;
- (id)presetID;
- (void)setTransitionID:(id)fp8;
- (id)transitionID;
- (void)dealloc;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)init;
- (id)initWithTransitionID:(id)fp8;

@end

