/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPAction.h"

@class NSMutableDictionary, NSObject<MPActionableSupport>, NSString;

@interface MPTransitionAction : MPAction
{
    NSString *_transitionID;
    double _transitionDuration;
    NSMutableDictionary *_transitionAttributes;
    NSObject<MPActionableSupport> *_transitionDestination;
}

+ (id)transitionAction;
- (id)transitionDestination;
- (double)transitionDuration;
- (id)transitionID;
- (id)transitionAttributes;
- (void)configureTarget;
- (void)setAction:(id)fp8;
- (void)setTransitionDestination:(id)fp8;
- (void)setTransitionDuration:(double)fp8;
- (void)setTransitionID:(id)fp8;
- (void)setTransitionAttributes:(id)fp8;
- (id)transitionAttributeForKey:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)dealloc;
- (id)initWithCoder:(id)fp8;
- (id)init;

@end

