/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSString;

@interface MPTransitionInternal : _ACAccountTypeIdentifierTwitter
{
    NSString *transitionID;
    NSString *presetID;
    double duration;
    BOOL isRandom;
}

- (void)setIsRandom:(BOOL)fp8;
- (BOOL)isRandom;
- (void)setDuration:(double)fp8;
- (double)duration;
- (void)setPresetID:(id)fp8;
- (id)presetID;
- (void)setTransitionID:(id)fp8;
- (id)transitionID;
- (void)dealloc;

@end

