/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface MPUtilities : _ACAccountTypeIdentifierTwitter
{
}

+ (float)aspectRatioOfLayerable:(id)fp8 relativeToAspectRatio:(float)fp12;
+ (id)placesPinLabelForSlideAssetPath:(id)fp8 inDocument:(id)fp12;
+ (id)presetIDOfCombinedID:(id)fp8;
+ (id)idOfCombinedID:(id)fp8;
+ (id)layerForPlug:(id)fp8 inDocument:(id)fp12;
+ (id)slideForElementID:(id)fp8 withMCContainerEffect:(id)fp12 inDocument:(id)fp16;
+ (id)textForElementID:(id)fp8 withMCContainerEffect:(id)fp12 inDocument:(id)fp16;
+ (id)textsDisplayedAtTime:(double)fp8 inDocument:(id)fp16;
+ (id)slideForPath:(id)fp8 inDocument:(id)fp12;
+ (id)slideForSlide:(id)fp8 inDocument:(id)fp12;
+ (id)effectForMCContainerEffect:(id)fp8 inDocument:(id)fp12;
+ (id)effectForMCContainerWithObjectID:(id)fp8 inDocument:(id)fp12;
+ (id)textForIndex:(int)fp8 inMCContainerWithObjectID:(id)fp12 inDocument:(id)fp16;
+ (id)effectContainersForTime:(double)fp8 inDocument:(id)fp16;
+ (void)syncAnimationPaths:(id)fp8;
+ (id)animationsPathsFromFilterID:(id)fp8 andPresetID:(id)fp12;
+ (id)attributesFromAnimationPathsInFilter:(id)fp8 atTime:(double)fp12;
+ (id)attributesFormMPFilter:(id)fp8 atTime:(double)fp12;
+ (id)defaultAttributesForMPTransition:(id)fp8;
+ (id)defaultAttributesForMPFilter:(id)fp8;
+ (CDAnonymousStruct12)scaledFilterPresetVectorValue:(CDAnonymousStruct12)fp8 withKey:(id)fp28 forFilterID:(id)fp32 andPresetID:(id)fp36;
+ (struct CGPoint)scaledFilterPresetPointValue:(struct CGPoint)fp8 withKey:(id)fp16 forFilterID:(id)fp20 andPresetID:(id)fp24;
+ (float)scaledFilterPresetScalarValue:(float)fp8 withKey:(id)fp12 forFilterID:(id)fp16 andPresetID:(id)fp20;
+ (id)computeVectorValueForAnimationPath:(id)fp8 atTime:(double)fp12 defaultsTo:(id)fp20;
+ (struct CGPoint)computePointValueForAnimationPath:(id)fp8 atTime:(double)fp12 defaultsTo:(struct CGPoint)fp20;
+ (float)computeScalarValueForAnimationPath:(id)fp8 atTime:(double)fp12 defaultsTo:(float)fp20 context:(id)fp24;
+ (double)transformTime:(double)fp8 forAnimationPath:(id)fp16;
+ (int)timeOffSetFromString:(id)fp8;

@end

