/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class AVPlayer, NSArray;

@interface MRAudioPlayer : _ACAccountTypeIdentifierTwitter
{
    NSArray *_audioItems;
    AVPlayer *_avPlayer;
    double _duration;
    double _localTime;
    float _volume;
    double _fadeInDuration;
    double _fadeOutDuration;
    float _duckLevel;
    double _duckInDuration;
    double _duckOutDuration;
    int _priority;
    BOOL _shouldBePlaying;
}

- (BOOL)shouldBePlaying;
- (void)setPriority:(int)fp8;
- (int)priority;
- (void)setDuckOutDuration:(double)fp8;
- (double)duckOutDuration;
- (void)setDuckInDuration:(double)fp8;
- (double)duckInDuration;
- (void)setDuckLevel:(float)fp8;
- (float)duckLevel;
- (void)setFadeOutDuration:(double)fp8;
- (double)fadeOutDuration;
- (void)setFadeInDuration:(double)fp8;
- (double)fadeInDuration;
- (void)setVolume:(float)fp8;
- (float)volume;
- (void)setLocalTime:(double)fp8;
- (double)localTime;
- (double)duration;
- (id)avPlayer;
- (void)resyncAudioItem;
- (void)processWithDuckLevel:(float)fp8;
- (void)setShouldBePlaying:(BOOL)fp8;
- (float)currentDuckLevel;
- (void)syncVolumeToAudioPlaylist:(id)fp8;
- (void)dealloc;
- (id)initWithAudioItems:(id)fp8 andAudioPlaylist:(id)fp12;

@end

