/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MREffect.h"

@class MRImageProvider, MRTextRenderer, NSMutableArray, NSMutableDictionary;

@interface MREffectReflectionsTitle : MREffect
{
    NSMutableDictionary *mSprites;
    BOOL mFlipped;
    BOOL mSpeedUpRight;
    double mImageMain;
    double mTextMain;
    MRTextRenderer *mTextRenderer;
    MRTextRenderer *mWordRenderer;
    NSMutableArray *mWordImages;
    NSMutableArray *mWordFrames;
    NSMutableArray *mCachedRenderedWords;
    float mTextYOffset;
    struct CGSize mTextSize;
    struct CGSize mTextImageSize;
    MRImageProvider *mMaskProvider;
    MRImageProvider *mGroundShadowCenterProvider;
    MRImageProvider *mGroundShadowLeftProvider;
    MRImageProvider *mGroundShadowRightProvider;
}

- (void)_unload;
- (void)cacheRenderedWords;
- (void)_loadForTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)getVerticesCoordinates:(struct CGPoint (*)[4])fp8 withMatrix:(float [16])fp12 forElement:(id)fp16;
- (id)elementHitAtPoint:(struct CGPoint)fp8 withInverseMatrix:(float [16])fp16 localPoint:(struct CGPoint *)fp20;
- (void)renderKey:(id)fp8 size:(struct CGSize)fp12 position:(struct CGPoint)fp20 yRot:(float)fp28 tX:(float)fp32 time:(double)fp36 inContext:(id)fp44 withArguments:(id)fp48 light:(BOOL)fp52 shadow:(BOOL)fp56;
- (void)render1SlideAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20 scale:(float)fp24 tilt:(int)fp28 phaseOutType:(int)fp32 direction:(int)fp36;
- (void)renderTextAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20 scale:(float)fp24;
- (void)renderAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)isLoadedForTime:(double)fp8;
- (int)_maxLinesForTextElement:(id)fp8;
- (struct CGSize)_maxSizeForTextElement:(id)fp8;
- (BOOL)prerenderForTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (void)setPixelSize:(struct CGSize)fp8;
- (void)_cleanup;
- (id)initWithEffectID:(id)fp8;

@end

