/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MREffect.h"

@class MRImageProvider, MRTextRenderer, NSMutableArray, NSMutableDictionary;

@interface MREffectFlipupTitle : MREffect
{
    NSMutableDictionary *mSprites;
    BOOL mFlipped;
    MRTextRenderer *mTextRenderer;
    MRTextRenderer *mWordRenderer;
    NSMutableArray *mWordImages;
    NSMutableArray *mWordFrames;
    NSMutableArray *mCachedRenderedWords;
    float mTextYOffset;
    struct CGSize mTextSize;
    struct CGSize mTextImageSize;
    MRImageProvider *mMaskProvider;
}

- (void)_unload;
- (void)cacheRenderedWords;
- (void)_loadForTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)getVerticesCoordinates:(struct CGPoint (*)[4])fp8 withMatrix:(float [16])fp12 forElement:(id)fp16;
- (id)elementHitAtPoint:(struct CGPoint)fp8 withInverseMatrix:(float [16])fp16 localPoint:(struct CGPoint *)fp20;
- (void)renderTextAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20 scale:(float)fp24;
- (void)renderAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)isLoadedForTime:(double)fp8;
- (int)_maxLinesForTextElement:(id)fp8;
- (struct CGSize)_maxSizeForTextElement:(id)fp8;
- (BOOL)prerenderForTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (void)setPixelSize:(struct CGSize)fp8;
- (void)_cleanup;
- (id)initWithEffectID:(id)fp8;

@end

