/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MREffect.h"

#import "MZEffectTiming-Protocol.h"

@class MRCroppingSprite, MRImageProvider, NSMutableArray, NSMutableDictionary, NSString;

@interface MREffectPictureFrames : MREffect <MZEffectTiming>
{
    NSMutableDictionary *mSprites;
    NSMutableDictionary *mFrameProviders;
    MRCroppingSprite *mFrameSprite;
    MRImageProvider *mWallProvider;
    MRImageProvider *mGradientProvider;
    NSMutableArray *mTableProviders;
    NSMutableArray *mWallSprites;
    NSMutableArray *mLayoutWidths;
    float mTotalWidth;
    float mXOffset;
    BOOL mIsLoaded;
    NSMutableArray *mLayouts;
    NSMutableArray *mFrames;
    NSMutableArray *mSlideOrder;
    NSString *mFirstFrame;
    NSString *mLastFrame;
}

+ (id)customTimingWithEffectID:(id)fp8 effectAttributes:(id)fp12 slideInformation:(id)fp16 andTextInformation:(id)fp20;
+ (BOOL)hasCustomTiming;
+ (void)initialize;
- (BOOL)getVerticesCoordinates:(struct CGPoint (*)[4])fp8 withMatrix:(float [16])fp12 forElement:(id)fp16;
- (id)elementHitAtPoint:(struct CGPoint)fp8 withInverseMatrix:(float [16])fp16 localPoint:(struct CGPoint *)fp20;
- (id)_drawFrame:(id)fp8 provider:(id)fp12 index:(int)fp16 rect:(struct CGRect)fp20 time:(double)fp36 onTable:(BOOL)fp44 inContext:(id)fp48 withArguments:(id)fp52;
- (struct CGRect)_rectForFrameID:(id)fp8 rect:(struct CGRect)fp12 onTable:(BOOL)fp28 aspectRatio:(float)fp32;
- (id)_randomFrameForAspectRatio:(BOOL)fp8 forTable:(BOOL)fp12 allowMatte:(BOOL)fp16 onlyLoaded:(BOOL)fp20 ignoreFrames:(id)fp24 randomGenerator:(id)fp28;
- (id)_nextSlideProviderWithLandscape:(BOOL)fp8 providerKeys:(id)fp12 index:(int *)fp16;
- (void)renderAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (double)lowestDisplayTime;
- (double)displayTimeForTextAtIndex:(unsigned int)fp8;
- (double)displayTimeForSlideAtIndex:(unsigned int)fp8;
- (double)showDurationForSlideAtIndex:(unsigned int)fp8;
- (double)showTimeForSlideAtIndex:(unsigned int)fp8;
- (float)_xForSlideAtIndex:(int)fp8 layoutWidth:(float *)fp12;
- (struct CGRect)_frameRectFromInfo:(id)fp8 onShelf:(BOOL)fp12;
- (id)_populateFrames;
- (float)_aspectRatioForSlideIndex:(int)fp8;
- (void)_setupLayoutWithSlideInformation:(id)fp8;
- (float)_startingOffset;
- (float)_startingWidth;
- (double)_durationForEffect:(BOOL)fp8;
- (double)_durationForEffect;
- (void)_applyTimingToSlideProviders;
- (void)setPhaseInDuration:(double)fp8 mainDuration:(double)fp16 phaseOutDuration:(double)fp24;
- (BOOL)prerenderForTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (void)setPixelSize:(struct CGSize)fp8;
- (BOOL)isLoadedForTime:(double)fp8;
- (id)layoutsWithSlidesInfo:(id)fp8 seed:(unsigned int)fp12 hasShelf:(BOOL)fp16;
- (void)_cleanup;
- (id)initWithEffectID:(id)fp8;

@end

