/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MREffect.h"

@class MRImageProvider, MRReflectionsRenderable, NSMutableDictionary;

@interface MREffectReflections : MREffect
{
    NSMutableDictionary *mSprites;
    BOOL mSpeedUpRight;
    BOOL mIsLoaded;
    NSMutableDictionary *mLayoutInfo;
    int mTilt;
    int mPhaseOutType;
    int mDirection;
    int mLayout;
    int mAspect;
    MRImageProvider *mGroundShadowCenterProvider;
    MRImageProvider *mGroundShadowLeftProvider;
    MRImageProvider *mGroundShadowRightProvider;
    MRReflectionsRenderable *mHead;
    MRReflectionsRenderable *mTail;
}

+ (void)initialize;
- (void)endMorphing;
- (void)beginMorphingToAspectRatio:(float)fp8 withDuration:(double)fp12;
- (void)renderStuffAtTime:(double)fp8 alpha:(float)fp16 inContext:(id)fp20 withArguments:(id)fp24;
- (BOOL)getVerticesCoordinates:(struct CGPoint (*)[4])fp8 withMatrix:(float [16])fp12 forElement:(id)fp16;
- (id)elementHitAtPoint:(struct CGPoint)fp8 withInverseMatrix:(float [16])fp16 localPoint:(struct CGPoint *)fp20;
- (void)renderKey:(id)fp8 size:(struct CGSize)fp12 position:(struct CGPoint)fp20 yRot:(float)fp28 tX:(float)fp32 time:(double)fp36 inContext:(id)fp44 withArguments:(id)fp48 flipped:(BOOL)fp52 shadow:(BOOL)fp56;
- (float)_yOffsetForTime:(double)fp8 layout:(id)fp16 size:(struct CGSize)fp20 position:(struct CGPoint)fp28 aspectRatio:(float)fp36;
- (float)_tXForTime:(double)fp8 layout:(id)fp16;
- (float)_yRotationForTime:(double)fp8 layout:(id)fp16;
- (void)renderAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (void)_applySizeScripts:(float)fp8;
- (BOOL)prerenderForTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)isLoadedForTime:(double)fp8;
- (void)setPixelSize:(struct CGSize)fp8;
- (void)_cleanup;
- (id)initWithEffectID:(id)fp8;

@end

