/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MREffect.h"

@class MRImage, MRTextRenderer, NSArray, NSMutableArray, NSMutableDictionary;

@interface MREffectScrapbook : MREffect
{
    NSMutableDictionary *mFrameProviders;
    NSMutableDictionary *mSprites;
    BOOL mIsLoaded;
    BOOL mTitleAspectRatio;
    NSArray *mLayouts;
    MRTextRenderer *mTextRenderer0;
    MRImage *mTextImage0;
    NSMutableArray *mRectsToSubtract;
}

+ (void)initialize;
- (void)_drawBlendedFrame:(id)fp8 info:(id)fp12 index:(int)fp16 rect:(struct CGRect)fp20 zIndex:(int)fp36 zRotation:(float)fp40 subtract:(id)fp44 time:(double)fp48 inContext:(id)fp56 withArguments:(id)fp60;
- (void)_drawFrame:(id)fp8 info:(id)fp12 index:(int)fp16 rect:(struct CGRect)fp20 zIndex:(int)fp36 zRotation:(float)fp40 subtract:(id)fp44 time:(double)fp48 inContext:(id)fp56 withArguments:(id)fp60;
- (void)_drawMask:(id)fp8 index:(int)fp12 rect:(struct CGRect)fp16 zIndex:(int)fp32 zRotation:(float)fp36 subtract:(id)fp40 time:(double)fp44 inContext:(id)fp52 withArguments:(id)fp56;
- (void)_drawFrame:(id)fp8 info:(id)fp12 rect:(struct CGRect)fp16 stretch:(BOOL)fp32 zIndex:(int)fp36 zRotation:(float)fp40 subtract:(id)fp44 time:(double)fp48 inContext:(id)fp56 withArguments:(id)fp60;
- (void)_drawTextWithInfo:(id)fp8 rect:(struct CGRect)fp12 zIndex:(int)fp28 zRotation:(float)fp32 time:(double)fp36 inContext:(id)fp44 withArguments:(id)fp48;
- (void)renderAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)prerenderForTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)isOpaque;
- (BOOL)isAlphaFriendly;
- (void)setPixelSize:(struct CGSize)fp8;
- (BOOL)isLoadedForTime:(double)fp8;
- (void)_cleanup;
- (id)initWithEffectID:(id)fp8;

@end

