/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MREffect.h"

@class MRImage, MRTextRenderer;

@interface MREffectCalendar : MREffect
{
    MRTextRenderer *mTextRenderer;
    MRImage *mTextImage;
    struct CGSize mStride;
    struct CGSize mImageSize;
    struct CGSize mTextSize;
    struct CGPoint mBaseImagePosition;
    struct CGPoint mBaseTextPosition;
    unsigned char mFirstDayWeekday;
    unsigned char mNumberOfDays;
    BOOL mTextWasUpdatedSinceLastRendering;
}

- (void)renderAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)prerenderForTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)isLoadedForTime:(double)fp8;
- (void)setAttributes:(id)fp8;
- (id)init;

@end

