/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MREffectScrapbook_Old.h"

@interface MREffectScrapbook_Old (temp)
+ (void)renderDumbImage:(id)fp8 inContext:(id)fp12 atPosition:(struct CGPoint)fp16 andSize:(struct CGSize)fp24 zRotation:(float)fp32 withBorderRect:(struct CGRect)fp36;
+ (void)renderImage:(id)fp8 withFrame:(id)fp12 andMask:(id)fp16 usingSprite:(id)fp20 inContext:(id)fp24;
@end

