/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MREffectScrapbook_Old.h"

@interface MREffectScrapbook_Old (Effects)
- (void)renderEffect10AtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (void)renderEffect9AtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (void)renderEffect8AtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (void)renderEffect7AtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (void)renderEffect6AtTime:(double)fp8 movieVersion:(BOOL)fp16 inContext:(id)fp20 withArguments:(id)fp24;
- (void)renderEffect5AtTime:(double)fp8 movieVersion:(BOOL)fp16 inContext:(id)fp20 withArguments:(id)fp24;
- (void)renderEffect4AtTime:(double)fp8 movieVersion:(BOOL)fp16 inContext:(id)fp20 withArguments:(id)fp24;
- (void)renderEffect3AtTime:(double)fp8 movieVersion:(BOOL)fp16 inContext:(id)fp20 withArguments:(id)fp24;
- (void)renderEffect2AtTime:(double)fp8 movieVersion:(BOOL)fp16 inContext:(id)fp20 withArguments:(id)fp24;
- (void)renderEffect1AtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (void)renderBackgroundAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20 subtractingSprites:(id)fp24 withTranslation:(struct CGPoint)fp28 andScale:(float)fp36;
@end

