/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MREffect.h"

@class MRImage, MRImageProvider, MRTextRenderer, NSMutableArray, NSMutableDictionary;

@interface MREffectPortfolio : MREffect
{
    NSMutableDictionary *mSprites;
    MRImageProvider *mLeftPageProvider;
    MRImageProvider *mRightPageProvider;
    NSMutableDictionary *mFrameProviders;
    NSMutableArray *mFrameList;
    BOOL mIsLoaded;
    int mPageCount;
    BOOL mLeftZoom;
    BOOL mRightZoom;
    BOOL mNeedsSizeUpdate;
    BOOL mIsSlideOnly;
    MRTextRenderer *mTextRenderer0;
    MRImage *mTextImage0;
}

+ (void)initialize;
- (void)_updateSizes:(float)fp8;
- (void)endMorphing;
- (void)beginMorphingToAspectRatio:(float)fp8 withDuration:(double)fp12;
- (BOOL)getVerticesCoordinates:(struct CGPoint (*)[4])fp8 withMatrix:(float [16])fp12 forElement:(id)fp16;
- (id)elementHitAtPoint:(struct CGPoint)fp8 withInverseMatrix:(float [16])fp16 localPoint:(struct CGPoint *)fp20;
- (void)_drawIndex:(int)fp8 time:(double)fp12 context:(id)fp20 arguments:(id)fp24 size:(struct CGSize)fp28 position:(struct CGPoint)fp36;
- (struct CGRect)_rectForSlideAtIndex:(int)fp8 frame:(id)fp12 leftCount:(int)fp16 localAspectRatio:(float)fp20;
- (void)_drawFrame:(id)fp8 index:(int)fp12 leftCount:(int)fp16 time:(double)fp20 inContext:(id)fp28 withArguments:(id)fp32;
- (void)renderAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)prerenderForTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)isLoadedForTime:(double)fp8;
- (void)setPixelSize:(struct CGSize)fp8;
- (void)_cleanup;
- (id)initWithEffectID:(id)fp8;

@end

