/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MREffect.h"

#import "MZEffectTiming-Protocol.h"

@class MREffectCoverCascadeSlideStory, NSMutableArray;

@interface MREffectCoverCascade : MREffect <MZEffectTiming>
{
    NSMutableArray *_slideStories;
    MREffectCoverCascadeSlideStory *_grid[7][4];
    struct _NSRange _previousNewSlideRange;
    unsigned int _numberOfStoriesRemoved;
    unsigned char _previousScenarioType;
    unsigned char _previousStartX;
}

+ (id)customTimingWithEffectID:(id)fp8 effectAttributes:(id)fp12 slideInformation:(id)fp16 andTextInformation:(id)fp20;
+ (BOOL)hasCustomTiming;
- (void)_cleanup;
- (void)_unload;
- (void)renderAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)prerenderForTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (double)_buildNumberOfSlideStories:(unsigned int)fp8 withSlideRange:(struct _NSRange)fp12;
- (void)setPhaseInDuration:(double)fp8 mainDuration:(double)fp16 phaseOutDuration:(double)fp24;
- (void)_applyTimingToSlideProviders;
- (void)appendSlideInformation:(id)fp8 andTextInformation:(id)fp12;
- (double)lowestDisplayTime;
- (double)displayTimeForTextAtIndex:(unsigned int)fp8;
- (double)displayTimeForSlideAtIndex:(unsigned int)fp8;
- (double)showDurationForSlideAtIndex:(unsigned int)fp8;
- (double)showTimeForSlideAtIndex:(unsigned int)fp8;

@end

