/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MREffect.h"

@class MRCroppingSprite, MRImage, MRTextRenderer;

@interface MREffectJustATitle : MREffect
{
    MRTextRenderer *mTextRenderer0;
    MRTextRenderer *mTextRenderer1;
    MRImage *mImage0;
    MRImage *mImage1;
    MRCroppingSprite *mTextSprite0;
    MRCroppingSprite *mTextSprite1;
    struct CGRect mText0Rect;
    struct CGRect mText1Rect;
    BOOL mTextWasUpdatedSinceLastRendering;
}

- (void)renderAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)prerenderForTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)isLoadedForTime:(double)fp8;
- (BOOL)getVerticesCoordinates:(struct CGPoint (*)[4])fp8 withMatrix:(float [16])fp12 forElement:(id)fp16;
- (id)elementHitAtPoint:(struct CGPoint)fp8 withInverseMatrix:(float [16])fp16 localPoint:(struct CGPoint *)fp20;
- (void)setAttributes:(id)fp8;
- (id)init;

@end

