/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MREffect.h"

#import "MZEffectTiming-Protocol.h"

@class NSMutableArray, NSMutableDictionary;

@interface MREffectShiftingTiles : MREffect <MZEffectTiming>
{
    NSMutableDictionary *mSprites;
    NSMutableArray *mTiming;
    NSMutableArray *mFirstLayout;
    NSMutableArray *mLastLayout;
    int mLastCol;
    int mLastSlideIndex;
    int mSlideStartIndex;
    BOOL mNeedsToBeRebuilt;
    BOOL mNeedsToRecalculateIterations;
    int mIterationStartIndex;
}

+ (unsigned int)typicalSlideBatchSizeForEffectID:(id)fp8;
+ (BOOL)supportsDynamicExpansionForEffectID:(id)fp8;
+ (id)customTimingWithEffectID:(id)fp8 effectAttributes:(id)fp12 slideInformation:(id)fp16 andTextInformation:(id)fp20;
+ (BOOL)hasCustomTiming;
- (BOOL)getVerticesCoordinates:(struct CGPoint (*)[4])fp8 withMatrix:(float [16])fp12 forElement:(id)fp16;
- (id)elementHitAtPoint:(struct CGPoint)fp8 withInverseMatrix:(float [16])fp16 localPoint:(struct CGPoint *)fp20;
- (id)_layoutForIteration:(int)fp8;
- (id)_layoutForTime:(double)fp8;
- (id)_infoForTime:(double)fp8;
- (id)_slideProviderWithAspectRatio:(BOOL)fp8 nearest:(int)fp12 actual:(int *)fp16;
- (void)renderAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)prerenderForTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (void)_setupLayoutsWithSlideInfo:(id)fp8 append:(BOOL)fp12;
- (int)_widthForLayout:(int)fp8;
- (float)_aspectRatioForSlideIndex:(int)fp8;
- (double)displayTimeForTextAtIndex:(unsigned int)fp8;
- (double)displayTimeForSlideAtIndex:(unsigned int)fp8;
- (double)lowestDisplayTime;
- (double)showDurationForSlideAtIndex:(unsigned int)fp8;
- (id)_setupFirstLayout;
- (double)_calculateMainDuration;
- (double)showTimeForSlideAtIndex:(unsigned int)fp8;
- (void)_updateSizeScripts;
- (void)_applyTimingToSlideProviders;
- (void)setPhaseInDuration:(double)fp8 mainDuration:(double)fp16 phaseOutDuration:(double)fp24;
- (void)appendSlideInformation:(id)fp8 andTextInformation:(id)fp12;
- (void)setMultiImageSlideRange:(struct _NSRange)fp8;
- (int)_lowestDisplayIteration;
- (unsigned int)firstSlideIndexStillNeededAtTime:(double)fp8;
- (int)typicalSlideBatchSize;
- (BOOL)supportsDynamicExpansion;
- (void)_cleanup;
- (id)initWithEffectID:(id)fp8;

@end

