/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class AVAsset, AVAssetReader, AVAssetReaderTrackOutput;

@interface MRFakeMoviePlayer2 : _ACAccountTypeIdentifierTwitter
{
    AVAsset *_asset;
    AVAssetReader *_assetReader;
    AVAssetReaderTrackOutput *_trackOutput;
    struct __CVBuffer *_imageBuffer;
    double _playTimeOffset;
    double _lastImageCopyTime;
    double _time;
    BOOL _isPlaying;
}

- (BOOL)isPlaying;
- (double)time;
- (void)getNextImage;
- (struct __CVBuffer *)currentImage;
- (void)setIsPlaying:(BOOL)fp8;
- (void)setTime:(double)fp8;
- (void)cleanup;
- (void)dealloc;
- (id)initWithAsset:(id)fp8 andSize:(struct CGSize)fp12;

@end

