/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class MRCroppingSprite, MRImage;

@interface MRFlipupRenderable : _ACAccountTypeIdentifierTwitter
{
    float zPosition;
    BOOL needsBlend;
    float modelViewMatrix[16];
    float color;
    float opacity;
    MRImage *slide;
    MRCroppingSprite *sprite;
    struct CGPoint position;
    struct CGSize size;
    float flippedModelViewMatrix[16];
    MRCroppingSprite *reflectionSprite;
    struct CGPoint reflectionPosition;
}

- (void)setReflectionSprite:(id)fp8;
- (id)reflectionSprite;
- (void)setSprite:(id)fp8;
- (id)sprite;
- (void)setSlide:(id)fp8;
- (id)slide;
- (void)dealloc;

@end

