/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "MRLoadable-Protocol.h"
#import "MRRenderable-Protocol.h"

@class MRImage, MRSlideProvider, NSDictionary, NSString;

@interface MRFrame : _ACAccountTypeIdentifierTwitter <MRLoadable, MRRenderable>
{
    NSDictionary *mDescription;
    MRSlideProvider *mSlideProvider;
    MRImage *mInputImage;
    MRImage *mOutputImage;
    NSString *mFrameID;
    NSDictionary *mAttributes;
    NSDictionary *mFlattenedAttributes;
    struct CGSize mPixelSize;
}

+ (id)retainedFrameWithFrameID:(id)fp8 forSlideProvider:(id)fp12;
- (struct CGSize)pixelSize;
- (id)attributes;
- (id)frameID;
- (id)inputImage;
- (id)patchworkAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (id)retainedByUserRenderedImageAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (void)renderAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)prerenderForTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)isInfinite;
- (BOOL)isAlphaFriendly;
- (BOOL)isOpaque;
- (BOOL)isNative3D;
- (void)cancelLoading;
- (void)unload;
- (void)loadForTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20 now:(BOOL)fp24;
- (BOOL)isLoadedForTime:(double)fp8;
- (void)setPixelSize:(struct CGSize)fp8;
- (void)setAttributes:(id)fp8;
- (void)setInputImage:(id)fp8;
- (BOOL)isRetainedBySlideProvider;
- (void)releaseBySlideProvider:(id)fp8;
- (void)retainBySlideProvider:(id)fp8;
- (void)cleanup;
- (void)finalize;
- (void)dealloc;
- (id)initWithFrameID:(id)fp8;

@end

