/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSMutableDictionary;

@interface MRFrameManager : _ACAccountTypeIdentifierTwitter
{
    NSMutableDictionary *mFrameRepository;
    NSMutableDictionary *mFrameSets;
    NSMutableDictionary *mFramePools;
}

+ (void)loadFrameManagerWithPaths:(id)fp8;
+ (id)sharedManager;
+ (void)initialize;
- (id)attributesForFrameID:(id)fp8 andPresetID:(id)fp12;
- (id)sizeScriptForFrameID:(id)fp8;
- (id)resourcePathForFrameID:(id)fp8 andResource:(id)fp12;
- (id)descriptionForFrameID:(id)fp8;
- (void)recycleFrame:(id)fp8;
- (id)frameWithFrameID:(id)fp8;
- (void)releaseResources;
- (void)cleanup;
- (void)dealloc;
- (id)initWithPaths:(id)fp8;

@end

