/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSString;

@interface MRGIFMoviePlayer : _ACAccountTypeIdentifierTwitter
{
    NSString *_path;
    struct CGSize _size;
    struct CGImageSource *_imageSource;
    struct CGImage *_currentImage;
    unsigned long _currentIndex;
    unsigned long _numberOfImages;
    double _nextImageTime;
    double _playTimeOffset;
    float _imageDuration;
    BOOL _isPlaying;
}

- (BOOL)isPlaying;
- (void)getNextImage;
- (struct CGImage *)currentImage;
- (void)setIsPlaying:(BOOL)fp8;
- (void)setTime:(double)fp8;
- (void)cleanup;
- (void)dealloc;
- (id)initWithPath:(id)fp8 andSize:(struct CGSize)fp12;

@end

