/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class MRImageManager, MRTexture, NSDictionary, NSMutableDictionary, NSString;

@interface MRImage : _ACAccountTypeIdentifierTwitter
{
    MRImageManager *mImageManager;
    unsigned long mWidth;
    unsigned long mHeight;
    MRImage *mRefImage;
    NSString *mImageBufferKey;
    MRTexture *mTexture;
    unsigned long mPixelFormat;
    float mCenterX;
    float mCenterY;
    float mScale;
    float mRotationAngle;
    NSString *mFilterID;
    NSDictionary *mShader;
    int mClampMode;
    double mSourceTimeStamp;
    double mRenderTime;
    int mRetainByUserCount;
    float mColor[4];
    struct __CVBuffer *mCVPixelBuffer;
    struct CGContext *mCGContext;
    struct CGColorSpace *mColorspace;
    void *mDatas[3];
    unsigned long mDataSize;
    unsigned long mDataRowBytes;
    unsigned long mDataWidth;
    unsigned long mDataHeight;
    unsigned char mOrientation;
    NSMutableDictionary *mUserData;
    unsigned long mFlags;
}

- (void)setClampMode:(int)fp8;
- (int)clampMode;
- (void)setRenderTime:(double)fp8;
- (double)renderTime;
- (void)setSourceTimeStamp:(double)fp8;
- (double)sourceTimeStamp;
- (void)setShader:(id)fp8;
- (id)shader;
- (void)setFilterID:(id)fp8;
- (void)setRotationAngle:(float)fp8;
- (float)rotationAngle;
- (void)setScale:(float)fp8;
- (float)scale;
- (void)setCenterY:(float)fp8;
- (float)centerY;
- (void)setCenterX:(float)fp8;
- (float)centerX;
- (unsigned long)pixelFormat;
- (unsigned long)height;
- (unsigned long)width;
- (id)imageManager;
- (id)textureIfExists;
- (id)updateGLContext;
- (unsigned int)textureTarget;
- (unsigned int)textureName;
- (id)texture;
- (BOOL)isYUV;
- (BOOL)hasKBOrShader;
- (id)filterID;
- (struct CGSize)relativeSizeInContextPixelSize:(struct CGSize)fp8;
- (void)unsetOnContext:(id)fp8 onTextureUnit:(unsigned int)fp12 state:(const CDAnonymousStruct6 *)fp16;
- (void)setOnContext:(id)fp8 onTextureUnit:(unsigned int)fp12 withReferenceAspectRatio:(float)fp16 state:(CDAnonymousStruct6 *)fp20;
- (void)getMatrix:(float [16])fp8 forReferenceAspectRatio:(float)fp12;
- (void)kenburnsMatrix:(float [16])fp8 forReferenceAspectRatio:(float)fp12;
- (BOOL)isEmpty;
- (float)aspectRatio;
- (id)userData;
- (id)imageBufferKey;
- (void)setHasKenBurns:(BOOL)fp8;
- (BOOL)hasKenBurns;
- (void)setPreservesAspectRatio:(BOOL)fp8;
- (BOOL)preservesAspectRatio;
- (void)generateMipmap;
- (BOOL)usesMipmapping;
- (BOOL)isOpaque;
- (void)setFiltersNearest:(BOOL)fp8;
- (BOOL)filtersNearest;
- (BOOL)isMonochromatic;
- (BOOL)isPremultiplied;
- (void)setUsesBackgroundColorAsBorderColor:(BOOL)fp8;
- (BOOL)usesBackgroundColorAsBorderColor;
- (id)retainedByUserImageWithShader:(id)fp8;
- (id)retainedByUserImage;
- (void)removingFromCollection;
- (id)insertingInCollection;
- (void)releaseByUser;
- (id)retainByUser;
- (void)cleanup;
- (void)finalize;
- (void)dealloc;
- (id)initWithCGContext:(struct CGContext *)fp8 imageManager:(id)fp12;
- (id)initWithCGContext:(struct CGContext *)fp8 size:(struct CGSize)fp12 imageManager:(id)fp20;
- (id)initWithCVPixelBuffer:(struct __CVBuffer *)fp8 size:(struct CGSize)fp12 orientation:(int)fp20 imageBufferKey:(id)fp24 imageManager:(id)fp28 monochromatic:(BOOL)fp32;
- (id)initWithCGImage:(struct CGImage *)fp8 textureSize:(struct CGSize)fp12 orientation:(int)fp20 imageBufferKey:(id)fp24 imageManager:(id)fp28 monochromatic:(BOOL)fp32;
- (id)initWithImage:(id)fp8;
- (id)initWithTexture:(id)fp8;
- (id)initWithSize:(struct CGSize)fp8 andColor:(const float *)fp16 imageBufferKey:(id)fp20 imageManager:(id)fp24 options:(id)fp28;
- (id)init;

@end

