/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface MRLayerCommand : _ACAccountTypeIdentifierTwitter
{
    int commandID;
    id object;
}

- (void)dealloc;
- (id)initWithCommand:(int)fp8 andObject:(id)fp12;

@end

