/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MRLayer.h"

@interface MRLayer (Private)
- (void)_setNeedsToRequestRebuildAudio:(BOOL)fp8;
- (void)_unobservePlugOnDepreactivate;
- (void)_observePlugOnPreactivate;
- (void)_unobservePlug;
- (void)_observePlug;
- (void)_queueLayerCommand:(int)fp8 object:(id)fp12;
@end

