/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MRLayerEffect.h"

@interface MRLayerEffect (Private)
- (id)_retainedByUserRenderedImageAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (void)_renderAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (void)_unobservePlugOnDepreactivate;
- (void)_observePlugOnPreactivate;
- (void)_unobservePlug;
- (void)_observePlug;
- (void)_updateEffectAttributes;
- (void)_updateTexts;
- (void)_updateSlides;
- (void)_updateTiming;
- (void)_cleanupProviders;
- (void)_rebuildEffect;
@end

