/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MRLayer.h"

@class MCContainerSerializer, MRTransition, NSMutableArray, NSMutableDictionary;

@interface MRLayerSerializer : MRLayer
{
    MCContainerSerializer *mContainer;
    NSMutableArray *mSublayers;
    NSMutableDictionary *mSublayersForPlugs;
    BOOL mNeedsToUpdateSublayersTiming;
    BOOL mNeedsToUpdateTransitionAttributes;
    MRLayer *mCurrentSublayer;
    MRLayer *mNextSublayer;
    MRTransition *mCurrentTransition;
    MRLayer *mSublayerForTransition;
    BOOL mIsTransitioning;
    MRLayer *mSublayerToPrecompute;
    id mPrecomputingTarget;
    unsigned int mPrecomputingType;
    MRLayer *mLiveSourceSublayer;
    MRLayer *mLiveTargetSublayer;
    BOOL mLiveTransitionIsBackwards;
    BOOL mHasWarnedDelegateAboutNearingEnd;
}

- (id)sublayers;
- (id)_dumpLayerWithOptions:(unsigned int)fp8;
- (id)_currentState;
- (void)endTransitionToSublayer;
- (double)transitionToSublayerAtIndex:(unsigned int)fp8;
- (double)transitionToPreviousSublayer;
- (double)transitionToNextSublayer;
- (id)actionForKey:(id)fp8 recursive:(BOOL)fp12;
- (id)actionHitAtPoint:(struct CGPoint)fp8 layer:(id *)fp16;
- (id)sublayerForPlugObjectID:(id)fp8 recursive:(BOOL)fp12;
- (id)sublayerAtIndex:(unsigned int)fp8;
- (BOOL)_isNative3D;
- (BOOL)hasAudio;
- (id)sublayerHitAtPoint:(struct CGPoint)fp8 onlyIfHitElement:(BOOL)fp16 localPoint:(struct CGPoint *)fp20;
- (BOOL)supportsDynamicExpansion;
- (id)patchworkAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)prerenderForTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)isAlphaFriendly;
- (BOOL)isOpaque;
- (BOOL)isLoadedForTime:(double)fp8;
- (void)depreactivate:(BOOL)fp8;
- (void)deactivate;
- (void)endMorphing;
- (void)beginMorphingToAspectRatio:(float)fp8 withDuration:(double)fp12;
- (void)synchronizeTime;
- (BOOL)hasSomethingToRender;
- (void)setPixelSize:(struct CGSize)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)cleanup;
- (id)initWithPlug:(id)fp8 andParameters:(id)fp12 inSuperlayer:(id)fp16;

@end

