/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol MRMarimbaHitBlobSupport
- (void)cancelGesture:(id)fp8;
- (void)endGesture:(id)fp8;
- (void)doGesture:(id)fp8;
- (void)beginGesture:(id)fp8;
- (BOOL)endLiveUpdateForHitBlob:(id)fp8;
- (BOOL)beginLiveUpdateForHitBlob:(id)fp8;
- (struct CGPoint)convertPoint:(struct CGPoint)fp8 toHitBlob:(id)fp16;
- (BOOL)getOnScreenVertices:(struct CGPoint [4])fp8 forHitBlob:(id)fp12;
- (id)blobHitAtPoint:(struct CGPoint)fp8 fromObjectsForObjectIDs:(id)fp16 localPoint:(struct CGPoint *)fp20;
@end

