/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MRMarimbaLayer.h"

@interface MRMarimbaLayer (Private)
- (BOOL)updateFramebuffer;
- (void)destroyFramebuffer;
- (void)setBailTimeWatcher:(BOOL)fp8;
- (BOOL)bailTimeWatcher;
- (void)setReadOnly:(BOOL)fp8;
@end

