/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "MRMarimbaBasicPlayback-Protocol.h"

@class EAGLContext, MPDocument, MPFaceDetector, MRRenderer, NSDictionary;

@interface MRMarimbaLayer : _ACAccountTypeIdentifierTwitter <MRMarimbaBasicPlayback>
{
    MRRenderer *_renderer;
    MPDocument *_document;
    BOOL _masterClockIsSet;
    BOOL _bailTimeWatcher;
    BOOL _stopWithVideo;
    BOOL _readOnly;
    BOOL _wasSuspended;
    MPFaceDetector *_faceDetector;
    float _morphingToAspectRatio;
    struct CGSize _frameBufferSize;
    NSDictionary *_nextMorphInfo;
    EAGLContext *_context;
    unsigned int _viewRenderbuffer;
    unsigned int _viewFramebuffer;
}

+ (void)releaseResources;
+ (id)layerWithDocument:(id)fp8;
+ (id)layerWithDocument:(id)fp8 size:(struct CGSize)fp12;
- (void)swipeAt:(struct CGPoint)fp8 inDirection:(unsigned int)fp16 withModifiers:(unsigned int)fp20;
- (void)hitCanceledForKey:(id)fp8;
- (void)hitForKey:(id)fp8 endsAt:(struct CGPoint)fp12 withModifiers:(unsigned int)fp20;
- (void)hitForKey:(id)fp8 tracksAt:(struct CGPoint)fp12 hitCount:(int)fp20 withModifiers:(unsigned int)fp24;
- (void)hitForKey:(id)fp8 startsAt:(struct CGPoint)fp12 hitCount:(int)fp20 withModifiers:(unsigned int)fp24;
- (struct CGImage *)snapshotAsCGImage;
- (struct CGImage *)snapshotAsCGImageForTime:(double)fp8 withSize:(struct CGSize)fp16;
- (void)aspectRatioChangedTo:(id)fp8;
- (void)didAddEffects:(id)fp8;
- (void)didApplyStyle:(id)fp8;
- (BOOL)effectRequestedSlidesAfterDelay:(id)fp8;
- (BOOL)effect:(id)fp8 requestedNumberOfSlides:(unsigned int)fp12 firstSlideIndexStillNeeded:(unsigned int)fp16;
- (BOOL)nearingEndForSerializerAfterDelay:(id)fp8;
- (BOOL)nearingEndForSerializer:(id)fp8;
- (void)unlockRendering;
- (void)lockRendering;
- (void)_reauthorForAspectRatioChange;
- (void)endMorphing;
- (void)beginMorphingToAspectRatio:(float)fp8 withDuration:(double)fp12;
- (void)morphToAspectRatio:(float)fp8 andOrientation:(int)fp12 withDuration:(double)fp16;
- (void)_warmupRendererThreaded:(id)fp8;
- (void)warmupRenderer;
- (void)requestRendering:(BOOL)fp8;
- (void)setFramesPerSecond:(double)fp8;
- (double)framesPerSecond;
- (id)renderer;
- (void)prevFrame;
- (void)nextFrame;
- (void)gotoBeginning;
- (void)gotoEnd;
- (void)goForth;
- (void)goBack;
- (void)setSuspended:(BOOL)fp8;
- (void)setVolume:(float)fp8;
- (float)volume;
- (double)timeRemaining;
- (void)setTime:(double)fp8;
- (double)time;
- (void)setDisplaysFPS:(BOOL)fp8;
- (BOOL)displaysFPS;
- (void)setStopWithVideo:(BOOL)fp8;
- (BOOL)stopWithVideo;
- (void)pause;
- (void)play;
- (BOOL)isPlaying;
- (void)togglePlayback;
- (void)didLiveChanged:(id)fp8;
- (void)setDocument:(id)fp8;
- (struct CGSize)size;
- (void)setBounds:(struct CGRect)fp8;
- (void)setAsynchronous:(BOOL)fp8;
- (id)document;
- (void)cleanup;
- (void)dealloc;
- (id)init;

@end

