/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class MPText, MRMarimbaLayer, MRTextRenderer;

@interface MRMarimbaLayoutManager : _ACAccountTypeIdentifierTwitter
{
    MRMarimbaLayer *_marimbaLayer;
    MPText *_text;
    MRTextRenderer *_textRenderer;
}

- (void)setText:(id)fp8;
- (id)text;
- (void)setMarimbaLayer:(id)fp8;
- (id)marimbaLayer;
- (struct CGPoint)shadowOffset;
- (struct CGRect)currentRectForEditedText;
- (id)_renderer;
- (void)updateWithString:(id)fp8;
- (int)lineCount;
- (id)textRenderer;
- (void)dealloc;
- (id)init;

@end

