/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSMutableArray;

@interface MRPatchwork : _ACAccountTypeIdentifierTwitter
{
    NSMutableArray *_patches;
}

- (void)removeAllPatches;
- (void)addPatch:(id)fp8;
- (id)patchworkWithPatch:(id)fp8;
- (void)dealloc;
- (id)init;

@end

