/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MUPoolObject.h"

@class MRImage, NSString;

@interface MRPictureFrameRenderable : MUPoolObject
{
    MRImage *image;
    struct CGRect rect;
    struct CGRect innerRect;
    struct CGRect outerRect;
    NSString *where;
    BOOL ignoreBlend;
    MRPictureFrameRenderable *next;
}

+ (CDAnonymousStruct3 *)poolInfo;
- (void)setWhere:(id)fp8;
- (id)where;
- (void)setImage:(id)fp8;
- (id)image;
- (void)dealloc;
- (void)purge;

@end

