/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface MRPortfolioFrameImage : _ACAccountTypeIdentifierTwitter
{
    struct CGRect outer;
    struct CGRect inner;
    struct CGSize size;
    BOOL isImageFrame;
    BOOL needsInset;
    BOOL isMask;
    BOOL isRounded;
}

@end

