/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MRRenderer.h"

@interface MRRenderer (Private)
- (void)setUseCGLFlushDrawableWorkaround:(BOOL)fp8;
- (void)setHideTextWhileEditing:(BOOL)fp8;
- (BOOL)hideTextWhileEditing;
- (void)setScreenBurnTest:(BOOL)fp8;
- (BOOL)screenBurnTest;
- (void)setAsynchronousOperationsDelegate:(id)fp8;
- (id)asynchronousOperationsDelegate;
- (void)setLiveSlideshowDelegate:(id)fp8;
- (id)liveSlideshowDelegate;
- (void)setMasterStartTime:(double)fp8 andDuration:(double)fp16 mode:(int)fp24;
- (void)setMasterStartTime:(double)fp8 andDuration:(double)fp16 loop:(BOOL)fp24;
- (struct CGImage *)currentFrameAsCGImage;
- (struct CGImage *)copyCGSnapshotAtTime:(double)fp8 andSize:(struct CGSize)fp16;
- (struct CGImage *)snapshotAsCGImageForTime:(double)fp8 andSize:(struct CGSize)fp16;
- (id)layerAtPath:(id)fp8 fromLayer:(id)fp12;
- (void)undimAllLayers;
- (void)dimLayersExceptForPathTo:(id)fp8;
- (void)_undimAllLayersInLayer:(id)fp8;
- (id)selectedLayers;
- (void)deselectAllLayers;
- (void)deselectLayer:(id)fp8;
- (void)selectLayer:(id)fp8;
- (void)updateSelectionLayer;
- (BOOL)isFlipped;
- (void)setFreezeSizeOfImageRequests:(BOOL)fp8;
- (void)setMasterClock:(double)fp8;
- (double)masterClock;
- (void)setDontShowDRMUI:(BOOL)fp8;
- (BOOL)dontShowDRMUI;
- (id)context;
@end

