/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class MRContext, MRImage, MRLayerEffect, NSArray, NSConditionLock, NSDictionary, NSMutableArray, NSMutableDictionary, NSMutableSet, NSRecursiveLock, NSString, NSThread;

@interface MRRendererInternal : _ACAccountTypeIdentifierTwitter
{
    MRContext *mContext;
    double mMasterStartTime;
    double mMasterDuration;
    int mMasterMode;
    NSThread *mRenderThread;
    NSRecursiveLock *mRenderLock;
    NSConditionLock *mFrameLock;
    double mTimeOffset;
    double mUnalteredTimeOffset;
    double mMasterClock;
    double mTimeForResync;
    BOOL mRenderingRequested;
    BOOL mHasToRebuildAudio;
    BOOL mDontShowDRMUI;
    BOOL mSlaveFrameMode;
    struct CGPoint mContextOffset;
    NSMutableDictionary *mArguments;
    struct CGImage *mSnapshotAsCGImage;
    NSConditionLock *mSnapshotAsCGImageLock;
    int mPreviousMode;
    double mModeChangeTime;
    NSMutableArray *mSelectedLayers;
    NSMutableDictionary *mLayerHittings;
    NSMutableDictionary *mLayerTrackings;
    int mEventTracking;
    NSMutableSet *mLayersCurrentlyTrackedIn;
    MRLayerEffect *mLayerCurrentlyTextEditing;
    NSString *mCurrentlyEditedTextElement;
    BOOL mNeedsToResize;
    BOOL mNeedsToTemporaryResize;
    BOOL mNeedsToResumeOrPauseLayers;
    BOOL mNeedsToSynchronizeTimeInLayers;
    BOOL mNeedsToSynchronizeTimeInAudioMovies;
    struct CGSize mTemporarySize;
    double mMorphingStartTime;
    double mMorphingEndTime;
    float mMorphingRotationAngle;
    BOOL mMorphingHandlesRotation;
    MRImage *mSnapshotForMorphing;
    NSMutableArray *mActions;
    NSMutableDictionary *mAudioPlayerBuckets;
    NSArray *mAudioPlayerSortedBuckets;
    id <MRLiveSlideshowDelegate> mLiveSlideshowDelegate;
    id <MRAsynchronousOperationsDelegate> mAsynchronousOperationsDelegate;
    BOOL mScreenBurnTest;
    unsigned long long mScreenBurnTestCurrentPass;
    MRImage *mScreenBurnTestAccumulationImage1;
    MRImage *mScreenBurnTestAccumulationImage2;
    NSMutableArray *mNavigatorHistoryBack;
    NSMutableArray *mNavigatorHistoryForth;
    NSDictionary *mForcedState;
    BOOL mHideTextWhileEditing;
    double mFrameTime[64];
    unsigned long mFrameTimeIndex;
    struct __sFILE *mRenderingLogFile;
    double mPreviousStartTimeForLog;
    double mLastSaveTimeForLog;
}

@end

