/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class MRCroppingSprite, MRImage;

@interface MRShiftingTilesRenderable : _ACAccountTypeIdentifierTwitter
{
    MRImage *slide;
    MRCroppingSprite *sprite;
    struct CGPoint position;
    struct CGSize size;
}

- (void)setSprite:(id)fp8;
- (id)sprite;
- (id)slide;
- (void)setSlide:(id)fp8;
- (void)dealloc;

@end

