/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MRSlideProvider.h"

@interface MRSlideProvider (Private)
+ (void)applyKenBurnsForSlide:(id)fp8 inPlug:(id)fp12 forSize:(struct CGSize)fp16 atTime:(double)fp24 withTargetSize:(struct CGSize)fp32 kenBurnsType:(int)fp40 translation:(struct CGPoint *)fp44 scale:(float *)fp48 rotation:(float *)fp52;
@end

