/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface MRSphere : _ACAccountTypeIdentifierTwitter
{
    float *mVertices;
    float *mTextureCoordinates;
    float *mNormals;
    unsigned long mLongitudeResolution;
    unsigned long mLatitudeResolution;
    float mHalfLongitudeAngle;
    float mHalfLatitudeAngle;
    float mRadius;
}

- (void)setRadius:(float)fp8;
- (float)radius;
- (void)setHalfLatitudeAngle:(float)fp8;
- (float)halfLatitudeAngle;
- (void)setHalfLongitudeAngle:(float)fp8;
- (float)halfLongitudeAngle;
- (void)setLatitudeResolution:(unsigned long)fp8;
- (unsigned long)latitudeResolution;
- (void)setLongitudeResolution:(unsigned long)fp8;
- (unsigned long)longitudeResolution;
- (void)renderDumbImage:(id)fp8 inContext:(id)fp12 atPosition:(struct CGPoint)fp16 andSize:(struct CGSize)fp24;
- (void)dealloc;
- (id)init;

@end

