/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class EAGLContext;

@interface MRTexture : _ACAccountTypeIdentifierTwitter
{
    EAGLContext *mParentGLContext;
    unsigned long mWidth;
    unsigned long mHeight;
    unsigned int mTextureName;
    unsigned int mTextureTarget;
    unsigned long mPixelFormat;
    double mTimestamp;
    unsigned int mFramebufferName;
    EAGLContext *mGLContext;
    int mMinFilter;
    int mMagFilter;
    int mWrapS;
    int mWrapT;
    float mBorderColor[4];
}

- (int)wrapT;
- (int)wrapS;
- (int)magFilter;
- (int)minFilter;
- (unsigned int)framebufferName;
- (unsigned long)pixelFormat;
- (id)glContext;
- (void)setTimestamp:(double)fp8;
- (double)timestamp;
- (unsigned int)textureTarget;
- (unsigned int)textureName;
- (unsigned long)height;
- (unsigned long)width;
- (void)setWrapT:(int)fp8;
- (void)setWrapS:(int)fp8;
- (void)setMagFilter:(int)fp8;
- (void)setMinFilter:(int)fp8;
- (void)cleanup;
- (void)finalize;
- (void)dealloc;
- (id)initWithDatas:(void **)fp8 dataCount:(unsigned int)fp12 width:(unsigned long)fp16 height:(unsigned long)fp20 rowBytes:(unsigned long)fp24 inGLContext:(id)fp28 options:(id)fp32;
- (id)initWithData:(void *)fp8 width:(unsigned long)fp12 height:(unsigned long)fp16 rowBytes:(unsigned long)fp20 inGLContext:(id)fp24 options:(id)fp28;
- (id)initWithSize:(struct CGSize)fp8 inGLContext:(id)fp16 options:(id)fp20;

@end

