/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSMutableArray;

@interface MRTiledSprite : _ACAccountTypeIdentifierTwitter
{
    struct CGPoint mPosition;
    struct CGSize mHalfSize;
    float mRotation;
    struct CGRect mInnerRect;
    struct CGRect mOuterRect;
    BOOL mPreservesImageAspectRatio;
    BOOL mIsSealed;
    NSMutableArray *mTriangles;
    float *mVertices;
    float *mBasicTextureCoordinates;
    float *mInSpriteCoordinates;
    float *mTextureCoordinates[4];
    NSMutableArray *mMiddleTriangles;
    float *mMiddleVertices;
    float *mMiddleBasicTextureCoordinates;
    float *mMiddleInSpriteCoordinates;
    float *mMiddleTextureCoordinates[4];
    NSMutableArray *mOuterTriangles;
    float *mOuterVertices;
    float *mOuterBasicTextureCoordinates;
    float *mOuterInSpriteCoordinates;
    float *mOuterTextureCoordinates[4];
    struct CGSize mInSpriteCoordinatesFactor;
    struct CGPoint mInSpriteCoordinatesOffset;
    struct CGSize mTextureCoordinatesFactor[4];
    struct CGPoint mTextureCoordinatesOffset[4];
    char mNeedsTextureCoordinates[4];
    BOOL mNeedsInSpriteCoordinates;
    BOOL mNeedsToUpdateInSpriteCoordinates;
    BOOL mHitIsActive;
}

- (void)setPreservesImageAspectRatio:(BOOL)fp8;
- (BOOL)preservesImageAspectRatio;
- (void)setNeedsInSpriteCoordinates:(BOOL)fp8;
- (BOOL)needsInSpriteCoordinates;
- (void)setHitIsActive:(BOOL)fp8;
- (BOOL)hitIsActive;
- (struct CGRect)outerRect;
- (struct CGRect)innerRect;
- (float)rotation;
- (struct CGSize)halfSize;
- (struct CGPoint)position;
- (void)getOpaquePosition:(struct CGPoint *)fp8 andHalfSize:(struct CGSize *)fp12;
- (BOOL)getVerticesCoordinates:(struct CGPoint (*)[4])fp8 withMatrix:(float [16])fp12;
- (BOOL)hitAtPoint:(struct CGPoint)fp8 withInverseMatrix:(float [16])fp16 localPoint:(struct CGPoint *)fp20;
- (void)setSpriteCoordinatesFactor:(struct CGSize)fp8 andOffset:(struct CGPoint)fp16;
- (void)setTextureCoordinatesFactor:(struct CGSize)fp8 andOffset:(struct CGPoint)fp16 onTextureUnit:(unsigned int)fp24;
- (void)setNeedsTextureCoordinates:(BOOL)fp8 onTextureUnit:(unsigned int)fp12;
- (void)renderImage:(id)fp8 inContext:(id)fp12;
- (void)renderImageOuter:(id)fp8 inContext:(id)fp12;
- (void)renderImageMiddle:(id)fp8 inContext:(id)fp12;
- (void)renderImageInner:(id)fp8 inContext:(id)fp12;
- (void)renderDumbImage:(id)fp8 inContext:(id)fp12;
- (void)updateInSpriteCoordinates;
- (void)seal;
- (void)subtractOpaqueSpriteWithPosition:(struct CGPoint)fp8 halfSize:(struct CGSize)fp16 andRotation:(float)fp24;
- (void)subtractSpriteAtPosition:(struct CGPoint)fp8 withSize:(struct CGSize)fp16 zRotation:(float)fp24 andOpaqueRect:(struct CGRect)fp28 inContext:(id)fp44;
- (void)subtractSprite:(id)fp8;
- (void)subtractTriangle:(float [6])fp8 fromTriangle:(float [6])fp12 addTrianglesTo:(id)fp16;
- (void)dealloc;
- (id)initWithPosition:(struct CGPoint)fp8 size:(struct CGSize)fp16 zRotation:(float)fp24 innerRect:(struct CGRect)fp28 outerRect:(struct CGRect)fp44 context:(id)fp60;
- (id)initWithPosition:(struct CGPoint)fp8 size:(struct CGSize)fp16 zRotation:(float)fp24 innerRect:(struct CGRect)fp28 context:(id)fp44;

@end

