/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

#import "MRLoadable-Protocol.h"
#import "MRRenderable-Protocol.h"

@class MRImage, MRLayer, NSDictionary, NSString;

@interface MRTransition : _ACAccountTypeIdentifierTwitter <MRLoadable, MRRenderable>
{
    NSDictionary *mDescription;
    id mTransitioner;
    MRLayer *mSourceLayer;
    MRLayer *mTargetLayer;
    MRImage *mSourceLayerImage;
    MRImage *mTargetLayerImage;
    MRImage *mOutputImage;
    NSString *mTransitionID;
    NSString *mPresetID;
    NSDictionary *mAttributes;
    NSDictionary *mFlattenedAttributes;
    BOOL mNeedsToUpdateAttributes;
    struct CGSize mPixelSize;
}

+ (id)retainedTransitionWithTransitionID:(id)fp8 forTransitioner:(id)fp12;
- (void)setPixelSize:(struct CGSize)fp8;
- (struct CGSize)pixelSize;
- (id)attributes;
- (void)setPresetID:(id)fp8;
- (id)presetID;
- (id)transitionID;
- (id)targetLayerImage;
- (id)sourceLayerImage;
- (void)setTargetLayer:(id)fp8;
- (id)targetLayer;
- (void)setSourceLayer:(id)fp8;
- (id)sourceLayer;
- (id)patchworkAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (id)retainedByUserRenderedImageAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (void)renderAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)prerenderForTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)isInfinite;
- (BOOL)isAlphaFriendly;
- (BOOL)isOpaque;
- (BOOL)isNative3D;
- (void)cancelLoading;
- (void)unload;
- (void)loadForTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20 now:(BOOL)fp24;
- (BOOL)isLoadedForTime:(double)fp8;
- (void)setTargetLayerImage:(id)fp8;
- (void)setSourceLayerImage:(id)fp8;
- (void)setAttributes:(id)fp8;
- (BOOL)needsTargetLayerImageForPrecomputing;
- (BOOL)needsSourceLayerImageForPrecomputing;
- (BOOL)noContentsMotion;
- (BOOL)isRetainedByTransitioner;
- (void)releaseByTransitioner:(id)fp8;
- (void)retainByTransitioner:(id)fp8;
- (void)cleanup;
- (void)finalize;
- (void)dealloc;
- (id)initWithTransitionID:(id)fp8;

@end

