/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MRTransition.h"

@class MRImageProvider;

@interface MRTransitionShortMapZoom : MRTransition
{
    MRImageProvider *mGradientProvider;
    MRImageProvider *mPinProvider;
    MRImageProvider *mYellowPinProvider;
    MRImageProvider *mRedPinProvider;
    MRImageProvider *mBoxShadowSmall;
}

- (void)drawSortedPins:(id)fp8 providers:(id)fp12 attributes:(id)fp16 offset:(struct CGPoint)fp20 outro:(BOOL)fp28 atTime:(double)fp32 inContext:(id)fp40 withArguments:(id)fp44;
- (void)renderAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (void)setAttributes:(id)fp8;
- (BOOL)prerenderForTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (BOOL)isLoadedForTime:(double)fp8;
- (void)setPixelSize:(struct CGSize)fp8;
- (void)_cleanup;
- (id)initWithTransitionID:(id)fp8;

@end

