/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSMutableDictionary;

@interface MRTransitionManager : _ACAccountTypeIdentifierTwitter
{
    NSMutableDictionary *mTransitionRepository;
    NSMutableDictionary *mTransitionSets;
    NSMutableDictionary *mTransitionPools;
}

+ (void)loadTransitionManagerWithPaths:(id)fp8;
+ (id)sharedManager;
+ (void)initialize;
- (id)attributesForTransitionID:(id)fp8 andPresetID:(id)fp12;
- (BOOL)needsTargetLayerToBeOpaqueForSimple3DTransitionSubtype:(int)fp8;
- (BOOL)needsSourceLayerToBeOpaqueForSimple3DTransitionSubtype:(int)fp8;
- (BOOL)needsTargetLayerImageForPrecomputingForTransitionID:(id)fp8;
- (BOOL)needsSourceLayerImageForPrecomputingForTransitionID:(id)fp8;
- (BOOL)noContentsMotionForTransitionID:(id)fp8;
- (BOOL)canHandleKenBurnsForTransitionID:(id)fp8;
- (id)resourcePathForTransitionID:(id)fp8 andResource:(id)fp12;
- (id)descriptionForTransitionID:(id)fp8;
- (void)recycleTransition:(id)fp8;
- (id)transitionWithTransitionID:(id)fp8;
- (void)releaseResources;
- (void)cleanup;
- (void)dealloc;
- (id)initWithPaths:(id)fp8;

@end

