/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MRTransition.h"

@class NSMutableArray;

@interface MRTransitionTileFlip : MRTransition
{
    NSMutableArray *mSortedTiles;
    unsigned long mNumberOfTilesX;
    unsigned long mNumberOfTilesY;
    float mFlipOverlap;
    unsigned char mDirection;
    BOOL mUseLighting;
}

- (void)renderAtTime:(double)fp8 inContext:(id)fp16 withArguments:(id)fp20;
- (void)setAttributes:(id)fp8;
- (void)buildTiles;
- (void)releaseByTransitioner:(id)fp8;
- (void)cleanup;
- (id)initWithTransitionID:(id)fp8;

@end

