/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MUPoolObject.h"

@interface MRUniform : MUPoolObject
{
    float x;
    float y;
    float z;
    float w;
    int i;
    int length;
}

+ (CDAnonymousStruct3 *)poolInfo;
- (id)initWithI:(float)fp8;
- (id)initWithX:(float)fp8 Y:(float)fp12 Z:(float)fp16 W:(float)fp20;
- (id)initWithX:(float)fp8 Y:(float)fp12 Z:(float)fp16;
- (id)initWithX:(float)fp8 Y:(float)fp12;
- (id)initWithX:(float)fp8;

@end

