/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@interface MRUtilities : _ACAccountTypeIdentifierTwitter
{
}

+ (int)operatingSystemMajorVersion;
+ (int)operatingSystemMinorVersion;
+ (int)operationQueueConcurrentOperationCount;
+ (id)executeScript:(id)fp8 withHeader:(id)fp12 andAttributes:(id)fp16;
+ (struct CGColorSpace *)newColorSpaceForDevice;
+ (struct CGColor *)CGColorFromString:(id)fp8;
+ (double)transformTime:(double)fp8 forAnimationPath:(id)fp16 inPlug:(id)fp20;
+ (struct CGPoint)valueForPointAnimationPath:(id)fp8 inPlug:(id)fp12 atTime:(double)fp16 defaultsTo:(struct CGPoint)fp24 previousKeyPoint:(struct CGPoint *)fp32 nextKeyPoint:(struct CGPoint *)fp36;
+ (float)valueForScalarAnimationPath:(id)fp8 inPlug:(id)fp12 atTime:(double)fp16 defaultsTo:(float)fp24 previousKeyValue:(float *)fp28 nextKeyValue:(float *)fp32;
+ (void)initialize;

@end

