/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MUPoolObject.h"

@interface MURandom : MUPoolObject
{
    long _state[31];
    long *_frontPtr;
    long *_rearPtr;
    long *_endPtr;
}

+ (id)randomGeneratorWithSeed:(unsigned long)fp8;
+ (CDAnonymousStruct3 *)poolInfo;
- (float)randomFloatInRange:(float)fp8:(float)fp12;
- (long)randomInt;
- (void)_seed:(unsigned long)fp8;

@end

