/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol MZEffectTiming
- (double)phaseOutDuration;
- (double)mainDuration;
- (double)phaseInDuration;
- (double)lowestDisplayTime;
- (double)displayTimeForTextAtIndex:(unsigned int)fp8;
- (double)displayTimeForSlideAtIndex:(unsigned int)fp8;
- (double)showDurationForSlideAtIndex:(unsigned int)fp8;
- (double)showTimeForSlideAtIndex:(unsigned int)fp8;
- (void)setPhaseInDuration:(double)fp8 mainDuration:(double)fp16 phaseOutDuration:(double)fp24;
@end

