/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BLSharingServiceViewController.h"

#import "P2PUploadOperationDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class BLActivityAlert, GKSession, NSArray, NSMutableArray, NSOperationQueue, NSString, UITableView;

@interface P2PGKUIManagePeerViewController : BLSharingServiceViewController <P2PUploadOperationDelegate, UITableViewDelegate, UITableViewDataSource>
{
    UITableView *m_tableView;
    BLActivityAlert *m_activityAlert;
    GKSession *m_session;
    id m_getPeerIDListBlock;
    id m_connectToPeerBlock;
    id m_disconnectFromPeerBlock;
    id m_checkAcknowledgementPacket;
    NSArray *m_outgoingMediaList;
    NSMutableArray *_filteredPeerIDList;
    NSString *_selectedPeerID;
    BOOL _cancelRequested;
    NSOperationQueue *_operationQueue;
    id m_checkAcknowledgementPacketBlock;
}

- (void)setOutgoingMediaList:(id)fp8;
- (id)outgoingMediaList;
- (void)setCheckAcknowledgementPacketBlock:(id)fp(null);
- (id)checkAcknowledgementPacketBlock;
- (void)setDisconnectFromPeerBlock:(id)fp(null);
- (id)disconnectFromPeerBlock;
- (void)setConnectToPeerBlock:(id)fp(null);
- (id)connectToPeerBlock;
- (void)setGetPeerIDListBlock:(id)fp(null);
- (id)getPeerIDListBlock;
- (void)setSession:(id)fp8;
- (id)session;
- (void)reload;
- (void)uploadOperationDidEnd:(id)fp8;
- (void)uploadOperationInProgress:(id)fp8;
- (void)uploadOperationWillStart:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (float)tableView:(id)fp8 heightForFooterInSection:(int)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (struct CGSize)requiredPopoverSize;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)a_share:(id)fp8;
- (BOOL)cancelRequested;
- (void)setCancelRequested:(BOOL)fp8;
- (void)loadView;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (id)description;
- (void)dealloc;
- (id)init;
- (void)_discoveredPeerListChanged:(id)fp8;

@end

