/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class GKSession, NSArray, NSError, NSObject, NSObject<P2PUploadOperationDelegate>, NSString;

@interface P2PGKUploadOperation : _ACAccountTypeIdentifierTwitter
{
    GKSession *m_session;
    NSString *m_peerID;
    NSArray *m_outgoingMediaList;
    id m_checkAcknowledgementPacketBlock;
    NSObject<P2PUploadOperationDelegate> *m_delegate;
    NSObject *m_context;
    NSError *m_error;
    int _totalItems;
    int _completedItems;
}

+ (id)itemDescriptionWithPath:(id)fp8;
+ (id)uuidWithAdjustmentDataDeviceSpecificFileName:(id)fp8 deviceUuid:(id *)fp12;
+ (id)uuidWithImageDataDeviceSpecificFileName:(id)fp8 deviceUuid:(id *)fp12;
+ (id)uuidWithMetaDataDeviceSpecificFileName:(id)fp8 deviceUuid:(id *)fp12;
+ (id)uuidWithObjectDataDeviceSpecificFileName:(id)fp8 deviceUuid:(id *)fp12;
+ (id)adjustmentDataDeviceSpecificFileNameWithObjectUuid:(id)fp8;
+ (id)imageDataDeviceSpecificFileNameWithObjectUuid:(id)fp8;
+ (id)metaDataDeviceSpecificFileNameWithObjectUuid:(id)fp8;
+ (id)objectDataDeviceSpecificFileNameWithObjectUuid:(id)fp8;
- (int)completedItems;
- (int)totalItems;
- (void)setError:(id)fp8;
- (id)error;
- (void)setContext:(id)fp8;
- (id)context;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setCheckAcknowledgementPacketBlock:(id)fp(null);
- (id)checkAcknowledgementPacketBlock;
- (void)setOutgoingMediaList:(id)fp8;
- (id)outgoingMediaList;
- (void)setPeerID:(id)fp8;
- (id)peerID;
- (void)setSession:(id)fp8;
- (id)session;
- (id)initWithSession:(id)fp8 peerID:(id)fp12 outgoingMediaList:(id)fp16 checkAcknowledgementPacketBlock:(id)fp(null) delegate:(void)fp20;
- (id)className;
- (void)cancel;
- (void)main;
- (id)description;
- (void)dealloc;
- (id)_uploadData:(id)fp8 withFileName:(id)fp12 itemIndex:(unsigned int)fp16 itemCount:(unsigned int)fp20 abortBlock:(id)fp(null);

@end

