/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ACAccountTypeIdentifierTwitter.h"

@class NSData, NSMutableData, NSMutableIndexSet, NSString;

@interface P2PGKDataHandler : _ACAccountTypeIdentifierTwitter
{
    NSString *m_fileName;
    NSData *m_data;
    unsigned int m_itemIndex;
    unsigned int m_itemCount;
    unsigned int _packetIndex;
    unsigned int _packetCount;
    NSMutableData *_tempData;
    unsigned int _tempFirstPacketPayloadLength;
    NSMutableIndexSet *_tempPacketIndexSet;
}

+ (id)acknowledgementDataWithPacketUuid:(id)fp8;
+ (id)dataHandler;
+ (id)dataHandlerWithFileName:(id)fp8 data:(id)fp12 itemIndex:(unsigned int)fp16 itemCount:(unsigned int)fp20;
- (unsigned int)packetCount;
- (unsigned int)packetIndex;
- (void)setItemCount:(unsigned int)fp8;
- (unsigned int)itemCount;
- (void)setItemIndex:(unsigned int)fp8;
- (unsigned int)itemIndex;
- (void)setData:(id)fp8;
- (id)data;
- (void)setFileName:(id)fp8;
- (id)fileName;
- (BOOL)addPacketData:(id)fp8 type:(int *)fp12 uuid:(id *)fp16;
- (id)packetDataAtIndex:(unsigned int)fp8 withType:(int)fp12 uuid:(id *)fp16;
- (id)initWithFileName:(id)fp8 data:(id)fp12;
- (id)description;
- (void)dealloc;
- (void)_computePacketCount;

@end

