/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol P2PUploadOperationDelegate
- (void)uploadOperationDidEnd:(id)fp8;
- (void)uploadOperationInProgress:(id)fp8;
- (void)uploadOperationWillStart:(id)fp8;
@end

